
EXEC DROPROLE 'ZSM', 'ZSM_RDR';
EXEC CREATEROLE 'ZSM', 'ZSM_RDR', 'Reader', 'DCC.ZOS.ZSM.exe';

EXEC DROPROLE 'ZSM', 'ZSM_ATM';
EXEC CREATEROLE 'ZSM', 'ZSM_ATM', 'Attendance Marker', 'DCC.ZOS.ZSM.exe';

EXEC DROPROLE 'ZSM', 'ZSM_USR';
EXEC CREATEROLE 'ZSM', 'ZSM_USR', 'User', 'DCC.ZOS.ZSM.exe';

EXEC DROPROLE 'ZSM', 'ZSM_SUP';
EXEC CREATEROLE 'ZSM', 'ZSM_SUP', 'Supervisor', 'DCC.ZOS.ZSM.exe';

EXEC DROPROLE 'ZSM', 'ZSM_ADM';
EXEC CREATEROLE 'ZSM', 'ZSM_ADM', 'Administrator', 'DCC.ZOS.ZSM.exe';

EXEC DROPROLE 'ZSM', 'ZSM_CU';
EXEC CREATEROLE 'ZSM', 'ZSM_CU', 'Centre User', 'DCC.ZOS.ZSM.exe';

EXEC DROPROLE 'ZSM', 'ZSM_PC';
EXEC CREATEROLE 'ZSM', 'ZSM_PC', 'Photo Clicking User', 'DCC.ZOS.ZSM.exe';
