delete from medical_disabilities

INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Allergy', 'AL')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Amputation (Hand)', 'AH')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Amputation (Left Arm)', 'AM')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Artificial Leg', 'ALG')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Asthma', 'AS')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Arthritis', 'AR')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('B/L Kidney Failure', 'KF')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Back Bone Problem', 'BP')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Breathlessness', 'BL')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Breast Cancer', 'BC')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Cervical Spondylosis', 'CS')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Deaf', 'DF')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Dumb', 'DU')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Ear Disorder', 'ED')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Foot Drop', 'FD')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Gout', 'GT')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Hearing Impairment', 'HI')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Kidney Problem', 'KP')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Knee Joint Disorder', 'KJ')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Loss of Speech- Paralysis', 'LSP')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Mentally challenged', 'MC')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Migraine', 'MI')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('One Eye', 'OE')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd ) 
VALUES ('Osteoporosis', 'OS')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Ovary Cancer', 'OC')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Paralytic', 'PA')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Parkinson''s disease', 'PR')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Physical Handicap', 'PH')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Physical Handicap (Hand)', 'HH')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Physical Handicap (Leg)', 'HL')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Polio', 'PO')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Polio (Foot)', 'PF')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Polio (Hand)', 'PLH')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Polio (Leg)', 'PL')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Rod in Arm', 'RA')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Rod in Leg', 'RL')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Skin Allergy', 'SA')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Slip Disc', 'SD')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Spondylitis', 'SP')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Sunburn', 'SB')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Thyroid', 'TH')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Thyroid, Allergy', 'TA')
INSERT INTO   medical_disabilities ( medical_disability_nm, medical_disability_cd )
VALUES ('Varicose Veins', 'VV')
