INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Aadhar U.I.D.', 'UID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Add. Proof Pending', 'PRP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Adhikar Patra', 'ADP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Advocate ID', 'AID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Affidavit', 'AFF')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Agreement Copy', 'AGC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Allotment Letter', 'ALL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Application', 'APL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Applied Voters Card', 'AVC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Appointment Letter', 'APP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Area Sec.- Approval', 'ASA')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Caretaker - Approval', 'CAA')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Approved by HOD', 'HOD')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Secretary - Approval', 'SEC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Sewa Samiti-Approval', 'SWA')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Army ID Card', 'ARM')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Authority Letter', 'AUT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Bank Certificate', 'BAC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Bank ID Card', 'BID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Bank Letter', 'BLT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Bank Pass Book', 'BPB')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Bar Association ID', 'BAI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Birth Certificate', 'BIC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Bond', 'BON')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('BPL Card', 'BPL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Brothers Add Proof', 'BAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Caretaker Letter', 'CTL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Caste Certificate', 'CCE')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Certificate', 'CER')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Childs Address Proof', 'CAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Citizenship Card', 'CTC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Co. Allotment Letter', 'CAL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('College ID Card', 'CIC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('College Leaving Cert', 'CLC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Company ID Card', 'CID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Company Letter/Cert', 'CLT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Cooking Gas Paper', 'CGP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Defense Dept ID', 'DDI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Defense Dept Letter', 'DDL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Dependent ID card ', 'DIC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Doctor ID', 'DID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Domicile Certificate', 'DOM')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Driving Licence', 'DLI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Relatives DrivingLic', 'RDL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Electricity Bill', 'ELB')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Employment Letter', 'EML')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Endosement Form', 'ENF')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('ESIC Card', 'ESI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('ExServiceman ID Card', 'EID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Exam Certifcate', 'EXC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Family ID Card', 'FID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Farmers ID', 'FRI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Fathers Add Proof', 'FAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Gazette', 'GAZ')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Govt Dept Letter', 'GDL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Govt. Dept Cert', 'GDC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Govt. Dept ID', 'GDI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Gram Panchayat Cert', 'GPC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Gram Panchayat ID', 'GPI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Gram Panchayat Ltr', 'GPL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Hospital ID Card', 'HID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Hostel ID Card', 'OID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('HSC Certificate', 'HSC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('HSC Marksheet', 'HSM')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Husbands Add Proof', 'HAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('ID Card', 'IDC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('L & L Agreement', 'LLA')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Land record', 'LRE')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Landlord''s Proof', 'LAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Letter', 'LET')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Library Card', 'LIB')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('LIC Policy', 'LIC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Marriage Certificate', 'MAR')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Medical Council ID', 'MCI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Membership Card', 'MEM')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Mothers Add Proof', 'MAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Muncipal Dept Letter', 'MDL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Municipality Cert', 'MUN')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Nagar Sewak Cert', 'NSC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Nagar Sewak I D', 'NSI')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Name Change Cert', 'NCH')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Naval Certificate', 'NAC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Naval ID Card', 'NID')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Notary Certificate', 'NOT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('P G Agreement', 'PGA')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Pan Card', 'PAN')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Passport', 'PAS')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Pensioner''s ID Card', 'PEN')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('PIO Card', 'PIO')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Police ID', 'POL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Police Letter', 'PLL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Possession Letter', 'POS')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Property Card', 'PRO')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Property Tax Bill', 'PTB')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Ration Card', 'RAT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Relatives Add Proof', 'RAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Residence Cert', 'REC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Residence Permit', 'REP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Residence Proof', 'RES')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Resident Card', 'REC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('School ID Card', 'SCH')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('School Leaving Cert', 'SLC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Senior Citizen Card', 'SCC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Shop Regn.cert.', 'SRC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Social Security Card', 'SSC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Society Bill', 'SOB')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Society Certificate', 'SOC')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Society Letter', 'SOL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Spouse Address Proof', 'SAP')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('SSC Leaving Cert', 'SSL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('SSC Marksheet', 'SSM')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Telephone Bill', 'TBL')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Transfer Certificate', 'TCE')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Vehicle RC book', 'RCB')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Voters Card', 'VOT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Voucher', 'VOU')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Water Bill', 'WAT')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Wedding Card', 'WED')
INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
VALUES ('Wireman''s Cert', 'WIC')
