/* ==================================================================================
    Source File		:	upgrade_v5.77.sql
    Author(s)		:	Anil
    Started On		:	24 Oct, 2015
    Last updated	:	
    Module ID		:	ZSM (Zonal Sewadars Manager)
    Language		:	TRANSACT-SQL
    Reviewed By		:
    Reviewed On		:
    ==================================================================================
																		   Usage Notes
    ----------------------------------------------------------------------------------
		Upgrade Script for v5.77
				....
		
    ==================================================================================
								      								  Revision History
    ----------------------------------------------------------------------------------
   ==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

USE SysAdmin
GO

UPDATE packages
	SET	version_no = 5.77,
		version_dt = GetDate()
WHERE	package_id = 'ZSM'

-- =============================================================================
--		ZSM changes
-- =============================================================================

USE ZSM
GO

-- =============================================================================



IF EXISTS (SELECT * FROM systypes WHERE name = 'address_proof_id')
	EXEC	sp_droptype	'address_proof_id'
GO
EXEC	sp_addtype	'address_proof_id',	SMALLINT,			'NULL'
GO

-- =============================================================================

CREATE	TABLE	other_address_proofs
(
	address_proof_id				address_proof_id		NOT NULL 	IDENTITY (1, 1)
																		CONSTRAINT	OtherAddressProofs_PK_AddressProofID
																			PRIMARY KEY	NONCLUSTERED,
	address_proof_nm 				gnc_long_nm				NOT NULL	CONSTRAINT	OtherAddressProofs_U1_AddressProofName
																			UNIQUE	CLUSTERED,
	address_proof_cd				VARCHAR (10)			NOT NULL	CONSTRAINT	OtherAddressProofs_U2_AddressProofCode
																			UNIQUE	NONCLUSTERED,
	effective_from					DATETIME				NOT NULL	CONSTRAINT	OtherAddressProofs_DF_EffectiveFrom
																			DEFAULT CONVERT (VARCHAR (11), GetDate(), 106),
	effective_till					DATETIME				NOT NULL	CONSTRAINT	OtherAddressProofs_DF_EffectiveTill
																			DEFAULT '31-Dec-9999',

		CONSTRAINT	OtherAddressProofs_CK_EffectiveDates
			CHECK	(	effective_from <= effective_till	)
)
GO

ALTER TABLE sewadars_details
	ADD	other_address_proof_id address_proof_id			NULL		CONSTRAINT	SewadarsDetails_FK_OtherAddressProofID
									REFERENCES	other_address_proofs
GO


DECLARE @tbl	TABLE	(address_proof_nm	VARCHAR (35), address_proof_cd	varchar (10));

--setup table other_address_proofs
INSERT INTO   @tbl VALUES ('Aadhar U.I.D.', 'UID')
INSERT INTO   @tbl VALUES ('Add. Proof Pending', 'PRP')
INSERT INTO   @tbl VALUES ('Adhikar Patra', 'ADP')
INSERT INTO   @tbl VALUES ('Advocate ID', 'AID')
INSERT INTO   @tbl VALUES ('Affidavit', 'AFF')
INSERT INTO   @tbl VALUES ('Agreement Copy', 'AGC')
INSERT INTO   @tbl VALUES ('Allotment Letter', 'ALL')
INSERT INTO   @tbl VALUES ('Application', 'APL')
INSERT INTO   @tbl VALUES ('Applied Voters Card', 'AVC')
INSERT INTO   @tbl VALUES ('Appointment Letter', 'APP')
INSERT INTO   @tbl VALUES ('Area Sec. Approval', 'ASA')
INSERT INTO   @tbl VALUES ('Caretaker Approval', 'CAA')
INSERT INTO   @tbl VALUES ('Approved by HOD', 'HOD')
INSERT INTO   @tbl VALUES ('Secretary Approval', 'SEC')
INSERT INTO   @tbl VALUES ('Sewa Samiti Approval', 'SWA')
INSERT INTO   @tbl VALUES ('Army ID Card', 'ARM')
INSERT INTO   @tbl VALUES ('Authority Letter', 'AUT')
INSERT INTO   @tbl VALUES ('Bank Certificate', 'BAC')
INSERT INTO   @tbl VALUES ('Bank ID Card', 'BID')
INSERT INTO   @tbl VALUES ('Bank Letter', 'BLT')
INSERT INTO   @tbl VALUES ('Bank Pass Book', 'BPB')
INSERT INTO   @tbl VALUES ('Bar Association ID', 'BAI')
INSERT INTO   @tbl VALUES ('Birth Certificate', 'BIC')
INSERT INTO   @tbl VALUES ('Bond', 'BON')
INSERT INTO   @tbl VALUES ('BPL Card', 'BPL')
INSERT INTO   @tbl VALUES ('Brother''s Add Proof', 'BAP')
INSERT INTO   @tbl VALUES ('Caretaker Letter', 'CTL')
INSERT INTO   @tbl VALUES ('Caste Certificate', 'CCE')
INSERT INTO   @tbl VALUES ('Certificate', 'CER')
INSERT INTO   @tbl VALUES ('Childs Address Proof', 'CAP')
INSERT INTO   @tbl VALUES ('Citizenship Card', 'CTC')
INSERT INTO   @tbl VALUES ('Co. Allotment Letter', 'CAL')
INSERT INTO   @tbl VALUES ('College ID Card', 'CIC')
INSERT INTO   @tbl VALUES ('College Leaving Cert', 'CLC')
INSERT INTO   @tbl VALUES ('Company ID Card', 'CID')
INSERT INTO   @tbl VALUES ('Company Letter/Cert', 'CLT')
INSERT INTO   @tbl VALUES ('Cooking Gas Paper', 'CGP')
INSERT INTO   @tbl VALUES ('Defense Dept ID', 'DDI')
INSERT INTO   @tbl VALUES ('Defense Dept Letter', 'DDL')
INSERT INTO   @tbl VALUES ('Dependent ID card ', 'DIC')
INSERT INTO   @tbl VALUES ('Doctor ID', 'DID')
INSERT INTO   @tbl VALUES ('Domicile Certificate', 'DOM')
INSERT INTO   @tbl VALUES ('Driving Licence', 'DLI')
INSERT INTO   @tbl VALUES ('Relatives DrivingLic', 'RDL')
INSERT INTO   @tbl VALUES ('Electricity Bill', 'ELB')
INSERT INTO   @tbl VALUES ('Employment Letter', 'EML')
INSERT INTO   @tbl VALUES ('Endosement Form', 'ENF')
INSERT INTO   @tbl VALUES ('ESIC Card', 'ESI')
INSERT INTO   @tbl VALUES ('ExServiceman ID Card', 'EID')
INSERT INTO   @tbl VALUES ('Exam Certifcate', 'EXC')
INSERT INTO   @tbl VALUES ('Family ID Card', 'FID')
INSERT INTO   @tbl VALUES ('Farmers ID', 'FRI')
INSERT INTO   @tbl VALUES ('Father''s Add Proof', 'FAP')
INSERT INTO   @tbl VALUES ('Gazette', 'GAZ')
INSERT INTO   @tbl VALUES ('Govt Dept Letter', 'GDL')
INSERT INTO   @tbl VALUES ('Govt. Dept Cert', 'GDC')
INSERT INTO   @tbl VALUES ('Govt. Dept ID', 'GDI')
INSERT INTO   @tbl VALUES ('Gram Panchayat Cert', 'GPC')
INSERT INTO   @tbl VALUES ('Gram Panchayat ID', 'GPI')
INSERT INTO   @tbl VALUES ('Gram Panchayat Ltr', 'GPL')
INSERT INTO   @tbl VALUES ('Hospital ID Card', 'HID')
INSERT INTO   @tbl VALUES ('Hostel ID Card', 'OID')
INSERT INTO   @tbl VALUES ('HSC Certificate', 'HSC')
INSERT INTO   @tbl VALUES ('HSC Marksheet', 'HSM')
INSERT INTO   @tbl VALUES ('ID Card', 'IDC')
INSERT INTO   @tbl VALUES ('L & L Agreement', 'LLA')
INSERT INTO   @tbl VALUES ('Land record', 'LRE')
INSERT INTO   @tbl VALUES ('Landlord''s Proof', 'LAP')
INSERT INTO   @tbl VALUES ('Letter', 'LET')
INSERT INTO   @tbl VALUES ('Library Card', 'LIB')
INSERT INTO   @tbl VALUES ('LIC Policy', 'LIC')
INSERT INTO   @tbl VALUES ('Marriage Certificate', 'MAR')
INSERT INTO   @tbl VALUES ('Medical Council ID', 'MCI')
INSERT INTO   @tbl VALUES ('Membership Card', 'MEM')
INSERT INTO   @tbl VALUES ('Mother''s Add Proof', 'MAP')
INSERT INTO   @tbl VALUES ('Muncipal Dept Letter', 'MDL')
INSERT INTO   @tbl VALUES ('Municipality Cert', 'MUN')
INSERT INTO   @tbl VALUES ('Nagar Sewak Cert', 'NSC')
INSERT INTO   @tbl VALUES ('Nagar Sewak I D', 'NSI')
INSERT INTO   @tbl VALUES ('Name Change Cert', 'NCH')
INSERT INTO   @tbl VALUES ('Naval Certificate', 'NAC')
INSERT INTO   @tbl VALUES ('Naval ID Card', 'NID')
INSERT INTO   @tbl VALUES ('Notary Certificate', 'NOT')
INSERT INTO   @tbl VALUES ('P G Agreement', 'PGA')
INSERT INTO   @tbl VALUES ('Pan Card', 'PAN')
INSERT INTO   @tbl VALUES ('Passport', 'PAS')
INSERT INTO   @tbl VALUES ('Pensioner''s ID Card', 'PEN')
INSERT INTO   @tbl VALUES ('PIO Card', 'PIO')
INSERT INTO   @tbl VALUES ('Police ID', 'POL')
INSERT INTO   @tbl VALUES ('Police Letter', 'PLL')
INSERT INTO   @tbl VALUES ('Possession Letter', 'POS')
INSERT INTO   @tbl VALUES ('Property Card', 'PRO')
INSERT INTO   @tbl VALUES ('Property Tax Bill', 'PTB')
INSERT INTO   @tbl VALUES ('Ration Card', 'RAT')
INSERT INTO   @tbl VALUES ('Relatives Add Proof', 'RAP')
INSERT INTO   @tbl VALUES ('Residence Cert', 'REC')
INSERT INTO   @tbl VALUES ('Residence Permit', 'REP')
INSERT INTO   @tbl VALUES ('Residence Proof', 'RES')
INSERT INTO   @tbl VALUES ('Resident Card', 'RCD')
INSERT INTO   @tbl VALUES ('School ID Card', 'SCH')
INSERT INTO   @tbl VALUES ('School Leaving Cert', 'SLC')
INSERT INTO   @tbl VALUES ('Senior Citizen Card', 'SCC')
INSERT INTO   @tbl VALUES ('Shop Regn.cert.', 'SRC')
INSERT INTO   @tbl VALUES ('Social Security Card', 'SSC')
INSERT INTO   @tbl VALUES ('Society Bill', 'SOB')
INSERT INTO   @tbl VALUES ('Society Certificate', 'SOC')
INSERT INTO   @tbl VALUES ('Society Letter', 'SOL')
INSERT INTO   @tbl VALUES ('Spouse Address Proof', 'SAP')
INSERT INTO   @tbl VALUES ('SSC Leaving Cert', 'SSL')
INSERT INTO   @tbl VALUES ('SSC Marksheet', 'SSM')
INSERT INTO   @tbl VALUES ('Telephone Bill', 'TBL')
INSERT INTO   @tbl VALUES ('Transfer Certificate', 'TCE')
INSERT INTO   @tbl VALUES ('Vehicle RC book', 'RCB')
INSERT INTO   @tbl VALUES ('Voters Card', 'VOT')
INSERT INTO   @tbl VALUES ('Voucher', 'VOU')
INSERT INTO   @tbl VALUES ('Water Bill', 'WAT')
INSERT INTO   @tbl VALUES ('Wedding Card', 'WED')
INSERT INTO   @tbl VALUES ('Wireman''s Cert', 'WIC')


SELECT	address_proof_cd, count(*)
	FROM @tbl 
	group by address_proof_cd
	having count(*) > 1
-- =============================================================================

INSERT INTO   other_address_proofs ( address_proof_nm, address_proof_cd )
	SELECT	address_proof_nm, address_proof_cd
	FROM	@tbl;

-- =============================================================================

-- =============================================================================
-- =============================================================================
--	Data migration steps to be added here.
-- =============================================================================


DECLARE @mgr	TABLE	(new_val	VARCHAR (50), old_val	varchar (50));

-- fix existing entries
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', ' Aadhar U.I.D')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', ' Pan Card')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Proof Pending')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', ' School Leaving')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', ' School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', ' signed by secr')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', ' U.I.D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', ' U.I.D Card')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', '10th Mark sheet')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'A. Sec. Aprv. L')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadaar card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar (UID)')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AADHAAR Acknowl')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar ID Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar U I D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar UID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhaar Unique ')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar  UID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AADHAR ID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar Registra')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar rrU.I.D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AADHAR U I Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AADHAR U.I Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AAdhar U.I. Car')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar U.I.D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar U.I.D.')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar U.ID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AADHAR UI CARD')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar UID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar UID Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'AADHAR....UID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Adahar Card ')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Adahar UID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Adahare Card')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Address Proof Pending')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'adhaar')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Adhaar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Adhar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Adhar UId')
INSERT INTO @mgr	VALUES	 ( 'Adhikar Patra', 'Adhikar Patra ')
INSERT INTO @mgr	VALUES	 ( 'Advocate ID', 'Advocate I. Car')
INSERT INTO @mgr	VALUES	 ( 'Advocate ID', 'Advocate ID')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Affi-davit')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Affidavit')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Affidavite')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Aggrement Copy')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreemant')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Copy')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Deed')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Formn')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Index')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Agreement Leave @ Li')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Agreement of le')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Paper')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Proof')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Agreement(affidavit)')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agrement Copy')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agrement Papers')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agrmt, Elect. Bill')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agrrement')
INSERT INTO @mgr	VALUES	 ( 'Allotment Letter', 'Allotment Lette')
INSERT INTO @mgr	VALUES	 ( 'Allotment Letter', 'Allotment Letter')
INSERT INTO @mgr	VALUES	 ( 'Applied Voters Card', 'App. Electoral Roll')
INSERT INTO @mgr	VALUES	 ( 'Appointment Letter', 'Appointment let')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti Approval', 'Appr.By SewaSam')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Approoved By In')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Approved Addres')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Approved By Ksg')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Approved by Sec')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Approved by Sew')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Area Secre. Let')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Area Secretary ')
INSERT INTO @mgr	VALUES	 ( 'Army ID Card', 'Army ID Card')
INSERT INTO @mgr	VALUES	 ( 'Army ID Card', 'Army Widow Id C')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'As Per K. S. G.')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'As Per K.s.g')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'As Per Ksg')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti Approval', 'As Per Mr. Mahey')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'As Per Secretary')
INSERT INTO @mgr	VALUES	 ( 'Authority Letter', 'Attorised Lette')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Aunt Address Pr')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank A/c No')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Account Copy')
INSERT INTO @mgr	VALUES	 ( 'Allotment Letter', 'Bank Alotment Letter')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Book')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Copy')
INSERT INTO @mgr	VALUES	 ( 'Bank ID Card', 'Bank I Card')
INSERT INTO @mgr	VALUES	 ( 'Bank ID Card', 'Bank ID')
INSERT INTO @mgr	VALUES	 ( 'Bank ID Card', 'Bank Id Card')
INSERT INTO @mgr	VALUES	 ( 'Bank Letter', 'Bank Letter')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Papers')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Pass Bk')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Pass Bk.')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Pass Book')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Pass Book,')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Pass-Book')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Passbook')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Passbook /')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Passbook C')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank PassBook(R')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Passs Book')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Quarter Al')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Statemant')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Statement')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Statement.')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'BankPassBook')
INSERT INTO @mgr	VALUES	 ( 'Bar Association ID', 'Bar Assocation ')
INSERT INTO @mgr	VALUES	 ( 'BPL Card', 'BelowPovertylin')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Bill of electri')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Birla Ins ID')
INSERT INTO @mgr	VALUES	 ( 'Birth Certificate', 'Birth Cert')
INSERT INTO @mgr	VALUES	 ( 'Birth Certificate', 'Birth Certifica')
INSERT INTO @mgr	VALUES	 ( 'Birth Certificate', 'Birthcertif')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bnk Statemnt&agreeme')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Board Certifica')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'BOM Saving Acco')
INSERT INTO @mgr	VALUES	 ( 'BPL Card', 'BPL Card')
INSERT INTO @mgr	VALUES	 ( 'Brother''s Add Proof', 'Brothers Ration Card')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'BSNL Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'BSNL Electric b')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'BSNL Id Card')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'BSNL Statement')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Approval', 'Caretaker  Agreement')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Approval', 'Caretaker Agreement')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Approval', 'Caretaker Certi')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Approval', 'Caretaker''s let')
INSERT INTO @mgr	VALUES	 ( 'Caste Certificate', 'Caste Certifica')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Central Railway')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Central Railway Id')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Certicate by G0')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Govt. Dept. ID')
INSERT INTO @mgr	VALUES	 ( 'Certificate', 'Certificate')
INSERT INTO @mgr	VALUES	 ( 'Certificate', 'Certificate fro')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'CERTIFIED BANK ')
INSERT INTO @mgr	VALUES	 ( 'Name Change Cert', 'Change of name ')
INSERT INTO @mgr	VALUES	 ( 'Citizenship Card', 'Citizen Card')
INSERT INTO @mgr	VALUES	 ( 'Citizenship Card', 'Citizenship Cer')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Allotment Letter')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Resi Proof(elec)')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'Collage I D')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College I.D')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College I.D. ')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College id card')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College Id. Car')
INSERT INTO @mgr	VALUES	 ( 'College Leaving Cert', 'College Leaving')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'CollegeID.Elect')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'Company Certifi')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Company ID')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'Company Letter')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'Cooking Gas Pap')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'CookingGas Rece')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Copy of Agreeme')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Copy Of Agreement')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Copy of Sale Ag')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'Corporator Lett')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Corporetor ID L')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'Council Certifi')
INSERT INTO @mgr	VALUES	 ( 'Childs Address Proof', 'Daughter''s Passport')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Decl Form')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept Letter', 'Defence Force Letter')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept Letter', 'Defence Letter')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Defence Pension Card')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept Letter', 'Defence Qtr Agmnt.')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept Letter', 'Defence Qtr. Agmnt.')
INSERT INTO @mgr	VALUES	 ( 'Dependent ID card ', 'Dependent card ')
INSERT INTO @mgr	VALUES	 ( 'Dependent ID card ', 'Dependent I Car')
INSERT INTO @mgr	VALUES	 ( 'Dependent ID card ', 'Dependent Id Ca')
INSERT INTO @mgr	VALUES	 ( 'Dependent ID card ', 'Dependent Ident')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Diving Licence')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Diving license')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Pan card/ Aadha')
INSERT INTO @mgr	VALUES	 ( 'Doctor ID', 'Doctor''s Id Proof')
INSERT INTO @mgr	VALUES	 ( 'Domicile Certificate', 'Domicile Certif')
INSERT INTO @mgr	VALUES	 ( 'Domicile Certificate', 'Domicle Certifi')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'draiwing licenc')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Dreiving licenc')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Get Address Pro')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drive Licence,letter')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driver Licence')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driver''s Licenc')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driver''s Licens')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driver''s License')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drivers licenc')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drivers Licence')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drivers License')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Get Address Proof')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Get Details')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Pending')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licence')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving License')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Liecenc')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Lience')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'DRIVING LINCENC')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drivng License')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drivrs Licence')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Pending Address')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drv Lsc+PAN Car')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Proof Required')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'required')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Eectricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elec Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elec Bill+Mtr S')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elec Bill/Marks')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elec. Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elecric Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elecricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Elecricty Bill ')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'ELECT BILL')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electic Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electicity Bill')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Election List')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bil')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bill &')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bill + Pan')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bill C')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bill o')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electric Bill+ ')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electrical Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'ElectricBill,Ba')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricbill/ Ration')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electrici Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electriciry Bil')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricity Bil')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'ElectricityBill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electrict Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electrictcity B')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricty Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricy Bill ')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Eletricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employed''s ID')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employee Id')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employee ID Car')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employee IDcard')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employee PPF Ca')
INSERT INTO @mgr	VALUES	 ( 'Employment Letter', 'Employers Lette')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employment Card')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Employment ID')
INSERT INTO @mgr	VALUES	 ( 'Employment Letter', 'Employment Lett')
INSERT INTO @mgr	VALUES	 ( 'Endosement Form', 'Endosement Form')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'Entrance Card C')
INSERT INTO @mgr	VALUES	 ( 'ESIC Card', 'ESIC Card')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'To get present ')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Will Submit')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Required-ksg')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Hatpiplia RSSB ')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'In charge lette')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Incharge Approv')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Incharge Letter')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'K S G Approval')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'K. S. G.')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'K.s.g.')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'K.s.g. Apprd')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Ksg Approved')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Ksg-proof Not Needed')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Ksg: Proof Not Reqd.')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Letter from Are')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Letter, D.N.Mis')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'No Proof As Per Ksg')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'No Proof Reqd.:')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'No Proof Requir')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Req. K. S. G.')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Reqd K. S. G.')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Reqd- Ksg')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Reqd-ksg')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Required -ksg')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Required- Ksg')
INSERT INTO @mgr	VALUES	 ( 'Area Sec. Approval', 'Not Required-ks')
INSERT INTO @mgr	VALUES	 ( 'Exam Certifcate', 'Exam Cert')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Flat Aggrement')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Flat Aggrement Copy')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Flat Agreement ')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Flat Agreement L & L')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Flat Registration')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'Gas Bill')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'Gas Connection')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'Gas Registratio')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'Gas Statement')
INSERT INTO @mgr	VALUES	 ( 'Family ID Card', 'Family Card ')
INSERT INTO @mgr	VALUES	 ( 'Family ID Card', 'Family ID Card')
INSERT INTO @mgr	VALUES	 ( 'Bond', 'Government Bond')
INSERT INTO @mgr	VALUES	 ( 'Family ID Card', 'Government Fami')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Government I.D.')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Government Id Card')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Government Proo')
INSERT INTO @mgr	VALUES	 ( 'Gazette', 'Govt Of Maha Gazette')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Govt Railway Id')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Govt. ID')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Govt. Identity ')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Govt. of India ')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Govt.Residence ')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat ID', 'Gram Panchayat Card')
INSERT INTO @mgr	VALUES	 ( 'HSC Marksheet', 'H.S.C Marksheet')
INSERT INTO @mgr	VALUES	 ( 'ESIC Card', 'Health Card')
INSERT INTO @mgr	VALUES	 ( 'ESIC Card', 'Health Insuranc')
INSERT INTO @mgr	VALUES	 ( 'HSC Marksheet', 'High School Cer')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Hire Paper')
INSERT INTO @mgr	VALUES	 ( 'Hospital ID Card', 'Hospital Card')
INSERT INTO @mgr	VALUES	 ( 'Hostel ID Card', 'Hostel Id')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'House Agreement')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'House Agreement Copy')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'House Agreementpaper')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'House Agrmt. Paper')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'House Rent Agreement')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'House Share Certi')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'House Tax Copy')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'House Tax Recipt')
INSERT INTO @mgr	VALUES	 ( 'Family ID Card', 'Household Card ')
INSERT INTO @mgr	VALUES	 ( 'HSC Certificate', 'HSC Certificate')
INSERT INTO @mgr	VALUES	 ( 'HSC Marksheet', 'HSC Mark Sheet')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Hsg Soc. Bill')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husb. Drving License')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband Ration ')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband Voter I D')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband Voters ')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s copy ')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s Passp')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s Passport')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s Rationcard')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s U.I.D')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s UID')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s UID C')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husband''s Voter')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husbands Drivin')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husbands Passpo')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husbands Ration')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Husbands Ration Card')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'I D Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'I.U.D.L')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'ID Card')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'ID Card/Markshe')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'ID Proof - Exec')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'Id. Card (singapore)')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'Identity Card')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'Identity Card C')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'Identity Card f')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'IIT- Identity C')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept ID', 'Indian Navy ID')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Indian Railways')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept Letter', 'INS Letter')
INSERT INTO @mgr	VALUES	 ( 'Appointment Letter', 'Job Appointment')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Job Card')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Letter Frm Secr')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Letter from Sec')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'RSSB Letter ')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Satsang ID Card')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Secretary Approval')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'secretary certi')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Secretary Lette')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Secretary''s Let')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Seva letter')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Sevadar Id Card')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Sewa Card')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Sewadar I-D')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Sewadar ID Card')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Sewadar Letter')
INSERT INTO @mgr	VALUES	 ( 'Muncipal Dept Letter', 'K.M.C. Muncipal')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'K.s.g.apprvd,votrcrd')
INSERT INTO @mgr	VALUES	 ( 'Approved by HOD', 'Kewal Dogra Gurantee')
INSERT INTO @mgr	VALUES	 ( 'Farmers ID', 'Kisan Kitab')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'L & L Agreement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'L & L Agreement/ Pan')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'L& L Agrment/ration')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'L.i.c Policy')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'L.I.C receipt')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'L.I.C. Policy')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'L.i.c. Receipt')
INSERT INTO @mgr	VALUES	 ( 'Land record', 'Land record')
INSERT INTO @mgr	VALUES	 ( 'Landlord''s Proof', 'Landlord Electr')
INSERT INTO @mgr	VALUES	 ( 'Landlord''s Proof', 'Landlord''S Elec')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Learner Driving')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Learner''s Licen')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Learners Licenc')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Lease Agreement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & Li Agreement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & Lic.age')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & Licence Agmt')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & Licence Agre')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & Licence Copy')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & License')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & License Agmt')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & License Copy')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave & Licnc Agrmnt')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave &lic.agreement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave Agreement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave Licence Agreem')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave License A')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Leave& Lic.agre')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Letter', 'Letter from car')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti Approval', 'Sewa samiti end')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti Approval', 'Sewa Samiti Let')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan + Bank Pass')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Letter', 'Letter Of Incha')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan Card & Bank')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Letter Of Posse')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Letter Sec. Suw')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Soceity Letter')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'PAN Card+Pass B')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'PAN Card/BankPa')
INSERT INTO @mgr	VALUES	 ( 'Library Card', 'Library Card')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'LIC Document')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'LIC Policy')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'LIC policy prem')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'LIC Premium Rec')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'LIC Receipt')
INSERT INTO @mgr	VALUES	 ( 'LIC Policy', 'LIC Receipt, El')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Licence')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Licence + Pan C')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Licence card')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'License')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Light  Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Light Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Light Bill/pan Card')
INSERT INTO @mgr	VALUES	 ( 'Caretaker Letter', 'Lttr from Care ')
INSERT INTO @mgr	VALUES	 ( 'Cooking Gas Paper', 'Mahanagar Gas Bill')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Maintainance Bill')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Maintainence Receipt')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Maintenance Copy')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Mark sheeet(10t')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Mark Sheet')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Mark Sheet and ')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet & Let')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet + App')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet Copy')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet ID')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet(B S E')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet, Driv')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'Marksheet/ Pass')
INSERT INTO @mgr	VALUES	 ( 'Marriage Certificate', 'Marriage Certic')
INSERT INTO @mgr	VALUES	 ( 'Marriage Certificate', 'Marriage Certif')
INSERT INTO @mgr	VALUES	 ( 'Marriage Certificate', 'Marriage Certificate')
INSERT INTO @mgr	VALUES	 ( 'Marriage Certificate', 'Marriage Proof')
INSERT INTO @mgr	VALUES	 ( 'Medical Council ID', 'Medical Council Id')
INSERT INTO @mgr	VALUES	 ( 'Membership Card', 'Membership card')
INSERT INTO @mgr	VALUES	 ( 'Medical Council ID', 'MH State Pharma')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept ID', 'Military ID')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept ID', 'Military ID Car')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept ID', 'Ministry of Def')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Mobile Bill')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Pan Card/PassBo')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'PanCard+Bank Pa')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'Office Letter')
INSERT INTO @mgr	VALUES	 ( 'Police ID', 'MP Police ID Ca')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'MTNL bILL')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Mtnl Phone Bill')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'Office Letter Head')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Municipal Card')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'salary slip ')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Municipal Ident')
INSERT INTO @mgr	VALUES	 ( 'Company Letter/Cert', 'service certifi')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Municipal offic')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'municipal Tax')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'Municipal Tax R')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'Municipal-tax Recpt')
INSERT INTO @mgr	VALUES	 ( 'Relatives DrivingLic', 'Driving L (Hus)')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'DL+BNK PBook+El')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Municiplity ID ')
INSERT INTO @mgr	VALUES	 ( 'Defense Dept Letter', 'N O C - Indian Navy')
INSERT INTO @mgr	VALUES	 ( 'Nagar Sewak I D', 'Nagar Sewak I D')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drive Lic+Elec ')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Drv Lic + Elect')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'PAN Card & Driv')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Name Affidavit')
INSERT INTO @mgr	VALUES	 ( 'Naval Certificate', 'Naval Certificate')
INSERT INTO @mgr	VALUES	 ( 'Naval ID Card', 'Naval I Card')
INSERT INTO @mgr	VALUES	 ( 'Naval ID Card', 'Naval ID Card')
INSERT INTO @mgr	VALUES	 ( 'Naval Certificate', 'Navy Certificat')
INSERT INTO @mgr	VALUES	 ( 'Naval ID Card', 'Navy Id,  Elect.bill')
INSERT INTO @mgr	VALUES	 ( 'Naval ID Card', 'Navy ID.')
INSERT INTO @mgr	VALUES	 ( 'Naval Certificate', 'Navy Noc, Elect.bill')
INSERT INTO @mgr	VALUES	 ( 'Naval Certificate', 'Navy Ration Car')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Pan Card, Learn')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'New Electric Bill')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Lic., Ration')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Lic+Tel')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Pan card & Elec')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Pan card+Electr')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'PAN Card, Elect')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'House Tax & Light Bi')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman I')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex-Serviceman C')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex-Serviceman I')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex-Servicemen C')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Retire Identity Card')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father Voter ID')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father''s Compan')
INSERT INTO @mgr	VALUES	 ( 'Notary Certificate', 'Notary')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Office I D card')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Office I.d')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Office Id')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Office Id Card')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father''s Employ')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father''s Passpo')
INSERT INTO @mgr	VALUES	 ( 'P G Agreement', 'P G AGREEMENT.')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'P.O pass book')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan (as Per Mahey)')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father''s Voter ')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'PAN Allotment l')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'PAN Card ')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father''s Voter''')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Father''s Voters')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Fathers Passport')
INSERT INTO @mgr	VALUES	 ( 'Father''s Add Proof', 'Fathers Voter C')
INSERT INTO @mgr	VALUES	 ( 'Gazette', 'Gazette, Tele. ')
INSERT INTO @mgr	VALUES	 ( 'Govt Dept Letter', 'Letter of India')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept Cert', 'Education Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Panchayat Cert')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Panchayat Certi')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Pan Card/Tenant')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'PAN+EL BILL+REN')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'PAN+Elec Bill')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pancard')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'pancard & renta')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'PANCHYAT CERTIF')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Parshad''s Certi')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Sarpanch Certif')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Tehsil Certific')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Village Panchay')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Gram Panchayat ')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat ID', 'Panchayat ID')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat ID', 'Panchayat ID Ca')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Gram PanchayatS')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Gram Panchyat C')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Parichay Patra')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Gram Panchyat F')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Pass Bk+Drv Lic')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Pass Bk, Sr Citizen')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Pass Book')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Passbook')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Passbook & Panc')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Passbook(BOB)')
INSERT INTO @mgr	VALUES	 ( 'Passport', 'Passport')
INSERT INTO @mgr	VALUES	 ( 'Passport', 'Passport & Rati')
INSERT INTO @mgr	VALUES	 ( 'Passport', 'Passport + Ration')
INSERT INTO @mgr	VALUES	 ( 'Passport', 'Passport,tele. Bill')
INSERT INTO @mgr	VALUES	 ( 'Voucher', 'Payment Voucher')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pen Card')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Gram Raksha Sam')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Grampanchayat L')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pension Card')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pension Proof')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pensioner Card')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pensioner''s Card')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pensioner''s I C')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pensioner''s ID ')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pensioner''s ID.')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pensior''s Id Card')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'Permanent Resi. Card')
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'PF Id Card')
INSERT INTO @mgr	VALUES	 ( 'Medical Council ID', 'Pharmacist ID')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Phone Bill')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Phone Bill&photoid')
INSERT INTO @mgr	VALUES	 ( 'PIO Card', 'PO card/ Pan ca')
INSERT INTO @mgr	VALUES	 ( 'Police Letter', 'Police Letter')
INSERT INTO @mgr	VALUES	 ( 'Possession Letter', 'Possession Lett')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Post office pas')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Post office Sav')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Praman letter')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Praman Patra')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Progress Report')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Proof of Reside')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Letter frm Panc')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Property Agreement')
INSERT INTO @mgr	VALUES	 ( 'Property Card', 'Property index ')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'Property Tax')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'Property Tax Re')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'letter from Gra')
INSERT INTO @mgr	VALUES	 ( 'Allotment Letter', 'Qtr. Allotment')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Rahivasi Patra')
INSERT INTO @mgr	VALUES	 ( 'Family ID Card', 'Railway Family ')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Railway I D')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Railway I D Car')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Railway ID')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Railway ID Card')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'RAILWAYS FLT/DR')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Railways I D Ca')
INSERT INTO @mgr	VALUES	 ( 'Ration Card', 'Ration & Pan')
INSERT INTO @mgr	VALUES	 ( 'Ration Card', 'Ration Card')
INSERT INTO @mgr	VALUES	 ( 'Ration Card', 'Ration Card, Bank St')
INSERT INTO @mgr	VALUES	 ( 'Ration Card', 'Ration, Transfer Let')
INSERT INTO @mgr	VALUES	 ( 'Voucher', 'Rationcard Lic Certi')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Registration')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Registration Doc')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Registry')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Registry Certif')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Registry Paper')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Rel Electric Bi')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Rent Agreeement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Rent Agreement')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Rent Lease Lice')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Rent Receipt')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Rent Reciept')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Letter from Pan')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Res.Pro.Certifi')
INSERT INTO @mgr	VALUES	 ( 'Residence Permit', 'Resi Permit')
INSERT INTO @mgr	VALUES	 ( 'Residence Proof', 'Resi. Certifica')
INSERT INTO @mgr	VALUES	 ( 'Residence Proof', 'Residence certi')
INSERT INTO @mgr	VALUES	 ( 'Residence Proof', 'Residence Navy ')
INSERT INTO @mgr	VALUES	 ( 'Residence Proof', 'Residence Proof')
INSERT INTO @mgr	VALUES	 ( 'Residence Permit', 'Residence Visa')
INSERT INTO @mgr	VALUES	 ( 'Resident Card', 'Resident Card')
INSERT INTO @mgr	VALUES	 ( 'Resident Card', 'Resident Certif')
INSERT INTO @mgr	VALUES	 ( 'Resident Card', 'Resident ID')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Residential Aff')
INSERT INTO @mgr	VALUES	 ( 'Residence Proof', 'Residential Pro')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Letter-GramPanc')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Panchayal & Sec')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'S.c. Id.,ration Card')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Panchayat decla')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Sale Agreement')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Sale Agreement Copy')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Sale Deed')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Sales Agreement')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Ltr', 'Panchayat lette')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Hb.passport, Wed Crd')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Saving Bank Acc')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Saving Bank Pas')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'SBI Address Pro')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'SBI Passbook')
INSERT INTO @mgr	VALUES	 ( 'Mother''s Add Proof', 'Mom''s Voter Car')
INSERT INTO @mgr	VALUES	 ( 'Mother''s Add Proof', 'Mother''s Voter ')
INSERT INTO @mgr	VALUES	 ( 'Mother''s Add Proof', 'Mothers U.I.D/s')
INSERT INTO @mgr	VALUES	 ( 'School ID Card', 'School I Card')
INSERT INTO @mgr	VALUES	 ( 'School ID Card', 'School I D Card')
INSERT INTO @mgr	VALUES	 ( 'School ID Card', 'School I.D Card')
INSERT INTO @mgr	VALUES	 ( 'School ID Card', 'School ID')
INSERT INTO @mgr	VALUES	 ( 'School ID Card', 'School Identity')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Durgapur Munici')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Muncipality Cer')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'School Markshee')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'School Passing ')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'School Report B')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Scty Maint Bill')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipal Corp.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipal Lette')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Ce')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality le')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Secy. Letter')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'Self Applicatio')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'self declaratio')
INSERT INTO @mgr	VALUES	 ( 'Affidavit', 'self filled for')
INSERT INTO @mgr	VALUES	 ( 'Senior Citizen Card', 'Senior Citizen ')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Nagarpalika let')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Service Id')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Service Id Card')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Service Identit')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Nagpur Corporat')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Ujjain Municipa')
INSERT INTO @mgr	VALUES	 ( 'Nagar Sewak Cert', 'Nagar SewakCert')
INSERT INTO @mgr	VALUES	 ( 'Citizenship Card', 'Nepal Citizen I')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Psprt& Hsbnd Vo')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Uncle''s Ration Card')
INSERT INTO @mgr	VALUES	 ( 'Residence Cert', 'NivasPramanPtra')
INSERT INTO @mgr	VALUES	 ( 'Residence Cert', 'Niwasi Praman P')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Shares Certific')
INSERT INTO @mgr	VALUES	 ( 'Shop Regn.cert.', 'Shop Establishm')
INSERT INTO @mgr	VALUES	 ( 'Shop Regn.cert.', 'Shop Regn.cert.')
INSERT INTO @mgr	VALUES	 ( 'Letter', 'Signed letter')
INSERT INTO @mgr	VALUES	 ( 'Letter', 'signed note att')
INSERT INTO @mgr	VALUES	 ( 'Letter', 'signed paper pr')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'Leaving Certifi')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Soc. Bill, Ration')
INSERT INTO @mgr	VALUES	 ( 'Social Security Card', 'Social Security Card')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Society Allotme')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Society Bill')
INSERT INTO @mgr	VALUES	 ( 'Society Certificate', 'Society Certificate')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Society Letter')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Society Maint. Bill')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Society Mntnce Bill')
INSERT INTO @mgr	VALUES	 ( 'Society Letter', 'Society N.O.C.')
INSERT INTO @mgr	VALUES	 ( 'Childs Address Proof', 'Son''s House Agr')
INSERT INTO @mgr	VALUES	 ( 'Childs Address Proof', 'Son''s Rashan Card')
INSERT INTO @mgr	VALUES	 ( 'Childs Address Proof', 'Son''s VoterCard')
INSERT INTO @mgr	VALUES	 ( 'Childs Address Proof', 'Son-in-l  Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Drivi Li')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Drv.Lic.')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Employer')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Ration C')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse UID')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Voter Ca')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Voters C')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse Votor ID')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse''s Adhaar')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse''s Pan Ca')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse''s Pass B')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouse''s Voter ')
INSERT INTO @mgr	VALUES	 ( 'Spouse Address Proof', 'Spouses Voter C')
INSERT INTO @mgr	VALUES	 ( 'Senior Citizen Card', 'Sr. Citizen ID')
INSERT INTO @mgr	VALUES	 ( 'Senior Citizen Card', 'Sr. Citizen Id.')
INSERT INTO @mgr	VALUES	 ( 'Senior Citizen Card', 'Sr. Citizend Id')
INSERT INTO @mgr	VALUES	 ( 'Senior Citizen Card', 'Sr.citizen Card')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'SSC Marksheet')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'State Bank Pass')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'Student I Card')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'Student ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'Student ID Card')
INSERT INTO @mgr	VALUES	 ( 'Application', 'Survey Applicat')
INSERT INTO @mgr	VALUES	 ( 'Property Tax Bill', 'Tax receipt')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Soc. Bill, Voter''s')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat ID', 'Tehsil ID Proof')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Tel. Bill')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Telephone')
INSERT INTO @mgr	VALUES	 ( 'Telephone Bill', 'Telephone Bill')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Tenancy Agreeme')
INSERT INTO @mgr	VALUES	 ( 'L & L Agreement', 'Tent Agreemant')
INSERT INTO @mgr	VALUES	 ( 'SSC Leaving Cert', 'School Certific')
INSERT INTO @mgr	VALUES	 ( 'Transfer Certificate', 'Transfer certif')
INSERT INTO @mgr	VALUES	 ( 'Transfer Certificate', 'Transfer Order')
INSERT INTO @mgr	VALUES	 ( 'Bank ID Card', 'Travellers Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U . I. D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U I D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U I D Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U ID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U Id Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U ID Card  (AAD')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U,I,D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U. I. D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U. I. D.')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U. I. D. Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I. D. Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I.D')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I.D + Electri')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I.D CARD')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I.D.')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I.D. CARD')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.I.D.card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.Id')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.ID card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.ID.')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'U.Id. Card')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'UCO Bank Docume')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UDI')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UIA Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UIA Card (AADHA')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID - Aadhar Ca')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID - Adhar Car')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID Aadhar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID Acknowledge')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID acknowlegem')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID Adhar Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID Card AADHAR')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID Receipt')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UID,Electric Bi')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'SSC Leaving Cert', 'School Certificate')
INSERT INTO @mgr	VALUES	 ( 'SSC Leaving Cert', 'School Cirtific')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Unique ID')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Unique ID Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'UniquE Identifi')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Unique Identity')
INSERT INTO @mgr	VALUES	 ( 'Vehicle RC book', 'Vehicle RC book')
INSERT INTO @mgr	VALUES	 ( 'SSC Leaving Cert', 'School Leaving ')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voter Card Slip')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voter''s & Pan C')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voter''s Card & ')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'VoterID+Electri')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voters Card (So')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voters Card of ')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voters, Agreement')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Voters/electricity')
INSERT INTO @mgr	VALUES	 ( 'Voters Card', 'Votor Slip')
INSERT INTO @mgr	VALUES	 ( 'Water Bill', 'Water Bill ')
INSERT INTO @mgr	VALUES	 ( 'Wedding Card', 'Wedding Card')
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Western railway')
INSERT INTO @mgr	VALUES	 ( 'SSC Leaving Cert', 'School Leaving/')
INSERT INTO @mgr	VALUES	 ( 'Wireman''s Cert', 'Wireman''s Certi')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Work ID Card')
INSERT INTO @mgr	VALUES	 ( 'Aadhar U.I.D.', 'Aadhar U.I.D., Pan Card')
INSERT INTO @mgr	VALUES	 ( 'Agreement Copy', 'Agreement Copy, Electricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Bank Pass Book, Pan Card')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licence, Bank Pass Book, Electricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licence, Electricity Bill')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licence, Pan Card')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licence, Ration Card')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licence, Telephone Bill')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricity Bill, Pan Card')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electricity Bill, Property Tax Bill')
INSERT INTO @mgr	VALUES	 ( 'Gazette', 'Gazette, Telephone Bill')
INSERT INTO @mgr	VALUES	 ( 'Passport', 'Passport, Husbands Address Proof')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Society Bill, Ration Card')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Society Bill, Voters Card')


INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Brother''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Relative''s Add Proof')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Soceity Bill')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Applied Voters Card', 'Appln Voters Card')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti-Approval', 'Sewa Samiti approval')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Govt Dept Letter', 'Govt. Dept. Letter')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Nagar Sewak Cert', 'Nagar Sewak Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Nagar Sewak Cert', 'Nagar Sewak Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Mother''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'P G Agreement', 'P G AGREEMENT.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Company ID')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Address Proof')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Name Change Cert', 'Name Change Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Company ID')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti-Approval', 'Sewa Samiti approval')
INSERT INTO @mgr	VALUES	 ( 'Wireman''s Cert', 'Wireman''s Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Endorsement Form', 'Endorsement Form')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Pass Book copy')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', ' Bank passbook')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'bank record')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electircity bil')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Learner Licence')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'Bank A/C.')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'Bank document')
INSERT INTO @mgr	VALUES	 ( 'Residence Cert', 'Residence Cert.')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'Bankstatement/E')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan Card/D Lice')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Panchayat Lette')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'BankPpassbook')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pension Slip')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'License Electri')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan Card & Driv')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan card, Drivi')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'School Report')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Secretary appro');


INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Brother''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Relative''s Add Proof')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Society Bill', 'Soceity Bill')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Applied Voters Card', 'Appln Voters Card')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti-Approval', 'Sewa Samiti approval')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Govt Dept Letter', 'Govt. Dept. Letter')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Nagar Sewak Cert', 'Nagar Sewak Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Nagar Sewak Cert', 'Nagar Sewak Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Mother''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'P G Agreement', 'P G AGREEMENT.')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Company ID')
INSERT INTO @mgr	VALUES	 ( 'Add. Proof Pending', 'Address Proof')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Name Change Cert', 'Name Change Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Child''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Co. Allotment Letter', 'Co. Letter/Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'ExServiceman ID Card', 'Ex Serviceman ID')
INSERT INTO @mgr	VALUES	 ( 'Municipality Cert', 'Municipality Cert.')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'Relatives Add Proof', 'Father''s Add. Proof')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College ID')
INSERT INTO @mgr	VALUES	 ( 'School Leaving Cert', 'School Leaving Cert.')
INSERT INTO @mgr	VALUES	 ( 'Company ID Card', 'Company ID')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panchayat Cert.')
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti-Approval', 'Sewa Samiti approval')
INSERT INTO @mgr	VALUES	 ( 'Wireman''s Cert', 'Wireman''s Cert.')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Letter')
INSERT INTO @mgr	VALUES	 ( 'Endorsement Form', 'Endorsement Form')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'Pass Book copy')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', ' Bank passbook')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'bank record')
INSERT INTO @mgr	VALUES	 ( 'Electricity Bill', 'Electircity bil')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Learner Licence')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'Bank A/C.')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'Bank document')
INSERT INTO @mgr	VALUES	 ( 'Residence Cert', 'Residence Cert.')
INSERT INTO @mgr	VALUES	 ( 'Bank Certificate', 'Bankstatement/E')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan Card/D Lice')
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Panchayat Lette')
INSERT INTO @mgr	VALUES	 ( 'Bank Pass Book', 'BankPpassbook')
INSERT INTO @mgr	VALUES	 ( 'Pensioner''s ID Card', 'Pension Slip')
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'License Electri')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan Card & Driv')
INSERT INTO @mgr	VALUES	 ( 'Pan Card', 'Pan card, Drivi')
INSERT INTO @mgr	VALUES	 ( 'SSC Marksheet', 'School Report')
INSERT INTO @mgr	VALUES	 ( 'Secretary Approval', 'Secretary appro');
INSERT INTO @mgr	VALUES	 ( 'Sewa Samiti-Approval', 'Sewa Samiti approval')
INSERT INTO @mgr	VALUES	 ( 'Endosement Form', 'Endorsement Form');
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept Cert', 'Govt. Dept. Cert.');
INSERT INTO @mgr	VALUES	 ( 'Gram Panchayat Cert', 'Gram Panch. Let');
INSERT INTO @mgr	VALUES	 ( 'College ID Card', 'College Identit');
INSERT INTO @mgr	VALUES	 ( 'Advocate ID', 'Advovate ID Car');
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Lic.(Sp');
INSERT INTO @mgr	VALUES	 ( 'Marriage Certificate', 'Marriage Card');
INSERT INTO @mgr	VALUES	 ( 'Bank ID Card', 'bank details');
INSERT INTO @mgr	VALUES	 ( 'Driving Licence', 'Driving Licenec');
INSERT INTO @mgr	VALUES	 ( 'ID Card', 'self declared');
INSERT INTO @mgr	VALUES	 ( 'Medical Council ID', 'Medical ID ');
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Goverment ID');
INSERT INTO @mgr	VALUES	 ( 'Govt. Dept ID', 'Government ID');



SELECT *
FROM	@mgr	m
	LEFT JOIN other_address_proofs oap
		ON m.new_val = oap.address_proof_nm
WHERE	oap.address_proof_nm IS NULL

UPDATE sd
	SET other_address_proof_id = oap.address_proof_id
FROM sewadars_details sd
	JOIN other_address_proofs oap
		ON sd.other_address_proof = oap.address_proof_nm

UPDATE sd
	SET other_address_proof_id = oap.address_proof_id
FROM sewadars_details sd
	JOIN @mgr	m
		ON	(	m.old_val	=	sd.other_address_proof	)
	JOIN other_address_proofs oap
		ON m.new_val = oap.address_proof_nm
WHERE	sd.other_address_proof_id IS NULL

SELECT	*
FROM	sewadars_details	d
	LEFT JOIN	other_address_proofs	a
		ON	(	d.other_address_proof_id	=	a.address_proof_id	)
WHERE	a.address_proof_id	IS NULL
AND		d.other_address_proof	IS NOT NULL;
	
IF (@@ROWCOUNT > 0)
BEGIN
	RAISERROR ('There are invalid Other Address Proofs for the Sewadars, which need to be corrected', 16, 1);
	RETURN
END


ALTER TABLE sewadars_details
	DROP	CONSTRAINT	SewadarsDetails_CK_AddressProof_OtherAddressProof
GO

ALTER TABLE adt_sewadars_details
	ADD	other_address_proof_id address_proof_id		NULL
-- Drop the column
ALTER TABLE adt_sewadars_details
	DROP COLUMN	other_address_proof
GO
ALTER TABLE sewadars_details
	DROP COLUMN	other_address_proof
GO

ALTER TABLE sewadars_details
	ADD	CONSTRAINT	SewadarsDetails_CK_AddressProof_OtherAddressProof
			CHECK	(	(	address_proof	IS NULL		AND	other_address_proof_id	IS NULL		)
					OR	(	address_proof	IS NOT NULL	AND	other_address_proof_id	IS NULL		)
					OR	(	address_proof	IS NULL		AND	other_address_proof_id	IS NOT NULL	)
					)
GO