
/* ==================================================================================
    	Source File		:	setup_thailand_components.sql
	Author(s)		:	Auto-generated(Anil)	
	Started On		:	12-10-2014
	Module ID		:	CDB
	Last updated		:	12-10-2014
	==================================================================================
		Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of Thailand are set-up
	==================================================================================
		Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'Thailand';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('Country Thailand not found', 16, 1);
	RETURN;
END

UPDATE	countries
	SET	level_1_address_component	=	'Province',
		level_2_address_component	=	'District',
		level_3_address_component	=	NULL
WHERE	country_id	=	@country_id;

-- ======================================================================

SET NOCOUNT ON
DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_1_cd varchar (5), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_cd, level_2_cd), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Akat Amnuai',	'SN',	'AA');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Amnat Charoen',	'AC',	'AM');
INSERT INTO @tbl VALUES ('Samut Songkhram'            ,	     'Amphawa',	'SM',	'AM');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Ang Thong',	'AT',	'AN');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Ao Luek',	'KR',	'AL');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Aranyaprathet',	'SK',	'AR');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'At Samat',	'RE',	'AS');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Bacho',	'NW',	'BA');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Bamnet Narong',	'CY',	'BN');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Ban Bueng',	'CB',	'BU');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Ban Chang',	'RY',	'BC');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Ban Dan',	'BR',	'DA');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Ban Dan Lan Hoi',	'SO',	'BD');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Ban Dung',	'UN',	'BD');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Ban Fang',	'KK',	'FA');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Bang Ban',	'PA',	'BB');
INSERT INTO @tbl VALUES ('Samut Prakan'            ,	     'Bang Bo',	'SP',	'BB');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Bon',	'BM',	'BO');
INSERT INTO @tbl VALUES ('Nonthaburi'            ,	     'Bang Bua Thong',	'NO',	'BB');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Bang Kaeo',	'PL',	'BK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Kapi',	'BM',	'KP');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Khae',	'BM',	'KA');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Bang Khan',	'NT',	'BK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Khen',	'BM',	'KE');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Bang Khla',	'CC',	'KH');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Kho Laem',	'BM',	'KL');
INSERT INTO @tbl VALUES ('Samut Songkhram'            ,	     'Bang Khonthi',	'SM',	'BK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Khun Thian',	'BM',	'KT');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Bang Klam',	'SG',	'BK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bangkok Noi',	'BM',	'BN');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bangkok Yai',	'BM',	'BY');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Bang Krathum',	'PS',	'BK');
INSERT INTO @tbl VALUES ('Nonthaburi'            ,	     'Bang Kruai',	'NO',	'BK');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Bang Lamung',	'CB',	'LA');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Bang Len',	'NP',	'BL');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Bang Mun Nak',	'PC',	'BM');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Na',	'BM',	'NA');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Bang Nam Priao',	'CC',	'NP');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Bang Pahan',	'PA',	'PA');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Bang Pa-in',	'PA',	'PI');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Bang Pakong',	'CC',	'PA');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Bang Phae',	'RT',	'BP');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Phlat',	'BM',	'PH');
INSERT INTO @tbl VALUES ('Samut Prakan'            ,	     'Bang Phli',	'SP',	'BP');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Bang Pla Ma',	'SH',	'BP');
INSERT INTO @tbl VALUES ('Sing Buri'            ,	     'Bang Rachan',	'SB',	'BR');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Rak',	'BM',	'RA');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Bang Rakam',	'PS',	'BR');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Bang Sai',	'PA',	'BS');
INSERT INTO @tbl VALUES ('Samut Prakan'            ,	     'Bang Sao Thong',	'SP',	'BS');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Bang Saphan',	'PK',	'BS');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Bang Saphan Noi',	'PK',	'BN');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bang Sue',	'BM',	'SU');
INSERT INTO @tbl VALUES ('Nonthaburi'            ,	     'Bang Yai',	'NO',	'BY');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Ban Haet',	'KK',	'HT');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Ban Hong',	'LN',	'BH');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Ban Kha',	'RT',	'BK');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Ban Khai',	'RY',	'BK');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Ban Khok',	'UD',	'BK');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Ban Khwao',	'CY',	'KH');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Ban Kruat',	'BR',	'KR');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Ban Laem',	'PE',	'LM');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Ban Lat',	'PE',	'LT');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Ban Luang',	'NA',	'BL');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Ban Lueam',	'NR',	'LU');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Ban Mai Chaiyaphot',	'BR',	'MC');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Ban Mi',	'LB',	'BM');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Ban Mo',	'SR',	'BM');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Ban Muang',	'SN',	'BM');
INSERT INTO @tbl VALUES ('Nakhon Nayok'            ,	     'Ban Na',	'NN',	'BN');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Ban Na Doem',	'ST',	'ND');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Bannang Sata',	'YL',	'BS');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Ban Na San',	'ST',	'NS');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Ban Phaeng',	'NF',	'BP');
INSERT INTO @tbl VALUES ('Samut Sakhon'            ,	     'Ban Phaeo',	'SS',	'BP');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Ban Phai',	'KK',	'PH');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Ban Pho',	'CC',	'PH');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Banphot Phisai',	'NS',	'BP');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Ban Phraek',	'PA',	'PK');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Ban Phue',	'UN',	'BP');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Ban Pong',	'RT',	'PO');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Ban Rai',	'UT',	'BR');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Ban Sang',	'PB',	'BS');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Ban Tak',	'TK',	'BT');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Ban Ta Khun',	'ST',	'TK');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Ban Thaen',	'CY',	'TH');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Ban Thi',	'LN',	'BT');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Benchalak',	'SI',	'BE');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Betong',	'YL',	'BE');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Bo Kluea',	'NA',	'BK');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Bo Phloi',	'KN',	'BP');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Borabue',	'MS',	'BO');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Bo Rai',	'TT',	'BR');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Bo Thong',	'CB',	'BO');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Buachet',	'SU',	'BU');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Bua Lai',	'NR',	'LA');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Bua Yai',	'NR',	'BY');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Bueng Bun',	'SI',	'BB');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Bueng Kan',	'BK',	'KA');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Bueng Khong Long',	'BK',	'KL');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Bueng Kum',	'BM',	'BK');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Bueng Na Rang',	'PC',	'BN');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Bueng Samakkhi',	'KP',	'BS');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Bueng Sam Phan',	'PH',	'BS');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Bung Khla',	'BK',	'KH');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Buntharik',	'UR',	'BU');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Buri Ram',	'BR',	'BR');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Cha-am',	'PE',	'CH');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Chachoengsao',	'CC',	'CH');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Chae Hom',	'LG',	'CH');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Chai Badan',	'LB',	'CB');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Chai Buri',	'ST',	'CB');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Chai Nat',	'CN',	'CH');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Chai Prakan',	'CM',	'CP');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Chai Wan',	'UN',	'CW');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Chaiya',	'ST',	'CH');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Chaiyaphum',	'CY',	'CP');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Chaiyo',	'AT',	'CH');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Chakkarat',	'NR',	'CH');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Chaloem Phra Kiat',	'BR',	'CP');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Chaloem Phra Kiat',	'NA',	'CP');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Chaloem Phra Kiat',	'NR',	'PK');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Chaloem Phra Kiat',	'NT',	'CP');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Chaloem Phra Kiat',	'SR',	'CP');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Chamni',	'BR',	'CH');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Chana',	'SG',	'CH');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Chanae',	'NW',	'CH');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Changhan',	'RE',	'CH');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Chang Klang',	'NT',	'CK');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Chanthaburi',	'CT',	'CH');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Chanuman',	'AC',	'CH');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Charoen Sin',	'SN',	'CS');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Chat Trakan',	'PS',	'CT');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Chatturat',	'CY',	'CT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Chatuchak',	'BM',	'CH');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Chaturaphak Phiman',	'RE',	'CP');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Cha-uat',	'NT',	'CU');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Chawang',	'NT',	'CH');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Chiang Dao',	'CM',	'CD');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Chiang Kham',	'PY',	'CK');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Chiang Khan',	'LE',	'CK');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Chiang Khong',	'CR',	'CK');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Chiang Khwan',	'RE',	'CK');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Chiang Klang',	'NA',	'CK');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Chiang Mai',	'CM',	'CM');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Chiang Muan',	'PY',	'CM');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Chiang Rai',	'CR',	'CR');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Chiang Saen',	'CR',	'CS');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Chiang Yuen',	'MS',	'CY');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Chian Yai',	'NT',	'CY');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Cho-airong',	'NW',	'CA');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Chok Chai',	'NR',	'CC');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Chom Bueng',	'RT',	'CB');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Chom Phra',	'SU',	'CP');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Chom Thong',	'BM',	'CT');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Chom Thong',	'CM',	'CT');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Chon Buri',	'CB',	'CH');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Chon Daen',	'PH',	'CD');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Chonnabot',	'KK',	'CH');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Chuen Chom',	'MS',	'CC');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Chulabhorn',	'NT',	'CB');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Chum Phae',	'KK',	'CP');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Chumphon',	'CP',	'CH');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Chumphon Buri',	'SU',	'CB');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Chum Phuang',	'NR',	'CP');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Chum Saeng',	'NS',	'CS');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Chum Ta Bong',	'NS',	'CT');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Chun',	'PY',	'CH');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Damnoen Saduak',	'RT',	'DS');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Dan Chang',	'SH',	'DA');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Dan Khun Thot',	'NR',	'DK');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Dan Makham Tia',	'KN',	'DM');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Dan Sai',	'LE',	'DS');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Den Chai',	'PR',	'DC');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Det Udom',	'UR',	'DU');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Din Daeng',	'BM',	'DI');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Doem Bang Nang Buat',	'SH',	'DB');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Doi Lo',	'CM',	'DL');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Doi Luang',	'CR',	'DO');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Doi Saket',	'CM',	'DS');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Doi Tao',	'CM',	'DT');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Dok Khamtai',	'PY',	'DK');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Don Chan',	'KL',	'DO');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Don Chedi',	'SH',	'DO');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Dong Charoen',	'PC',	'DC');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'Dong Luang',	'MD',	'DL');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Don Mot Daeng',	'UR',	'DM');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Don Mueang',	'BM',	'DO');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Don Phut',	'SR',	'DP');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Don Sak',	'ST',	'DS');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'Don Tan',	'MD',	'DT');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Don Tum',	'NP',	'DT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Dusit',	'BM',	'DU');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Erawan',	'LE',	'ER');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Fak Tha',	'UD',	'FT');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Fang',	'CM',	'FA');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Fao Rai',	'NH',	'FR');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Galyani Vadhana',	'CM',	'GV');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Hang Chat',	'LG',	'HC');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Hang Dong',	'CM',	'HA');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Hankha',	'CN',	'HA');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Hat Samran',	'TG',	'HS');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Hat Yai',	'SG',	'HY');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Hot',	'CM',	'HO');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Hua Hin',	'PK',	'HH');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Huai Khot',	'UT',	'HK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Huai Khwang',	'BM',	'HU');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Huai Krachao',	'KN',	'HK');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Huai Mek',	'KL',	'HM');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Huai Phueng',	'KL',	'HP');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Huai Rat',	'BR',	'HU');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Huai Thalaeng',	'NR',	'HT');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Huai Thap Than',	'SI',	'HT');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Huai Yot',	'TG',	'HY');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Hua Sai',	'NT',	'HS');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Hua Taphan',	'AC',	'HU');
INSERT INTO @tbl VALUES ('Sing Buri'            ,	     'In Buri',	'SB',	'IB');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Kabang',	'YL',	'KA');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Kabin Buri',	'PB',	'KB');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Kae Dam',	'MS',	'KD');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Kaeng Hang Maeo',	'CT',	'KA');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Kaeng Khoi',	'SR',	'KK');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Kaeng Khro',	'CY',	'KK');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Kaeng Krachan',	'PE',	'KK');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Kaeng Sanam Nang',	'NR',	'KN');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Kalasin',	'KL',	'KL');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Kamalasai',	'KL',	'KA');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Kamphaeng Phet',	'KP',	'KP');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Kamphaeng Saen',	'NP',	'KS');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Kanchanaburi',	'KN',	'KA');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Kanchanadit',	'ST',	'KA');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Kantang',	'TG',	'KA');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Kantharalak',	'SI',	'KK');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Kanthararom',	'SI',	'KM');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Kantharawichai',	'MS',	'KA');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Kao Liao',	'NS',	'KL');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Kap Choeng',	'SU',	'KC');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Kapho',	'PI',	'KA');
INSERT INTO @tbl VALUES ('Ranong'            ,	     'Kapoe',	'RN',	'KA');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Kapong',	'PG',	'KA');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Kaset Sombun',	'CY',	'KA');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Kaset Wisai',	'RE',	'KW');
INSERT INTO @tbl VALUES ('Phuket'            ,	     'Kathu',	'PU',	'KA');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Khaen Dong',	'BR',	'KD');
INSERT INTO @tbl VALUES ('Sing Buri'            ,	     'Khai Bang Rachan',	'SB',	'KB');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'Khamcha-i',	'MD',	'KH');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Kham Khuean Kaeo',	'YS',	'KK');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Kham Muang',	'KL',	'KM');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Kham Sakaesaeng',	'NR',	'KS');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Kham Ta Kla',	'SN',	'KT');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Kham Thale So',	'NR',	'KT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Khan Na Yao',	'BM',	'KY');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Khanom',	'NT',	'KH');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Khanu Woralaksaburi',	'KP',	'KW');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Khao Chaison',	'PL',	'KC');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Khao Chakan',	'SK',	'KC');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Khao Chamao',	'RY',	'KC');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Khao Khitchakut',	'CT',	'KK');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Khao Kho',	'PH',	'KK');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Khao Phanom',	'KR',	'KP');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Khao Saming',	'TT',	'KS');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Khao Suan Kwang',	'KK',	'KS');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Khao Wong',	'KL',	'KW');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Khao Yoi',	'PE',	'KY');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Khemarat',	'UR',	'KH');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Khian Sa',	'ST',	'KS');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Khiri Mat',	'SO',	'KM');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Khiri Rat Nikhom',	'ST',	'KR');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Khlong Hat',	'SK',	'KH');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Khlong Hoi Khong',	'SG',	'KH');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Khlong Khlung',	'KP',	'KK');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Khlong Khuean',	'CC',	'KK');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Khlong Lan',	'KP',	'KL');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Khlong Luang',	'PT',	'KL');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Khlong Sam Wa',	'BM',	'KW');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Khlong San',	'BM',	'KS');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Khlong Thom',	'KR',	'KT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Khlong Toei',	'BM',	'KH');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Khlong Yai',	'TT',	'KY');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Khlung',	'CT',	'KH');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Khok Charoen',	'LB',	'KC');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Khok Pho',	'PI',	'KP');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Khok Pho Chai',	'KK',	'KP');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Khok Samrong',	'LB',	'KS');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Khok Si Suphan',	'SN',	'KS');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Khok Sung',	'SK',	'KS');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Khon Buri',	'NR',	'KB');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Khong',	'NR',	'KH');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Khong Chai',	'KL',	'CH');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Khong Chiam',	'UR',	'KC');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Khon Kaen',	'KK',	'KK');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Khon San',	'CY',	'KS');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Khon Sawan',	'CY',	'KO');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Kho Wang',	'YS',	'KW');
INSERT INTO @tbl VALUES ('Satun'            ,	     'Khuan Don',	'SA',	'KD');
INSERT INTO @tbl VALUES ('Satun'            ,	     'Khuan Kalong',	'SA',	'KK');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Khuan Khanun',	'PL',	'KK');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Khuan Niang',	'SG',	'KN');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Khueang Nai',	'UR',	'KN');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Khukhan',	'SI',	'KU');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Khu Mueang',	'BR',	'KM');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Khun Han',	'SI',	'KH');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Khun Tan',	'CR',	'KH');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Khun Yuam',	'MH',	'KY');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Khura Buri',	'PG',	'KB');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Khwao Sinarin',	'SU',	'KS');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Klaeng',	'RY',	'KL');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Ko Chan',	'CB',	'KC');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Ko Chang',	'TT',	'KC');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Ko Kha',	'LG',	'KK');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Ko Kut',	'TT',	'KK');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Ko Lanta',	'KR',	'KL');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Kong Krailat',	'SO',	'KK');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Kong Ra',	'PL',	'KR');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Ko Pha-ngan',	'ST',	'KP');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Kosamphi Nakhon',	'KP',	'KN');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Ko Samui',	'ST',	'KO');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Ko Sichang',	'CB',	'KS');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Kosum Phisai',	'MS',	'KP');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Ko Yao',	'PG',	'KY');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Krabi',	'KR',	'KR');
INSERT INTO @tbl VALUES ('Ranong'            ,	     'Kra Buri',	'RN',	'KB');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Kranuan',	'KK',	'KR');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Krasae Sin',	'SG',	'KS');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Krasang',	'BR',	'KS');
INSERT INTO @tbl VALUES ('Samut Sakhon'            ,	     'Krathum Baen',	'SS',	'KB');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Krok Phra',	'NS',	'KP');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Krong Pinang',	'YL',	'KP');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Kuchinarai',	'KL',	'KU');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Kui Buri',	'PK',	'KB');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Ku Kaeo',	'UN',	'KK');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Kumphawapi',	'UN',	'KU');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Kusuman',	'SN',	'KU');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Kut Bak',	'SN',	'KB');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Kut Chap',	'UN',	'KC');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Kut Chum',	'YS',	'KC');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Kut Khaopun',	'UR',	'KK');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Kut Rang',	'MS',	'KR');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Laem Ngop',	'TT',	'LN');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Laem Sing',	'CT',	'LA');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Lahan Sai',	'BR',	'LS');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Lak Si',	'BM',	'LS');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Lamae',	'CP',	'LA');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Lamduan',	'SU',	'LA');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Lam Luk Ka',	'PT',	'LM');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Lampang',	'LG',	'LA');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Lamphun',	'LN',	'LA');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Lam Plai Mat',	'BR',	'LP');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Lam Sonthi',	'LB',	'LS');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Lam Thamenchai',	'NR',	'LT');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Lam Thap',	'KR',	'LT');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Lang Suan',	'CP',	'LS');
INSERT INTO @tbl VALUES ('Satun'            ,	     'La-ngu',	'SA',	'LA');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Lan Krabue',	'KP',	'LK');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Lan Sak',	'UT',	'LS');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Lan Saka',	'NT',	'LS');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Lao Khwan',	'KN',	'LK');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Lao Suea Kok',	'UR',	'LS');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Laplae',	'UD',	'LA');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Lat Bua Luang',	'PA',	'LB');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Lat Krabang',	'BM',	'LK');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Lat Lum Kaeo',	'PT',	'LT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Lat Phrao',	'BM',	'LP');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Lat Yao',	'NS',	'LY');
INSERT INTO @tbl VALUES ('Ranong'            ,	     'La-un',	'RN',	'LA');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Li',	'LN',	'LI');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Loei',	'LE',	'LO');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Loeng Nok Tha',	'YS',	'LN');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Lom Kao',	'PH',	'LK');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Lom Sak',	'PH',	'LS');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Long',	'PR',	'LO');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Lop Buri',	'LB',	'LB');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Lue Amnat',	'AC',	'LU');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Mae Ai',	'CM',	'MA');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Mae Chaem',	'CM',	'MM');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Mae Chai',	'PY',	'MC');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Mae Chan',	'CR',	'MC');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Mae Charim',	'NA',	'MC');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Mae Fa Luang',	'CR',	'MF');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Mae Hong Son',	'MH',	'MH');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Mae Lan',	'PI',	'ML');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Mae La Noi',	'MH',	'ML');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Mae Lao',	'CR',	'ML');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Mae Mo',	'LG',	'MM');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Mae On',	'CM',	'MO');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Mae Phrik',	'LG',	'MP');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Mae Poen',	'NS',	'MP');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Mae Ramat',	'TK',	'MR');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Mae Rim',	'CM',	'MR');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Mae Sai',	'CR',	'MS');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Mae Sariang',	'MH',	'MS');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Mae Sot',	'TK',	'MS');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Mae Suai',	'CR',	'MA');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Mae Taeng',	'CM',	'MT');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Mae Tha',	'LG',	'MT');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Mae Tha',	'LN',	'MT');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Mae Wang',	'CM',	'MW');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Mae Wong',	'NS',	'MW');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Maha Chana Chai',	'YS',	'MC');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Maha Rat',	'PA',	'MR');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Maha Sarakham',	'MS',	'MS');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Mai Kaen',	'PI',	'MK');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Makham',	'CT',	'MA');
INSERT INTO @tbl VALUES ('Satun'            ,	     'Manang',	'SA',	'MA');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Mancha Khiri',	'KK',	'MA');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Manorom',	'CN',	'MA');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Mayo',	'PI',	'MA');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Min Buri',	'BM',	'MI');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Moei Wadi',	'RE',	'MW');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Muak Lek',	'SR',	'ML');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Muang Sam Sip',	'UR',	'MS');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Mueang Chan',	'SI',	'MC');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Mueang Pan',	'LG',	'PA');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Mueang Phang Nga',	'PG',	'PH');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Mueang Suang',	'RE',	'MS');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Mueang Yang',	'NR',	'MY');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'Mukdahan',	'MD',	'MU');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Na Bon',	'NT',	'NB');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Na Chaluai',	'UR',	'NC');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Na Chueak',	'MS',	'NC');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Na Di',	'PB',	'ND');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Na Duang',	'LE',	'ND');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Na Dun',	'MS',	'ND');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Na Haeo',	'LE',	'NH');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Na Kae',	'NF',	'NK');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Nakhon Chai Si',	'NP',	'NC');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Nakhon Luang',	'PA',	'NL');
INSERT INTO @tbl VALUES ('Nakhon Nayok'            ,	     'Nakhon Nayok',	'NN',	'NN');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Nakhon Pathom',	'NP',	'NP');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Nakhon Phanom',	'NF',	'NP');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Nakhon Ratchasima',	'NR',	'NR');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Nakhon Sawan',	'NS',	'NS');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Nakhon Si Thammarat',	'NT',	'NS');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Nakhon Thai',	'PS',	'NT');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Na Khu',	'KL',	'NK');
INSERT INTO @tbl VALUES ('Nong Bua Lam Phu'            ,	     'Na Klang',	'NB',	'NK');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Nam Khun',	'UR',	'NK');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Nam Kliang',	'SI',	'NM');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Nam Nao',	'PH',	'NN');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Na Mom',	'SG',	'NM');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Na Mon',	'KL',	'NM');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Nam Pat',	'UD',	'NP');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Nam Phong',	'KK',	'NA');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Nam Som',	'UN',	'NS');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Na Muen',	'NA',	'NM');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Nam Yuen',	'UR',	'NY');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Nan',	'NA',	'NA');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Nang Rong',	'BR',	'NR');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Na Noi',	'NA',	'NN');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Na Pho',	'BR',	'NP');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Narathiwat',	'NW',	'NA');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Na Tan',	'UR',	'NT');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Na Thawi',	'SG',	'NT');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Na Thom',	'NF',	'NT');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Na Wa',	'NF',	'NW');
INSERT INTO @tbl VALUES ('Nong Bua Lam Phu'            ,	     'Na Wang',	'NB',	'NW');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Na Yai Am',	'CT',	'NA');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Na Yia',	'UR',	'NA');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Na Yong',	'TG',	'NY');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Na Yung',	'UN',	'NY');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Ngao',	'LG',	'NG');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'NiKhom Kham Soi',	'MD',	'NK');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Nikhom Nam Un',	'SN',	'NN');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Nikhom Phatthana',	'RY',	'NP');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Noen Kham',	'CN',	'NK');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Noen Maprang',	'PS',	'NM');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Noen Sa-nga',	'CY',	'NS');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Non Daeng',	'NR',	'ND');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Non Din Daeng',	'BR',	'ND');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Nong Bua',	'NS',	'NB');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Nong Bua Daeng',	'CY',	'ND');
INSERT INTO @tbl VALUES ('Nong Bua Lam Phu'            ,	     'Nong Bua Lam Phu',	'NB',	'NB');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Nong Bua Rawe',	'CY',	'NR');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Nong Bun Mak',	'NR',	'NB');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Nong Chang',	'UT',	'NC');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Nong Chik',	'PI',	'NC');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Nong Chok',	'BM',	'NC');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Nong Don',	'SR',	'ND');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Nong Han',	'UN',	'NH');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Nong Hi',	'RE',	'NH');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Nong Hin',	'LE',	'NO');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Nong Hong',	'BR',	'NH');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Nong Khae',	'SR',	'NK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Nong Khaem',	'BM',	'NK');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Nong Khai',	'NH',	'NK');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Nong Khayang',	'UT',	'NK');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Nong Ki',	'BR',	'NK');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Nong Kung Si',	'KL',	'NS');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Nong Mamong',	'CN',	'NM');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Nong Muang',	'LB',	'NM');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Nong Muang Khai',	'PR',	'NM');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Nong Na Kham',	'KK',	'NK');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Nong Phai',	'PH',	'NP');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Nong Phok',	'RE',	'NP');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Nong Prue',	'KN',	'NP');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Nong Ruea',	'KK',	'NR');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Nong Saeng',	'SR',	'NS');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Nong Saeng',	'UN',	'NO');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Nong Song Hong',	'KK',	'NH');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Nong Suea',	'PT',	'NS');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'Nong Sung',	'MD',	'NS');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Nong Wua So',	'UN',	'NW');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Nong Yai',	'CB',	'NO');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Nong Ya Plong',	'PE',	'NY');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Nong Ya Sai',	'SH',	'NY');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Non Khun',	'SI',	'NK');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Non Narai',	'SU',	'NN');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Non Sa-at',	'UN',	'SA');
INSERT INTO @tbl VALUES ('Nong Bua Lam Phu'            ,	     'Non Sang',	'NB',	'NS');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Non Sila',	'KK',	'NS');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Non Sung',	'NR',	'NS');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Non Suwan',	'BR',	'NS');
INSERT INTO @tbl VALUES ('Nonthaburi'            ,	     'Nonthaburi',	'NO',	'NO');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Non Thai',	'NR',	'NT');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Nopphitam',	'NT',	'NO');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Nuea Khlong',	'KR',	'NK');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Omkoi',	'CM',	'OM');
INSERT INTO @tbl VALUES ('Nakhon Nayok'            ,	     'Ongkharak',	'NN',	'ON');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Pa Bon',	'PL',	'PB');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Pa Daet',	'CR',	'PA');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Pai',	'MH',	'PA');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Pak Chom',	'LE',	'PC');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Pak Chong',	'NR',	'PC');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Pakham',	'BR',	'PA');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Pak Khat',	'BK',	'PK');
INSERT INTO @tbl VALUES ('Nonthaburi'            ,	     'Pak Kret',	'NO',	'PK');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Pak Phanang',	'NT',	'PN');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Pak Phayun',	'PL',	'PK');
INSERT INTO @tbl VALUES ('Nakhon Nayok'            ,	     'Pak Phli',	'NN',	'PP');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Pak Tho',	'RT',	'PT');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Pak Thong Chai',	'NR',	'PT');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Palian',	'TG',	'PA');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Pa Mok',	'AT',	'PA');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Panare',	'PI',	'PN');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Pang Mapha',	'MH',	'PM');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Pang Sila Thong',	'KP',	'PS');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Pa Phayom',	'PL',	'PP');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Pa Sang',	'LN',	'PS');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Pathio',	'CP',	'PA');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Pathum Rat',	'RE',	'PR');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Pathum Ratchawongsa',	'AC',	'PA');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Pathum Thani',	'PT',	'PT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Pathum Wan',	'BM',	'PA');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Pa Tio',	'YS',	'PT');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Pattani',	'PI',	'PT');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Phachi',	'PA',	'PC');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Phaisali',	'NS',	'PH');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Phakdi Chumphon',	'CY',	'PC');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Phak Hai',	'PA',	'PH');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Pha Khao',	'LE',	'PH');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Phan',	'CR',	'PH');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Phana',	'AC',	'PH');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Phanat Nikhom',	'CB',	'PN');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Phang Khon',	'SN',	'PK');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Phanna Nikhom',	'SN',	'PN');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Phanom',	'ST',	'PH');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Phanom Dong Rak',	'SU',	'PD');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Phanom Phrai',	'RE',	'PP');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Phanom Sarakham',	'CC',	'PS');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Phanom Thuan',	'KN',	'PT');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Phan Thong',	'CB',	'PT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Phasi Charoen',	'BM',	'PC');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Phato',	'CP',	'PH');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Phatthalung',	'PL',	'PH');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Phatthana Nikhom',	'LB',	'PN');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Phayakkhaphum Phisai',	'MS',	'PP');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Phaya Mengrai',	'CR',	'PM');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Phayao',	'PY',	'PH');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Phaya Thai',	'BM',	'PT');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Phayu',	'SI',	'PY');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Phayuha Khiri',	'NS',	'PK');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Phen',	'UN',	'PH');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Phetchabun',	'PH',	'PH');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Phetchaburi',	'PE',	'PH');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Phibun Mangsahan',	'UR',	'PM');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Phibun Rak',	'UN',	'PR');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Phichai',	'UD',	'PH');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Phichit',	'PC',	'PH');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Phimai',	'NR',	'PH');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Phipun',	'NT',	'PH');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Phitsanulok',	'PS',	'PH');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Phlapphla Chai',	'BR',	'PP');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Pho Chai',	'RE',	'PC');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Phon',	'KK',	'PN');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Phon Charoen',	'BK',	'PC');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Phon Na Kaeo',	'SN',	'NK');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Phon Phisai',	'NH',	'PP');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Phon Sai',	'RE',	'PS');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Phon Sawan',	'NF',	'PS');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Phon Thong',	'RE',	'PT');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Phop Phra',	'TK',	'PP');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Pho Prathap Chang',	'PC',	'PP');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Pho Sai',	'UR',	'PS');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Pho Si Suwan',	'SI',	'PS');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Pho Tak',	'NH',	'PT');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Pho Thale',	'PC',	'PT');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Photharam',	'RT',	'PH');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Pho Thong',	'AT',	'PH');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Phrae',	'PR',	'PH');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Phrai Bueng',	'SI',	'PB');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Phra Khanong',	'BM',	'PK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Phra Nakhon',	'BM',	'PN');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Phra Nakhon Si Ayutthaya',	'PA',	'PN');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Phran Kratai',	'KP',	'PK');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Phrao',	'CM',	'PH');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Phra Phrom',	'NT',	'PP');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Phra Phutthabat',	'SR',	'PP');
INSERT INTO @tbl VALUES ('Samut Prakan'            ,	     'Phra Pradaeng',	'SP',	'PP');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Phrasaeng',	'ST',	'PS');
INSERT INTO @tbl VALUES ('Samut Prakan'            ,	     'Phra Samut Chedi',	'SP',	'PS');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Phra Thong Kham',	'NR',	'TK');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Phra Yuen',	'KK',	'PY');
INSERT INTO @tbl VALUES ('Sing Buri'            ,	     'Phrom Buri',	'SB',	'PB');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Phrom Khiri',	'NT',	'PK');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Phrom Phiram',	'PS',	'PP');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Phu Kamyao',	'PY',	'PK');
INSERT INTO @tbl VALUES ('Phuket'            ,	     'Phuket',	'PU',	'PH');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Phu Khiao',	'CY',	'PK');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Phu Kradueng',	'LE',	'PK');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Phu Luang',	'LE',	'PL');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Phunphin',	'ST',	'PP');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Phu Pha Man',	'KK',	'PP');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Phu Phan',	'SN',	'PP');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Phu Phiang',	'NA',	'PP');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Phu Ruea',	'LE',	'PR');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Phu Sang',	'PY',	'PS');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Phu Sing',	'SI',	'PH');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Phutthaisong',	'BR',	'PH');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Phutthamonthon',	'NP',	'PH');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Phu Wiang',	'KK',	'PG');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Plaeng Yao',	'CC',	'PY');
INSERT INTO @tbl VALUES ('Krabi'            ,	     'Plai Phraya',	'KR',	'PP');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Pla Pak',	'NF',	'PP');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Pluak Daeng',	'RY',	'PD');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Pom Prap Sattru Phai',	'BM',	'PP');
INSERT INTO @tbl VALUES ('Phayao'            ,	     'Pong',	'PY',	'PO');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Pong Nam Ron',	'CT',	'PO');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Prachaksinlapakhom',	'UN',	'PS');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Prachantakham',	'PB',	'PR');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Prachin Buri',	'PB',	'PB');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Prachuap Khiri Khan',	'PK',	'PK');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Prakhon Chai',	'BR',	'PC');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Pran Buri',	'PK',	'PB');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Prang Ku',	'SI',	'PK');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Prasat',	'SU',	'PR');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Prathai',	'NR',	'PR');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Prawet',	'BM',	'PR');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Pua',	'NA',	'PU');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Pueai Noi',	'KK',	'PU');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Raman',	'YL',	'RA');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Ra-ngae',	'NW',	'RA');
INSERT INTO @tbl VALUES ('Ranong'            ,	     'Ranong',	'RN',	'RA');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Ranot',	'SG',	'RN');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Rasi Salai',	'SI',	'RS');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Rat Burana',	'BM',	'RB');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Ratchaburi',	'RT',	'RA');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Ratchasan',	'CC',	'RA');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Ratchathewi',	'BM',	'RT');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Ratsada',	'TG',	'RA');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Rattanaburi',	'SU',	'RA');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Rattanawapi',	'NH',	'RA');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Rattaphum',	'SG',	'RT');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Rayong',	'RY',	'RA');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Renu Nakhon',	'NF',	'RN');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Roi Et',	'RE',	'RE');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Rong Kham',	'KL',	'RK');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Rong Kwang',	'PR',	'RK');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Ron Phibun',	'NT',	'RP');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Rueso',	'NW',	'RU');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Saba Yoi',	'SG',	'SY');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Sa Bot',	'LB',	'SB');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Sadao',	'SG',	'SA');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Sahatsakhan',	'KL',	'SA');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Sai Buri',	'PI',	'SB');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Sai Mai',	'BM',	'SM');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Sai Mun',	'YS',	'SM');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Sai Ngam',	'KP',	'SN');
INSERT INTO @tbl VALUES ('Nonthaburi'            ,	     'Sai Noi',	'NO',	'SN');
INSERT INTO @tbl VALUES ('Kamphaeng Phet'            ,	     'Sai Thong Watthana',	'KP',	'ST');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Sai Yok',	'KN',	'SY');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Sa Kaeo',	'SK',	'SK');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Sakhrai',	'NH',	'SK');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Sak Lek',	'PC',	'SL');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Sakon Nakhon',	'SN',	'SN');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Sam Chai',	'KL',	'SC');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Sam Chuk',	'SH',	'SC');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Sam Khok',	'PT',	'SK');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Samko',	'AT',	'SA');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Sam Ngam',	'PC',	'SN');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Sam Ngao',	'TK',	'SN');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Samoeng',	'CM',	'SM');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Samphanthawong',	'BM',	'SA');
INSERT INTO @tbl VALUES ('Nakhon Pathom'            ,	     'Sam Phran',	'NP',	'SP');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Sam Roi Yot',	'PK',	'SR');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Samrong',	'UR',	'SA');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Samrong Thap',	'SU',	'ST');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Sam Sung',	'KK',	'SA');
INSERT INTO @tbl VALUES ('Samut Prakan'            ,	     'Samut Prakan',	'SP',	'SP');
INSERT INTO @tbl VALUES ('Samut Sakhon'            ,	     'Samut Sakhon',	'SS',	'SS');
INSERT INTO @tbl VALUES ('Samut Songkhram'            ,	     'Samut Songkhram',	'SM',	'SS');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Sanam Chai Khet',	'CC',	'SA');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Sangkha',	'SU',	'SK');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Sangkhla Buri',	'KN',	'SB');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Sangkhom',	'NH',	'SA');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Sang Khom',	'UN',	'SK');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'San Kamphaeng',	'CM',	'SK');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Sankhaburi',	'CN',	'SN');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Sanom',	'SU',	'SA');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'San Pa Tong',	'CM',	'SP');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'San Sai',	'CM',	'SS');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Santi Suk',	'NA',	'SS');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Sao Hai',	'SR',	'SH');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Saphan Sung',	'BM',	'SS');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Sapphaya',	'CN',	'SP');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Sap Yai',	'CY',	'SA');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Saraburi',	'SR',	'SA');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Saraphi',	'CM',	'SA');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Sathing Phra',	'SG',	'SP');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Sathon',	'BM',	'ST');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Sattahip',	'CB',	'SA');
INSERT INTO @tbl VALUES ('Buri Ram'            ,	     'Satuek',	'BR',	'SA');
INSERT INTO @tbl VALUES ('Satun'            ,	     'Satun',	'SA',	'SA');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Sawaeng Ha',	'AT',	'SH');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Sawang Arom',	'UT',	'SA');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Sawang Daen Din',	'SN',	'DD');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Sawang Wirawong',	'UR',	'SW');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Sawankhalok',	'SO',	'SA');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Sawi',	'CP',	'SA');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Seka',	'BK',	'SE');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Selaphum',	'RE',	'SE');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Sena',	'PA',	'SE');
INSERT INTO @tbl VALUES ('Amnat Charoen'            ,	     'Senangkhanikhom',	'AC',	'SE');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Si Banphot',	'PL',	'SB');
INSERT INTO @tbl VALUES ('Nong Bua Lam Phu'            ,	     'Si Bun Rueang',	'NB',	'SB');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Si Chiang Mai',	'NH',	'SC');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Si Chomphu',	'KK',	'SI');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Sichon',	'NT',	'SI');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Sida',	'NR',	'SD');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Sikao',	'TG',	'SI');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Sikhio',	'NR',	'SI');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Sikhoraphum',	'SU',	'SI');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Sila Lat',	'SI',	'SL');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Si Maha Phot',	'PB',	'SP');
INSERT INTO @tbl VALUES ('Prachin Buri'            ,	     'Si Mahosot',	'PB',	'SM');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Si Mueang Mai',	'UR',	'MM');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Si Nakhon',	'SO',	'SN');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Si Narong',	'SU',	'SN');
INSERT INTO @tbl VALUES ('Sing Buri'            ,	     'Sing Buri',	'SB',	'SB');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Singhanakhon',	'SG',	'SI');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Si Prachan',	'SH',	'SP');
INSERT INTO @tbl VALUES ('Chon Buri'            ,	     'Si Racha',	'CB',	'SI');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Si Rattana',	'SI',	'SR');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Sirindhorn',	'UR',	'SI');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Si Sa Ket',	'SI',	'SS');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Si Sakhon',	'NW',	'SS');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Si Samrong',	'SO',	'SR');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Si Satchanalai',	'SO',	'SS');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Si Sawat',	'KN',	'SS');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Si Somdet',	'RE',	'SS');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Si Songkhram',	'NF',	'SS');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Si That',	'UN',	'ST');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Si Thep',	'PH',	'ST');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'Si Wilai',	'BK',	'SW');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Soem Ngam',	'LG',	'SN');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Soeng Sang',	'NR',	'SS');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Soi Dao',	'CT',	'SO');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Somdet',	'KL',	'SO');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Song',	'PR',	'SO');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Song Dao',	'SN',	'SD');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Songkhla',	'SG',	'SO');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Song Khwae',	'NA',	'SK');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Song Phi Nong',	'SH',	'SN');
INSERT INTO @tbl VALUES ('Bueng Kan'            ,	     'So Phisai',	'BK',	'SP');
INSERT INTO @tbl VALUES ('Mae Hong Son'            ,	     'Sop Moei',	'MH',	'SM');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Sop Prap',	'LG',	'SP');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Srinagarindra',	'PL',	'SR');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Suan Luang',	'BM',	'SL');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Suan Phueng',	'RT',	'SP');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Sukhirin',	'NW',	'SU');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Sukhothai',	'SO',	'SU');
INSERT INTO @tbl VALUES ('Ranong'            ,	     'Suk Samran',	'RN',	'SS');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Su-ngai Kolok',	'NW',	'SK');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Su-ngai Padi',	'NW',	'SP');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Sung Men',	'PR',	'SM');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Sung Noen',	'NR',	'SN');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'Suphan Buri',	'SH',	'SB');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Surat Thani',	'ST',	'ST');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Surin',	'SU',	'SU');
INSERT INTO @tbl VALUES ('Nong Bua Lam Phu'            ,	     'Suwannakhuha',	'NB',	'SU');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Suwannaphum',	'RE',	'SU');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Tak',	'TK',	'TA');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Tak Bai',	'NW',	'TB');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Tak Fa',	'NS',	'TP');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Takhli',	'NS',	'TA');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Takua Pa',	'PG',	'TK');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Takua Thung',	'PG',	'TT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Taling Chan',	'BM',	'TA');
INSERT INTO @tbl VALUES ('Phatthalung'            ,	     'Tamot',	'PL',	'TA');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Tan Sum',	'UR',	'TS');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Tao Ngoi',	'SN',	'TN');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Taphan Hin',	'PC',	'TH');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Ta Phraya',	'SK',	'TP');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Tap Khlo',	'PC',	'TK');
INSERT INTO @tbl VALUES ('Nong Khai'            ,	     'Tha Bo',	'NH',	'TB');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Tha Chana',	'ST',	'TA');
INSERT INTO @tbl VALUES ('Sing Buri'            ,	     'Tha Chang',	'SB',	'TC');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Tha Chang',	'ST',	'TG');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Thai Charoen',	'YS',	'TC');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Thai Mueang',	'PG',	'TM');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Tha Khantho',	'KL',	'TK');
INSERT INTO @tbl VALUES ('Phuket'            ,	     'Thalang',	'PU',	'TH');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Tha Li',	'LE',	'TL');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Tha Luang',	'LB',	'TL');
INSERT INTO @tbl VALUES ('Chanthaburi'            ,	     'Tha Mai',	'CT',	'TH');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Tha Maka',	'KN',	'TM');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Tham Phannara',	'NT',	'TP');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Tha Muang',	'KN',	'TH');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Than To',	'YL',	'TT');
INSERT INTO @tbl VALUES ('Pathum Thani'            ,	     'Thanyaburi',	'PT',	'TH');
INSERT INTO @tbl VALUES ('Satun'            ,	     'Tha Phae',	'SA',	'TP');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Tha Pla',	'UD',	'TP');
INSERT INTO @tbl VALUES ('Phangnga'            ,	     'Thap Put',	'PG',	'TP');
INSERT INTO @tbl VALUES ('Prachuap Khiri Khan'            ,	     'Thap Sakae',	'PK',	'TS');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Thap Than',	'UT',	'TT');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Tha Ruea',	'PA',	'TR');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Tha Sae',	'CP',	'TS');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Tha Sala',	'NT',	'TS');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Tha Song Yang',	'TK',	'TS');
INSERT INTO @tbl VALUES ('Chachoengsao'            ,	     'Tha Takiap',	'CC',	'TH');
INSERT INTO @tbl VALUES ('Nakhon Sawan'            ,	     'Tha Tako',	'NS',	'TT');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'That Phanom',	'NF',	'TP');
INSERT INTO @tbl VALUES ('Surin'            ,	     'Tha Tum',	'SU',	'TT');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Tha Uthen',	'NF',	'TU');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Tha Wang Pha',	'NA',	'TW');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Thawat Buri',	'RE',	'TB');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Thawi Watthana',	'BM',	'TW');
INSERT INTO @tbl VALUES ('Lop Buri'            ,	     'Tha Wung',	'LB',	'TW');
INSERT INTO @tbl VALUES ('Phetchaburi'            ,	     'Tha Yang',	'PE',	'TY');
INSERT INTO @tbl VALUES ('Songkhla'            ,	     'Thepha',	'SG',	'TH');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Thepharak',	'NR',	'TH');
INSERT INTO @tbl VALUES ('Chaiyaphum'            ,	     'Thep Sathit',	'CY',	'TS');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Thoen',	'LG',	'TH');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Thoeng',	'CR',	'TH');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Thon Buri',	'BM',	'TB');
INSERT INTO @tbl VALUES ('Kanchanaburi'            ,	     'Thong Pha Phum',	'KN',	'TP');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Thong Saen Khan',	'UD',	'TS');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Thung Chang',	'NA',	'TC');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Thung Fon',	'UN',	'TF');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Thung Hua Chang',	'LN',	'TH');
INSERT INTO @tbl VALUES ('Roi Et'            ,	     'Thung Khao Luang',	'RE',	'TK');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Thung Khru',	'BM',	'TK');
INSERT INTO @tbl VALUES ('Sukhothai'            ,	     'Thung Saliam',	'SO',	'TS');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Thung Si Udom',	'UR',	'TU');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Thung Song',	'NT',	'TH');
INSERT INTO @tbl VALUES ('Chumphon'            ,	     'Thung Tako',	'CP',	'TT');
INSERT INTO @tbl VALUES ('Satun'            ,	     'Thung Wa',	'SA',	'TW');
INSERT INTO @tbl VALUES ('Nakhon Si Thammarat'            ,	     'Thung Yai',	'NT',	'TY');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Thung Yang Daeng',	'PI',	'TY');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Trakan Phuet Phon',	'UR',	'TP');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Trang',	'TG',	'TR');
INSERT INTO @tbl VALUES ('Trat'            ,	     'Trat',	'TT',	'TR');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Tron',	'UD',	'TR');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Ubolratana',	'KK',	'UB');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Ubon Ratchathani',	'UR',	'UR');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Udon Thani',	'UN',	'UT');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Umphang',	'TK',	'UM');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Uthai',	'PA',	'UT');
INSERT INTO @tbl VALUES ('Uthai Thani'            ,	     'Uthai Thani',	'UT',	'UT');
INSERT INTO @tbl VALUES ('Suphan Buri'            ,	     'U Thong',	'SH',	'UT');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Uthumphon Phisai',	'SI',	'UP');
INSERT INTO @tbl VALUES ('Uttaradit'            ,	     'Uttaradit',	'UD',	'UT');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Vibhavadi',	'ST',	'VI');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Wachirabarami',	'PC',	'WA');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Waeng',	'NW',	'WA');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Waeng Noi',	'KK',	'WN');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Waeng Yai',	'KK',	'WY');
INSERT INTO @tbl VALUES ('Rayong'            ,	     'Wang Chan',	'RY',	'WC');
INSERT INTO @tbl VALUES ('Tak'            ,	     'Wang Chao',	'TK',	'WC');
INSERT INTO @tbl VALUES ('Phrae'            ,	     'Wang Chin',	'PR',	'WC');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Wang Hin',	'SI',	'WH');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Wang Muang',	'SR',	'WM');
INSERT INTO @tbl VALUES ('Nakhon Ratchasima'            ,	     'Wang Nam Khiao',	'NR',	'WN');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Wang Nam Yen',	'SK',	'WY');
INSERT INTO @tbl VALUES ('Phra Nakhon Si Ayutthaya'            ,	     'Wang Noi',	'PA',	'WN');
INSERT INTO @tbl VALUES ('Lampang'            ,	     'Wang Nuea',	'LG',	'WN');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Wang Pong',	'PH',	'WP');
INSERT INTO @tbl VALUES ('Phichit'            ,	     'Wang Sai Phun',	'PC',	'WS');
INSERT INTO @tbl VALUES ('Udon Thani'            ,	     'Wang Sam Mo',	'UN',	'WS');
INSERT INTO @tbl VALUES ('Loei'            ,	     'Wang Saphung',	'LE',	'WS');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Wang Sombun',	'SK',	'WS');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Wang Thong',	'PS',	'WT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Wang Thonglang',	'BM',	'WT');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Wang Wiset',	'TG',	'WW');
INSERT INTO @tbl VALUES ('Nakhon Phanom'            ,	     'Wang Yang',	'NF',	'WY');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Wanon Niwat',	'SN',	'WN');
INSERT INTO @tbl VALUES ('Mukdahan'            ,	     'Wan Yai',	'MD',	'WY');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Wapi Pathum',	'MS',	'WP');
INSERT INTO @tbl VALUES ('Ubon Ratchathani'            ,	     'Warin Chamrap',	'UR',	'WC');
INSERT INTO @tbl VALUES ('Sakon Nakhon'            ,	     'Waritchaphum',	'SN',	'WA');
INSERT INTO @tbl VALUES ('Phitsanulok'            ,	     'Wat Bot',	'PS',	'WB');
INSERT INTO @tbl VALUES ('Ratchaburi'            ,	     'Wat Phleng',	'RT',	'WP');
INSERT INTO @tbl VALUES ('Chai Nat'            ,	     'Wat Sing',	'CN',	'WA');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Watthana',	'BM',	'WA');
INSERT INTO @tbl VALUES ('Sa Kaeo'            ,	     'Watthana Nakhon',	'SK',	'WN');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Wiang Chai',	'CR',	'WC');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Wiang Chiang Rung',	'CR',	'WR');
INSERT INTO @tbl VALUES ('Chiang Mai'            ,	     'Wiang Haeng',	'CM',	'WI');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Wiang Kaen',	'CR',	'WK');
INSERT INTO @tbl VALUES ('Khon Kaen'            ,	     'Wiang Kao',	'KK',	'WK');
INSERT INTO @tbl VALUES ('Lamphun'            ,	     'Wiang Nong Long',	'LN',	'WN');
INSERT INTO @tbl VALUES ('Chiang Rai'            ,	     'Wiang Pa Pao',	'CR',	'WP');
INSERT INTO @tbl VALUES ('Nan'            ,	     'Wiang Sa',	'NA',	'WS');
INSERT INTO @tbl VALUES ('Surat Thani'            ,	     'Wiang Sa',	'ST',	'WS');
INSERT INTO @tbl VALUES ('Phetchabun'            ,	     'Wichian Buri',	'PH',	'WB');
INSERT INTO @tbl VALUES ('Saraburi'            ,	     'Wihan Daeng',	'SR',	'WD');
INSERT INTO @tbl VALUES ('Ang Thong'            ,	     'Wiset Chai Chan',	'AT',	'WI');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Yaha',	'YL',	'YH');
INSERT INTO @tbl VALUES ('Yala'            ,	     'Yala',	'YL',	'YL');
INSERT INTO @tbl VALUES ('Si Sa Ket'            ,	     'Yang Chum Noi',	'SI',	'YC');
INSERT INTO @tbl VALUES ('Maha Sarakham'            ,	     'Yang Sisurat',	'MS',	'YS');
INSERT INTO @tbl VALUES ('Kalasin'            ,	     'Yang Talat',	'KL',	'YT');
INSERT INTO @tbl VALUES ('Bangkok Metropolis'            ,	     'Yan Nawa',	'BM',	'YA');
INSERT INTO @tbl VALUES ('Trang'            ,	     'Yan Ta Khao',	'TG',	'YT');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Yarang',	'PI',	'YA');
INSERT INTO @tbl VALUES ('Pattani'            ,	     'Yaring',	'PI',	'YI');
INSERT INTO @tbl VALUES ('Yasothon'            ,	     'Yasothon',	'YS',	'YA');
INSERT INTO @tbl VALUES ('Narathiwat'            ,	     'Yi-ngo',	'NW',	'YI');

SET NOCOUNT OFF

INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) 
	SELECT	DISTINCT @country_id, level_1_nm, level_1_cd
	FROM	@tbl;

-- ======================================================================


INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl	t
		LEFT JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				)

-- ======================================================================

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);


UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

-- ======================================================================

