// Generated on : 02 Aug 14 - 18:12:28
///This code is auto generated by CDF.
///Please don't alter the contents of this file

using System.Collections.Generic;
using System;
using System.Data;
using System.Data.SqlClient;
using DCC.UMB.WDF.DB;
using System.Text;
using System.Linq;
namespace DCC.CDB.DBFacade {
    public partial class CDB_APPDbFacade : IDBFacade{
        public void CommitTrans(string auditObjectId) { this.CommitTrans(); }
    }
}
