/* ==================================================================================
    Source File		:	setup_sri_lanka_components.sql
	Author(s)		:	Jitendra Loyal
	Started On		:	Mon Sep 15 12:02 2014
	Module ID		:	CDB
	Last updated	:	Sep 15, 2014
	==================================================================================
																		   Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of Sri Lanka are set-up
	==================================================================================
																	  Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'Sri Lanka';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('Country Sri Lanka not found', 16, 1);
	RETURN;
END

-- ======================================================================

DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50) PRIMARY KEY, level_1_cd varchar (5) UNIqUE);

INSERT INTO @tbl VALUES ( 'Kandy', 'KY')
INSERT INTO @tbl VALUES ( 'Matale', 'MT')
INSERT INTO @tbl VALUES ( 'Nuwara Eliya', 'NW')
INSERT INTO @tbl VALUES ( 'Ampara', 'AP')
INSERT INTO @tbl VALUES ( 'Batticaloa', 'BC')
INSERT INTO @tbl VALUES ( 'Trincomalee', 'TC')
INSERT INTO @tbl VALUES ( 'Anuradhapura', 'AD')
INSERT INTO @tbl VALUES ( 'Polonnaruwa', 'PR')
INSERT INTO @tbl VALUES ( 'Kurunegala', 'KG')
INSERT INTO @tbl VALUES ( 'Puttalam', 'PX')
INSERT INTO @tbl VALUES ( 'Jaffna', 'JA')
INSERT INTO @tbl VALUES ( 'Kilinochchi', 'KL')
INSERT INTO @tbl VALUES ( 'Mannar', 'MB')
INSERT INTO @tbl VALUES ( 'Mullaitivu', 'MP')
INSERT INTO @tbl VALUES ( 'Vavuniya', 'VA')
INSERT INTO @tbl VALUES ( 'Kegalle', 'KE')
INSERT INTO @tbl VALUES ( 'Ratnapura', 'RN')
INSERT INTO @tbl VALUES ( 'Galle', 'GL')
INSERT INTO @tbl VALUES ( 'Hambantota', 'HB')
INSERT INTO @tbl VALUES ( 'Matara', 'MH')
INSERT INTO @tbl VALUES ( 'Badulla', 'BD')
INSERT INTO @tbl VALUES ( 'Moneragala', 'MJ')
INSERT INTO @tbl VALUES ( 'Colombo', 'CO')
INSERT INTO @tbl VALUES ( 'Gampaha', 'GQ')
INSERT INTO @tbl VALUES ( 'Kalutara', 'KT')

INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) 
	SELECT	@country_id, level_1_nm, level_1_cd
	FROM	@tbl;

-- ======================================================================

SET NOCOUNT ON
DECLARE	@tbl2	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl2 VALUES ( 'Kandy', 'Akurana', 'AK')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Delthota', 'DE')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Doluwa', 'DO')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Ganga Ihala Korale', 'GI')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Harispattuwa', 'HP')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Hatharaliyadda', 'HY')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'K.F.G. & G. Korale', 'KG')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Kundasale', 'KU')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Medadumbara', 'ME')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Minipe', 'MI')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Panvila', 'PV')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Pasbage Korale', 'PK')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Pathadumbara', 'PD')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Pathahewaheta', 'PH')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Poojapitiya', 'PO')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Thumpane', 'TH')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Udadumbara', 'UD')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Udapalatha', 'UP')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Udunuwara', 'UN')
INSERT INTO @tbl2 VALUES ( 'Kandy', 'Yatinuwara', 'YA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Ambanganga Korale', 'AK')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Dambulla', 'DA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Galewela', 'GA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Laggala-Pallegama', 'LP')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Matale', 'MA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Naula', 'NA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Pallepola', 'PA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Rattota', 'RA')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Ukuwela', 'UK')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Wilgamuwa', 'WI')
INSERT INTO @tbl2 VALUES ( 'Matale', 'Yatawatta', 'YA')
INSERT INTO @tbl2 VALUES ( 'Nuwara Eliya', 'Ambagamuwa', 'AM')
INSERT INTO @tbl2 VALUES ( 'Nuwara Eliya', 'Hanguranketha', 'HA')
INSERT INTO @tbl2 VALUES ( 'Nuwara Eliya', 'Kothmale', 'KO')
INSERT INTO @tbl2 VALUES ( 'Nuwara Eliya', 'Nuwara Eliya', 'NE')
INSERT INTO @tbl2 VALUES ( 'Nuwara Eliya', 'Walapane', 'WA')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Addalachchenai', 'AD')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Akkaraipattu', 'AK')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Alayadiwembu', 'AL')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Ampara', 'AM')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Damana', 'DA')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Dehiattakandiya', 'DE')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Eragama', 'ER')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Kalmunai', 'KM')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Karativu', 'KR')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Lahugala', 'LA')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Mahaoya', 'MA')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Navithanveli', 'NA')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Ninthavur', 'NI')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Padiyathalawa', 'PA')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Pothuvil', 'PO')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Sainthamarathu', 'SI')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Samanthurai', 'SM')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Thirukkovil', 'TH')
INSERT INTO @tbl2 VALUES ( 'Ampara', 'Uhana', 'UH')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Eravur Pattu', 'EP')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Eravur Town', 'ET')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Kattankudy', 'KA')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Koralai Pattu (Valachchenai)', 'KP')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Koralai Pattu North', 'KN')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Koralai Pattu West (Oddamavadi)', 'KW')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Manmunai North', 'MN')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Manmunai Pattu (Araipattai)', 'MP')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Manmunai South and Eruvilpattu', 'ME')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Manmunai South-West', 'MS')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Manmunai West', 'MW')
INSERT INTO @tbl2 VALUES ( 'Batticaloa', 'Porativu Pattu', 'PP')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Gomarankadawala', 'GO')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Kantalai', 'KA')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Kinniya', 'KI')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Kuchchaveli', 'KU')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Morawewa', 'MO')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Muttur', 'MU')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Padavi Sri Pura', 'PS')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Seruvila', 'SE')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Thampalakamam', 'TH')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Trincomalee Town and Gravets', 'TT')
INSERT INTO @tbl2 VALUES ( 'Trincomalee', 'Verugal (Echchilampattai)', 'VE')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Galenbindunuwewa', 'GB')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Galnewa', 'GN')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Horowpothana', 'HO')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Ipalogama', 'IP')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Kahatagasdigiliya', 'KA')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Kebithigollewa', 'KB')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Kekirawa', 'KK')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Maha Vilachchiya', 'MV')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Medawachchiya', 'ME')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Mihinthale', 'MI')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'N. Palatha Central', 'NC')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'N. Palatha East', 'NE')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Nachchadoowa', 'NA')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Nochchiyagama', 'NO')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Padaviya', 'PD')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Palagala', 'PL')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Palugaswewa', 'PS')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Rajanganaya', 'RJ')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Rambewa', 'RB')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Thalawa', 'TL')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Thambuttegama', 'TB')
INSERT INTO @tbl2 VALUES ( 'Anuradhapura', 'Thirappane', 'TP')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Dimbulagala', 'DI')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Elahera', 'EL')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Hingurakgoda', 'HI')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Lankapura', 'LA')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Medirigiriya', 'ME')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Thamankaduwa', 'TH')
INSERT INTO @tbl2 VALUES ( 'Polonnaruwa', 'Welikanda', 'WE')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Alawwa', 'AL')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Ambanpola', 'AM')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Bamunakotuwa', 'BA')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Bingiriya', 'BI')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Ehetuwewa', 'EH')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Galgamuwa', 'GG')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Ganewatta', 'GN')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Giribawa', 'GI')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Ibbagamuwa', 'IB')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Katupotha', 'KA')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Kobeigane', 'KB')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Kotavehera', 'KT')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Kuliyapitiya East', 'KE')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Kuliyapitiya West', 'KW')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Kurunegala', 'KU')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Mahawa', 'MH')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Mallawapitiya', 'ML')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Maspotha', 'MS')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Mawathagama', 'MW')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Narammala', 'NA')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Nikaweratiya', 'NI')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Panduwasnuwara', 'PD')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Pannala', 'PL')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Polgahawela', 'PH')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Polpithigama', 'PP')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Rasnayakapura', 'RA')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Rideegama', 'RI')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Udubaddawa', 'UD')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Wariyapola', 'WA')
INSERT INTO @tbl2 VALUES ( 'Kurunegala', 'Weerambugedara', 'WE')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Anamaduwa', 'AN')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Arachchikattuwa PS', 'AR')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Chilaw', 'CH')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Dankotuwa', 'DA')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Kalpitiya', 'KP')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Karuwalagaswewa', 'KG')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Madampe', 'MD')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Mahakumbukkadawala', 'MK')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Mahawewa', 'MW')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Mundalama', 'MU')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Nattandiya', 'NT')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Nawagattegama', 'NW')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Pallama', 'PA')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Puttalam', 'PU')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Vanathavilluwa', 'VA')
INSERT INTO @tbl2 VALUES ( 'Puttalam', 'Wennappuwa', 'WE')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Delft', 'DE')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Island South (Velanai)', 'IS')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Islands North (Kayts)', 'IN')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Jaffna', 'JA')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Nallur', 'NA')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Thenmaradchy (Chavakachcheri)', 'TH')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Vadamaradchi South-West (Karaveddy)', 'VD')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Vadamaradchy East', 'VE')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Vadamaradchy North (Point Perdro)', 'PP')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Valikamam East (Kopay)', 'VK')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Valikamam North', 'VN')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Valikamam South (Uduvil)', 'VS')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Valikamam South-West (Sandilipay)', 'SA')
INSERT INTO @tbl2 VALUES ( 'Jaffna', 'Valikamam West (Chankanai)', 'VW')
INSERT INTO @tbl2 VALUES ( 'Kilinochchi', 'Kandawali', 'KN')
INSERT INTO @tbl2 VALUES ( 'Kilinochchi', 'Karachchi', 'KR')
INSERT INTO @tbl2 VALUES ( 'Kilinochchi', 'Pachchilaipalli', 'PA')
INSERT INTO @tbl2 VALUES ( 'Kilinochchi', 'Poonakary', 'PO')
INSERT INTO @tbl2 VALUES ( 'Mannar', 'Madhu', 'MA')
INSERT INTO @tbl2 VALUES ( 'Mannar', 'Mannar Town', 'MT')
INSERT INTO @tbl2 VALUES ( 'Mannar', 'Manthai West', 'MW')
INSERT INTO @tbl2 VALUES ( 'Mannar', 'Musali', 'MU')
INSERT INTO @tbl2 VALUES ( 'Mannar', 'Nanaddan', 'NA')
INSERT INTO @tbl2 VALUES ( 'Mullaitivu', 'Manthai East', 'ME')
INSERT INTO @tbl2 VALUES ( 'Mullaitivu', 'Maritimepattu', 'MA')
INSERT INTO @tbl2 VALUES ( 'Mullaitivu', 'Oddusuddan', 'OD')
INSERT INTO @tbl2 VALUES ( 'Mullaitivu', 'Puthukudiyiruppu', 'PU')
INSERT INTO @tbl2 VALUES ( 'Mullaitivu', 'Thunukkai', 'TH')
INSERT INTO @tbl2 VALUES ( 'Vavuniya', 'Vavuniya', 'VA')
INSERT INTO @tbl2 VALUES ( 'Vavuniya', 'Vavuniya North', 'VN')
INSERT INTO @tbl2 VALUES ( 'Vavuniya', 'Vavuniya South', 'VS')
INSERT INTO @tbl2 VALUES ( 'Vavuniya', 'Vengalacheddiculam', 'VE')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Aranayaka', 'AR')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Bulathkohupitiya', 'BU')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Dehiovita', 'DH')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Deraniyagala', 'DR')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Galigamuwa', 'GA')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Kegalle', 'KE')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Mawanella', 'MA')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Rambukkana', 'RA')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Ruwanwella', 'RU')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Warakapola', 'WA')
INSERT INTO @tbl2 VALUES ( 'Kegalle', 'Yatiyanthota', 'YA')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Ayagama', 'AY')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Balangoda', 'BA')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Eheliyagoda', 'EH')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Elapatha', 'EL')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Embilipitiya', 'EM')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Godakawela', 'GO')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Imbulpe', 'IM')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Kahawatta', 'KH')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Kalawana', 'KL')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Kiriella', 'KI')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Kolonna', 'KO')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Kuruvita', 'KU')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Nivithigala', 'NI')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Opanayaka', 'OP')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Pelmadulla', 'PE')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Ratnapura', 'RA')
INSERT INTO @tbl2 VALUES ( 'Ratnapura', 'Weligepola', 'WE')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Akmeemana', 'AK')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Ambalangoda', 'AM')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Baddegama', 'BD')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Balapitiya', 'BL')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Bentota', 'BE')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Bope-Poddala', 'BP')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Elpitiya', 'EL')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Galle Four Gravets', 'GF')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Habaraduwa', 'HA')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Hikkaduwa', 'HI')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Imaduwa', 'IM')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Karandeniya', 'KA')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Nagoda', 'NA')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Neluwa', 'NE')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Niyagama', 'NI')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Thawalama', 'TH')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Welivitiya-Divithura', 'WD')
INSERT INTO @tbl2 VALUES ( 'Galle', 'Yakkalamulla', 'YA')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Ambalanthota', 'AM')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Angunakolapelessa', 'AN')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Beliatta', 'BE')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Hambantota', 'HA')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Katuwana', 'KA')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Lunugamvehera', 'LU')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Okewela', 'OK')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Sooriyawewa', 'SO')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Tangalle', 'TA')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Thissamaharama', 'TH')
INSERT INTO @tbl2 VALUES ( 'Hambantota', 'Weeraketiya', 'WE')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Akuressa', 'AK')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Athuraliya', 'AT')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Devinuwara', 'DE')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Dickwella', 'DI')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Hakmana', 'HA')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Kamburupitiya', 'KA')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Kirinda-Puhulwella', 'KP')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Kotapola', 'KO')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Malimbada', 'MA')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Matara Four Gravets', 'MF')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Mulatiyana', 'MU')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Pasgoda', 'PA')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Pitabeddara', 'PI')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Thihagoda', 'TH')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Weligama', 'WG')
INSERT INTO @tbl2 VALUES ( 'Matara', 'Welipitiya', 'WP')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Badulla', 'BD')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Bandarawela', 'BN')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Ella', 'EL')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Hali-Ela', 'HE')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Haputale', 'HA')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Hildummulla', 'HI')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Kandaketiya', 'KA')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Lunugala', 'LU')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Mahiyanganaya', 'MA')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Meegahakivula', 'ME')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Passara', 'PA')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Rideemaliyadda', 'RI')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Soranathota', 'SO')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Uva Paranagama', 'UP')
INSERT INTO @tbl2 VALUES ( 'Badulla', 'Welimada', 'WE')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Badalkumbura', 'BA')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Bibile', 'BI')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Buttala', 'BU')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Katharagama', 'KA')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Madulla', 'MA')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Medagama', 'ME')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Moneragala', 'MO')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Sevanagala', 'SE')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Siyambalanduwa', 'SI')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Thanamalvila', 'TH')
INSERT INTO @tbl2 VALUES ( 'Moneragala', 'Wellawaya', 'WE')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Colombo', 'CO')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Dehiwala-Mount Lavinia', 'DM')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Hanwella', 'HA')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Homagama', 'HO')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Kaduwela', 'KA')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Kesbewa', 'KE')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Kolonnawa', 'KO')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Maharagama', 'MA')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Moratuwa', 'MO')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Padukka', 'PA')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Rathmalana', 'RA')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Sri Jayawardanapura Kotte', 'SJ')
INSERT INTO @tbl2 VALUES ( 'Colombo', 'Thimbirigasyaya', 'TH')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Attanagalla', 'AT')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Biyagama', 'BI')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Divulapitiya', 'DI')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Dompe', 'DO')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Gampaha', 'GA')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Ja-Ela', 'JE')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Katana', 'KA')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Kelaniya', 'KE')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Mahara', 'MA')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Minuwangoda', 'MN')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Mirigama', 'MR')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Negombo', 'NE')
INSERT INTO @tbl2 VALUES ( 'Gampaha', 'Wattala', 'WA')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Agalawatta', 'AG')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Bandaragama', 'BA')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Beruwala', 'BE')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Bulathsinhala', 'BU')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Dodangoda', 'DO')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Horana', 'HO')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Ingiriya', 'IN')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Kalutara', 'KA')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Madurawala', 'MD')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Mathugama', 'MT')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Millaniya', 'MI')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Palindanuwara', 'PL')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Panadura', 'PN')
INSERT INTO @tbl2 VALUES ( 'Kalutara', 'Walallawita', 'WA')

SET NOCOUNT OFF

INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl2	t
		LEFT JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				)

-- ======================================================================

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);

UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

-- ======================================================================


