/* ==================================================================================
    Source File		:	setup_canada_components.sql
	Author(s)		:	Jitendra Loyal
	Started On		:	Tue Sep 16 12:27 2014
	Module ID		:	CDB
	Last updated	:	Sep 16, 2014
	==================================================================================
																		   Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of Canada are set-up
	==================================================================================
																	  Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'Canada';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('Country Canada not found', 16, 1);
	RETURN;
END

-- ======================================================================

DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50) PRIMARY KEY, level_1_cd varchar (5) UNIqUE);

INSERT INTO @tbl VALUES ( 'Alberta', 'AB')
INSERT INTO @tbl VALUES ( 'British Columbia', 'BC')
INSERT INTO @tbl VALUES ( 'Manitoba', 'MB')
INSERT INTO @tbl VALUES ( 'New Brunswick', 'NB')
INSERT INTO @tbl VALUES ( 'Newfoundland and Labrador', 'NF')
INSERT INTO @tbl VALUES ( 'Northwest Territories', 'NT')
INSERT INTO @tbl VALUES ( 'Nova Scotia', 'NS')
INSERT INTO @tbl VALUES ( 'Nunavut Territory', 'NU')
INSERT INTO @tbl VALUES ( 'Ontario', 'ON')
INSERT INTO @tbl VALUES ( 'Prince Edward Island', 'PE')
INSERT INTO @tbl VALUES ( 'Quebec', 'QC')
INSERT INTO @tbl VALUES ( 'Saskatchewan', 'SK')
INSERT INTO @tbl VALUES ( 'Yukon Territory', 'YT')

INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) 
	SELECT	@country_id, level_1_nm, level_1_cd
	FROM	@tbl;

-- ======================================================================

SET NOCOUNT ON
DECLARE	@tbl2	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl2 VALUES ( 'Alberta', 'Acadia MD', 'AC')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Athabasca ', 'AT')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Beaver ', 'BR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Big Lakes MD', 'BL')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Bighorn MD', 'BM')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Birch Hills ', 'BH')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Bonnyville MD', 'BV')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Brazeau ', 'BZ')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Camrose ', 'CR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Cardston ', 'CS')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Clear Hills ', 'CH')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Clearwater ', 'CW')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Barrhead No. 11', 'B11')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Forty Mile No. 8', 'FM8')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Grande Prairie No. 1', 'GP1')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Minburn No. 27', 'M27')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Newell', 'NW')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Northern Lights', 'NL')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Paintearth No. 18', 'P18')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Two Hills No. 21', 'TH31')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Vermilion River', 'VR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Warner No. 5', 'W5')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Wetaskiwin No. 10', 'W10')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Crowsnest Pass', 'CP')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Cypress ', 'CY')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Fairview MD', 'FM')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Flagstaff ', 'FS')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Foothills MD', 'FH')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Greenview MD', 'GV')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Improvement District 12', 'ID12')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Improvement District 13', 'ID13')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Improvement District 24', 'ID24')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Improvement District 25', 'ID25')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Improvement District 9', 'ID9')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Improvement District No. 4', 'ID4')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Jasper', 'J')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Kananaskis I.D.', 'KID')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Kneehill ', 'KH')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Lac La Biche ', 'LB')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Lac Ste. Anne ', 'LA')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Lacombe ', 'LC')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Lamont ', 'LM')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Leduc ', 'LD')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Lethbridge ', 'LG')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Mackenzie ', 'M')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Mountain View ', 'MV')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'MD of Lesser Slave River No. 124', 'LSR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'MD of Pincher Creek No. 9', 'PC9')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'MD of Taber', 'TB')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'MD of Willow Creek No. 26', 'WC26')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Northern Sunrise ', 'NS')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Opportunity MD', 'OM')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Parkland ', 'PL')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Peace MD', 'PM')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Ponoka ', 'PN')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Provost MD', 'PV')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Ranchland MD', 'RL')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Red Deer ', 'RD')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Rocky View ', 'RV')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Saddle Hills ', 'SH')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Smoky Lake ', 'SL')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Smoky River MD', 'SMR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Special Area 2', 'SA2')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Special Area 3', 'SA3')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Special Area 4', 'SA4')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Spirit River MD', 'SPR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'St. Paul ', 'SP')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Starland ', 'SR')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Stettler ', 'ST')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Strathcona ', 'SC')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Sturgeon ', 'SG')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Thorhild ', 'T')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Vulcan ', 'VC')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Wainwright MD', 'WM')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Westlock ', 'WL')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Wheatland ', 'WH')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Wood Buffalo', 'WB')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Woodlands ', 'WD')
INSERT INTO @tbl2 VALUES ( 'Alberta', 'Yellowhead ', 'YH')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Alberni-Clayoquot', 'AC')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Bulkley-Nechako', 'BN')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Capital', 'CP')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Cariboo', 'CR')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Central Coast', 'CC')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Central Kootenay', 'CK')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Central Okanagan', 'CO')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Columbia-Shuswap', 'CS')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Comox-Strathcona', 'CX')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Cowichan Valley', 'CV')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'East Kootenay', 'EK')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Fort Nelson-Liard', 'FL')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Fraser Valley', 'FV')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Fraser-Fort George', 'FF')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Greater Vancouver', 'GV')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Kitimat-Stikine', 'KS')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Kootenay Boundary', 'KB')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Mount Waddington', 'MW')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Nanaimo', 'NA')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'North Okanagan', 'NO')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Okanagan-Similkameen', 'OS')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Peace River', 'PC')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Powell River', 'PW')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Skeena-Queen Charlotte', 'SQ')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Squamish-Lillooet', 'SL')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Stikine', 'ST')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Sunshine Coast', 'SC')
INSERT INTO @tbl2 VALUES ( 'British Columbia', 'Thompson-Nicola', 'TN')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Eastern Manitoba', 'EM')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Steinbach Area', 'SB')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Pembina Valley', 'PV')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Pilot Mound Area', 'PM')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'South West Westman', 'SWW')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Virden Area', 'VA')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Brandon Area', 'BA')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Central Manitoba', 'CM')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Portage la Prairie Area', 'PPA')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Whitehorse Plains', 'WP')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Winnipeg', 'WN')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Beausejour Area', 'BJ')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Selkirk Area', 'SK')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'South Interlake Region', 'SIR')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Western Manitoba Westman', 'WMW')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Roblin', 'RB')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Dauphin', 'DP')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'North Interlake Area Interlake Region', 'NIAIR')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'North East Northern Region', 'NENR')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Swan River', 'SR')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Flin Flon and North West Northern Region', 'FF')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Thompson & North Central Northern Region', 'TH')
INSERT INTO @tbl2 VALUES ( 'Manitoba', 'Churchill and Northern Manitoba', 'CNM')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Albert', 'AL')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Carleton', 'CA')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Charlotte', 'CH')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Gloucester', 'GL')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Kent', 'KE')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Kings', 'KI')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Madawaska', 'MA')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Northumberland', 'NO')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Queens', 'QU')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Restigouche', 'RE')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Saint John', 'SJ')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Sunbury', 'SU')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Victoria', 'VI')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'Westmorland', 'WE')
INSERT INTO @tbl2 VALUES ( 'New Brunswick', 'York', 'YO')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Avalon Peninsula-St. John''s', 'AP')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Burin Peninsula-Marystown', 'BP')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'South Coast-Channel-Port aux Basques', 'SC')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'St. George''s-Stephenville', 'SG')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Humber District-Corner Brook', 'HD')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Central Newfoundland-Grand Falls-Windsor', 'CN')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Bonavista/Trinity-Clarenville', 'BT')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Notre Dame Bay-Lewisporte', 'NDB')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Northern Peninsula-St. Anthony', 'NB')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Labrador-Happy Valley-Goose Bay', 'HV')
INSERT INTO @tbl2 VALUES ( 'Newfoundland and Labrador', 'Nunatsiavut-Nain', 'NV')
INSERT INTO @tbl2 VALUES ( 'Northwest Territories', 'Fort Smith', 'FS')
INSERT INTO @tbl2 VALUES ( 'Northwest Territories', 'Inuvik', 'IN')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Annapolis', 'AP')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Antigonish', 'AG')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Cape Breton', 'CB')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Colchester', 'CO')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Cumberland', 'CU')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Digby', 'DI')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Guysborough', 'GU')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Halifax', 'HL')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Hants', 'HN')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Inverness', 'IN')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Kings', 'KI')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Lunenburg', 'LU')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Pictou', 'PI')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Queens', 'QU')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Richmond', 'RI')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Shelburne', 'SH')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Victoria', 'VI')
INSERT INTO @tbl2 VALUES ( 'Nova Scotia', 'Yarmouth', 'YA')
INSERT INTO @tbl2 VALUES ( 'Nunavut Territory', 'Baffin', 'QK')
INSERT INTO @tbl2 VALUES ( 'Nunavut Territory', 'Keewatin', 'KV')
INSERT INTO @tbl2 VALUES ( 'Nunavut Territory', 'Kitikmeot', 'KT')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Algoma', 'AL')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Brant', 'BN')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Bruce', 'BC')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Cochrane', 'CO')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Dufferin', 'DF')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Durham', 'DR')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Elgin', 'EL')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Essex', 'ES')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Frontenac', 'FR')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Grey', 'GR')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Haldimand', 'HD')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Haliburton', 'HB')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Halton', 'HT')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Hamilton-Wentworth', 'HW')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Hastings', 'HS')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Huron', 'HU')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Kenora', 'KR')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Kent', 'KT')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Lambton', 'LM')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Lanark', 'LN')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Leeds and Grenville', 'LG')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Lennox and Addington', 'LA')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Manitoulin', 'MA')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Middlesex', 'MI')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Muskoka', 'MU')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Niagara', 'NG')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Nipissing', 'NP')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Norfolk', 'NF')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Northumberland', 'NU')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Ottawa-Carleton', 'OC')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Oxford', 'OX')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Parry Sound', 'PS')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Peel', 'PL')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Perth', 'PT')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Peterborough', 'PB')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Prescott and Russell', 'PR')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Prince Edward', 'PE')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Rainy River', 'RR')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Renfrew', 'RE')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Simcoe', 'SC')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Stormont, Dundas and Glengarry', 'SD')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Sudbury', 'SB')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Thunder Bay', 'TB')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Timiskaming', 'TI')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Toronto', 'TO')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Victoria', 'VI')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Waterloo', 'WT')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'Wellington', 'WL')
INSERT INTO @tbl2 VALUES ( 'Ontario', 'York', 'YO')
INSERT INTO @tbl2 VALUES ( 'Prince Edward Island', 'Kings', 'KI')
INSERT INTO @tbl2 VALUES ( 'Prince Edward Island', 'Prince', 'PR')
INSERT INTO @tbl2 VALUES ( 'Prince Edward Island', 'Queens', 'QU')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Abitibi', 'AB')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Abitibi-Ouest', 'AO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Acton', 'AC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Antoine-Labelle', 'AL')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Argenteuil', 'AG')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Arthabaska', 'AT')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Asbestos', 'AS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Avignon', 'AV')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Beauce-Sartigan', 'BS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Beauharnois-Salaberry', 'BH')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Bécancour', 'BC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Bellechasse', 'BL')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Bonaventure', 'BO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Brome-Missisquoi', 'BM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Champlain', 'CP')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Charlevoix', 'CV')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Charlevoix-Est', 'CE')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Coaticook', 'CT')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Communauté-Urbaine-de-l''Outaouais', 'OU')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Communauté-Urbaine-de-Montréal', 'MR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Communauté-Urbaine-de-Québec', 'QU')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'D''Autray', 'DA')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Denis-Riverin', 'DR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Desjardins', 'DE')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Deux-Montagnes', 'DM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Drummond', 'DU')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Francheville', 'FR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Joliette', 'JO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Kamouraska', 'KA')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Côte-de-Beaupré', 'CB')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Côte-de-Gaspé', 'CG')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Lac-Saint-Jean-Est', 'LS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Haute-Côte-Nord', 'HC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Haute-Yamaska', 'HY')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Jacques-Cartier', 'JC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Lajemmerais', 'LJ')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Matapédia', 'MP')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'L''Amiante', 'AM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Mitis', 'MI')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Nouvelle-Beauce', 'NB')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Rivière-du-Nord', 'RD')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'L''Assomption', 'AN')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Laval', 'LV')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Vallée-de-la-Gatineau', 'VG')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'La Vallée-du-Richelieu', 'VR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Bas-Richelieu', 'BR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Centre-de-la-Mauricie', 'CM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Domaine-du-Roy', 'DD')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Fjord-du-Saguenay', 'FS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Granit', 'GR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Haut-Richelieu', 'HR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Haut-Saint-François', 'HF')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Haut-Saint-Laurent', 'HL')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Haut-Saint-Maurice', 'HM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'L''Érable', 'ER')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Basques', 'BA')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Chutes-de-la-Chaudière', 'CC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Collines-de-l''Outaouais', 'CO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Etchemins', 'ET')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Îles-de-la-Madeleine', 'IM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Jardins-de-Napierville', 'JN')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Laurentides', 'LL')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Maskoutains', 'MK')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Moulins', 'MU')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Les Pays-d''en-Haut', 'PH')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Le Val-Saint-François', 'VF')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'L''Île-d''Orléans', 'IO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'L''Islet', 'IS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Lotbinière', 'LO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Manicouagan', 'MN')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Maria-Chapdelaine', 'MC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Maskinongé', 'MS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Matane', 'MT')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Matawinie', 'MW')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Mékinac', 'ME')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Memphrémagog', 'MG')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Minganie - Basse-Côte-Nord', 'MB')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Mirabel', 'ML')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Montcalm', 'MO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Montmagny', 'MM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Nicolet-Yamaska', 'NY')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Nord-du-Québec', 'NQ')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Pabok', 'PB')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Papineau', 'PP')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Pontiac', 'PN')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Portneuf', 'PR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Rimouski-Neigette', 'RM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Rivière-du-Loup', 'RL')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Robert-Cliche', 'RC')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Roussillon', 'RS')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Rouville', 'RV')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Rouyn-Noranda', 'RN')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Sept-Rivières - Caniapiscau', 'SR')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Sherbrooke', 'SH')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Témiscamingue', 'TM')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Témiscouata', 'TT')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Thérèse-De Blainville', 'TB')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Vallée-de-l''Or', 'VO')
INSERT INTO @tbl2 VALUES ( 'Quebec', 'Vaudreuil-Soulanges', 'VS')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Estevan', 'ES')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Weyburn', 'WE')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Assiniboia', 'AS')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Maple Creek', 'MC')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Melville', 'MV')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Regina', 'RG')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Moose Jaw', 'MJ')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Swift Current', 'SC')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Yorkton', 'YT')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Wynyard', 'WY')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Saskatoon', 'SK')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Battleford', 'BF')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Kindersley', 'KD')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Melfort', 'MF')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Prince Albert', 'PA')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'North Battleford', 'NB')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'Lloydminster', 'LM')
INSERT INTO @tbl2 VALUES ( 'Saskatchewan', 'La Ronge', 'LR')
INSERT INTO @tbl2 VALUES ( 'Yukon Territory', 'Yukon', 'YT')


SET NOCOUNT OFF

INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl2	t
		LEFT JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				)

-- ======================================================================

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);


UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

-- ======================================================================


