
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Accident (right leg)';
UPDATE sewadars_details	SET	any_disability	=	'Skin Allergy'	WHERE	any_disability	=	'Allergy In Hands';
UPDATE sewadars_details	SET	any_disability	=	'Asthma'	WHERE	any_disability	=	'Asthma and Leg problem';
UPDATE sewadars_details	SET	any_disability	=	'B/L Kidney Failure'	WHERE	any_disability	=	'B/L kidney failure';
UPDATE sewadars_details	SET	any_disability	=	'Breathlessness'	WHERE	any_disability	=	'Breathing';
UPDATE sewadars_details	SET	any_disability	=	'Breathlessness'	WHERE	any_disability	=	'Breathing difficulty';
UPDATE sewadars_details	SET	any_disability	=	'Loss of Speech- Paralysis'	WHERE	any_disability	=	'Cant Talk-Paralysis';
UPDATE sewadars_details	SET	any_disability	=	'Kidney Problem'	WHERE	any_disability	=	'Cardiac/Kidney Problem';
UPDATE sewadars_details	SET	any_disability	=	'Cervical Spondylosis'	WHERE	any_disability	=	'Cervical ';
UPDATE sewadars_details	SET	any_disability	=	'Deaf, Dumb'	WHERE	any_disability	=	'Deaf  Mute';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Disability in right hand';
UPDATE sewadars_details	SET	any_disability	=	'Deaf, Dumb'	WHERE	any_disability	=	'Dumb and deaf';
UPDATE sewadars_details	SET	any_disability	=	'Allergy'	WHERE	any_disability	=	'Dust Allergy';
UPDATE sewadars_details	SET	any_disability	=	'Ear Disorder'	WHERE	any_disability	=	'Ear Problem';
UPDATE sewadars_details	SET	any_disability	=	'Foot Drop'	WHERE	any_disability	=	'Foot Drop in Right Leg';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Hand/ Leg)'	WHERE	any_disability	=	'HAND / LEG  POLIO';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Handicap';
UPDATE sewadars_details	SET	any_disability	=	'Amputation (Left Arm)'	WHERE	any_disability	=	'Handicap (Left arm amputated)';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap (Leg)'	WHERE	any_disability	=	'Handicap - Leg';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap (Leg)'	WHERE	any_disability	=	'Handicap- Leg';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Handicapped';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap (Hand)'	WHERE	any_disability	=	'Handicapped By Right Hand';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Handicapped Person';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hard of Hearing';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hearing';
UPDATE sewadars_details	SET	any_disability	=	'Deaf, Dumb'	WHERE	any_disability	=	'Hearing & Speech';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hearing Aid';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hearing Deficit';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hearing Difficulty';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hearing disability';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Hearing problem';
UPDATE sewadars_details	SET	any_disability	=	'Paralytic'	WHERE	any_disability	=	'Heart Patient, Paralytic';
UPDATE sewadars_details	SET	any_disability	=	'Knee Joint Disorder'	WHERE	any_disability	=	'Knee Problem';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'LOW HEARING';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Minor Disability(Left hand & l';
UPDATE sewadars_details	SET	any_disability	=	'Artificial Leg'	WHERE	any_disability	=	'One artificial leg (Handicap)';
UPDATE sewadars_details	SET	any_disability	=	'One Eye'	WHERE	any_disability	=	'One Eyed';
UPDATE sewadars_details	SET	any_disability	=	'Amputation (Hand)'	WHERE	any_disability	=	'One hand Amputed';
UPDATE sewadars_details	SET	any_disability	=	'One Eye'	WHERE	any_disability	=	'One-eyed';
UPDATE sewadars_details	SET	any_disability	=	'Paralytic'	WHERE	any_disability	=	'Paralysis';
UPDATE sewadars_details	SET	any_disability	=	'Paralytic'	WHERE	any_disability	=	'Paralysis Attack';
UPDATE sewadars_details	SET	any_disability	=	'Paralytic'	WHERE	any_disability	=	'Paralytic (Right Side)';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap (Leg)'	WHERE	any_disability	=	'Physical (Left leg)';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Physical Handicap';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Physically Handicapped';
UPDATE sewadars_details	SET	any_disability	=	'Physical Handicap'	WHERE	any_disability	=	'Physically Handicapped (Knee P';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Foot)'	WHERE	any_disability	=	'Polio - Right Foot';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Leg)'	WHERE	any_disability	=	'Polio Left Leg';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Leg)'	WHERE	any_disability	=	'Polio Right Leg';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Hand)'	WHERE	any_disability	=	'Right hand deformity (polio)';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Hand)'	WHERE	any_disability	=	'Right Hand Problem';
UPDATE sewadars_details	SET	any_disability	=	'Polio (Leg)'	WHERE	any_disability	=	'Right Leg Problem';
UPDATE sewadars_details	SET	any_disability	=	'Rod in Leg'	WHERE	any_disability	=	'Rod in Left Leg';
UPDATE sewadars_details	SET	any_disability	=	'Rod in Arm'	WHERE	any_disability	=	'Rod in Right Hand';
UPDATE sewadars_details	SET	any_disability	=	'Rod in Leg'	WHERE	any_disability	=	'Rod in Right Leg';
UPDATE sewadars_details	SET	any_disability	=	'Hearing Impairment'	WHERE	any_disability	=	'Short of hearing';
UPDATE sewadars_details	SET	any_disability	=	'Spondylitis'	WHERE	any_disability	=	'Spondylosis';
UPDATE sewadars_details	SET	any_disability	=	'Thyroid'	WHERE	any_disability	=	'Thyroid and Heart Problem';
UPDATE sewadars_details	SET	any_disability	=	'Thyroid'	WHERE	any_disability	=	'Thyroid Problem';
UPDATE sewadars_details	SET	any_disability	=	'Thyroid'	WHERE	any_disability	=	'Thyroid Psoarasis Osteoporosis';
UPDATE sewadars_details	SET	any_disability	=	'Thyroid, Allergy'	WHERE	any_disability	=	'Thyroid, Allergy';
UPDATE sewadars_details	SET	any_disability	=	'Varicose Veins'	WHERE	any_disability	=	'Varicose Veins';

