/* ==================================================================================
    Source File		:	setup_australia_components.sql
	Author(s)		:	Jitendra Loyal
	Started On		:	Fri Sep 12 13:33 2014
	Module ID		:	CDB
	Last updated	:	Sep 12, 2014
	==================================================================================
																		   Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of Australia are set-up
	==================================================================================
																	  Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'Australia';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('Country Australia not found', 16, 1);
	RETURN;
END

-- ======================================================================

INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Ashmore and Cartier Islands',	'AS'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Australian Capital Territory',	'AC'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Coral Sea Islands Territory',	'CR'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Jervis Bay Territory',			'JB'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'New South Wales',				'NS'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Northern Territory',			'NT'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Queensland',					'QL'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'South Australia',				'SA'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Tasmania',						'TS'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Victoria',						'VI'	)
INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) VALUES ( @country_id,	'Western Australia',			'WA'	)
-- ======================================================================

DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl VALUES ( 'Ashmore and Cartier Islands', 'Ashmore and Cartier Islands', 'AS')
INSERT INTO @tbl VALUES ( 'Australian Capital Territory', 'Australian Capital Territory', 'AC')
INSERT INTO @tbl VALUES ( 'Coral Sea Islands Territory', 'Coral Sea Islands Territory', 'CR')
INSERT INTO @tbl VALUES ( 'Jervis Bay Territory', 'Jervis Bay Territory', 'JB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Albury', 'AL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Armidale Dumaresq', 'AD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Ashfield', 'AS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Auburn', 'AU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Ballina', 'BA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Balranald', 'BN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bankstown', 'BS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Barraba', 'BZ')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bathurst', 'BT')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Baulkham Hills', 'BK')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bega Valley', 'BV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bellingen', 'BE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Berrigan', 'BG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bingara', 'BI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Blacktown', 'BC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bland', 'BD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Blayney', 'BL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Blue Mountains', 'BM')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bogan', 'BX')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bombala', 'BO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Boorowa', 'BW')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Botany Bay', 'BB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Bourke', 'BQ')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Brewarrina', 'BR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Broken Hill', 'BH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Burwood', 'BU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Byron', 'BY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Cabonne', 'CE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Camden', 'CN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Campbelltown', 'CT')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Canada Bay', 'CC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Canterbury', 'CA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Carrathool', 'CH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Central Darling', 'CD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Cessnock', 'CS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Cobar', 'CR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Coffs Harbour', 'CF')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Conargo', 'CG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Coolah', 'CL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Coolamon', 'CO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Cooma-Monaro', 'CM')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Coonabarabran', 'CB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Coonamble', 'CJ')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Cootamundra', 'CQ')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Copmanhurst', 'CP')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Corowa', 'CV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Cowra', 'CW')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Crookwell', 'CK')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Culcairn', 'CU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Deniliquin', 'DE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Dubbo', 'DB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Dungog', 'DG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Eurobodalla', 'EU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Evans', 'EV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Fairfield', 'FA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Forbes', 'FO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Gilgandra', 'GG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Glen Innes', 'GI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Gloucester', 'GC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Gosford', 'GF')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Goulburn', 'GB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Grafton', 'GR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Great Lakes', 'GL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Greater Taree', 'GT')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Griffith', 'GH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Gundagai', 'GU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Gunnedah', 'GD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Gunning', 'GN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Guyra', 'GY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Harden', 'HD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hastings', 'HA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hawkesbury', 'HW')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hay', 'HY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Holbrook', 'HB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Holroyd', 'HO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hornsby', 'HR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hume', 'HM')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hunters Hill', 'HH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Hurstville', 'HV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Inverell', 'IN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Jerilderie', 'JE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Junee', 'JU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Kempsey', 'KE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Kiama', 'KI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Kogarah', 'KO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Ku-ring-gai', 'KU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Kyogle', 'KY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Lachlan', 'LA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Lake Macquarie', 'LM')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Lane Cove', 'LC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Leeton', 'LE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Leichhardt', 'LH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Lismore', 'LI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Lithgow', 'LG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Liverpool', 'LV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Lockhart', 'LO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Maclean', 'MC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Maitland', 'MD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Manilla', 'MA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Manly', 'MN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Marrickville', 'MV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Merriwa', 'ME')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Moree Plains', 'MP')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Mosman', 'MO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Mudgee', 'MG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Mulwaree', 'ML')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Murray', 'MU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Murrumbidgee', 'MB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Murrurundi', 'MR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Muswellbrook', 'MS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Nambucca', 'NC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Narrabri', 'NB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Narrandera', 'ND')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Narromine', 'NA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Newcastle', 'NE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'North Sydney', 'NS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Nundle', 'NU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Oberon', 'OB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Orange', 'OR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Parkes', 'PK')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Parramatta', 'PA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Parry', 'PY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Penrith', 'PE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Pittwater', 'PI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Port Stephens', 'PS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Pristine Waters', 'PW')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Queanbeyan', 'QB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Quirindi', 'QR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Randwick', 'RA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Richmond Valley', 'RV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Rockdale', 'RO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Ryde', 'RD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Rylstone', 'RY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Scone', 'SC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Severn', 'SE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Shellharbour', 'SH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Shoalhaven', 'SL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Singleton', 'SI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Snowy River', 'SR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'South Sydney', 'SS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Strathfield', 'ST')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Sutherland', 'SU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Sydney', 'SY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Tallaganda', 'TL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Tamworth', 'TA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Temora', 'TE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Tenterfield', 'TN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Tumbarumba', 'TU')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Tumut', 'TT')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Tweed', 'TW')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Uralla', 'UR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Urana', 'UN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wagga Wagga', 'WW')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wakool', 'WK')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Walcha', 'WH')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Walgett', 'WA')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Warren', 'WN')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Warringah', 'WR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Waverley', 'WV')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Weddin', 'WD')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wellington', 'WT')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wentworth', 'WE')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Willoughby', 'WB')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Windouran', 'WI')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wingecarribee', 'WC')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wollondilly', 'WL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wollongong', 'WG')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Woollahra', 'WO')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Wyong', 'WY')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Yallaroi', 'YL')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Yarrowlumla', 'YR')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Yass', 'YS')
INSERT INTO @tbl VALUES ( 'New South Wales', 'Young', 'YO')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Alice Springs', 'AS')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Alpurrurulam', 'AL')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Angurugu', 'AN')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Anmatjere', 'AM')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Arltarlpilta', 'AR')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Barunga Manyallaluk', 'BA')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Belyuen', 'BE')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Binjari', 'BI')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Borroloola', 'BO')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Coomalie', 'CO')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Cox Peninsula', 'CP')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Daguragu', 'DG')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Darwin', 'DR')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Elliott District', 'EL')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Jabiru', 'JA')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Jilkminggan', 'JI')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Katherine', 'KA')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Kunbarllanjnja', 'KU')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Lajamanu', 'LA')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Litchfield', 'LI')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Ltyentye Purte', 'LT')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Marngarr', 'MG')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Mataranka', 'MT')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Milikapiti', 'MI')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Nauiyu Nambiyu', 'NN')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Nguiu', 'NG')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Numbulwar/Numburindi', 'NU')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Palmerston', 'PA')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Pine Creek', 'PC')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Pirlangimpi', 'PI')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Tapatijatjaka', 'TP')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Tennant Creek', 'TC')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Timber Creek', 'TM')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Walingeri-Ngumpinku', 'WN')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Wallace Rockhole', 'WR')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Watiyawanu', 'WA')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Wugularr', 'WU')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Yuendumu', 'YU')
INSERT INTO @tbl VALUES ( 'Northern Territory', 'Yugal Mangi', 'YM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Aramac', 'AR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Atherton', 'AT')
INSERT INTO @tbl VALUES ( 'Queensland', 'Aurukun', 'AU')
INSERT INTO @tbl VALUES ( 'Queensland', 'Balonne', 'BA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Banana', 'BN')
INSERT INTO @tbl VALUES ( 'Queensland', 'Barcaldine', 'BC')
INSERT INTO @tbl VALUES ( 'Queensland', 'Barcoo', 'BQ')
INSERT INTO @tbl VALUES ( 'Queensland', 'Bauhinia', 'BH')
INSERT INTO @tbl VALUES ( 'Queensland', 'Beaudesert', 'BE')
INSERT INTO @tbl VALUES ( 'Queensland', 'Belyando', 'BY')
INSERT INTO @tbl VALUES ( 'Queensland', 'Bendemere', 'BM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Biggenden', 'BI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Blackall', 'BL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Boonah', 'BF')
INSERT INTO @tbl VALUES ( 'Queensland', 'Booringa', 'BG')
INSERT INTO @tbl VALUES ( 'Queensland', 'Boulia', 'BO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Bowen', 'BW')
INSERT INTO @tbl VALUES ( 'Queensland', 'Brisbane', 'BR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Broadsound', 'BS')
INSERT INTO @tbl VALUES ( 'Queensland', 'Bulloo', 'BU')
INSERT INTO @tbl VALUES ( 'Queensland', 'Bundaberg', 'BB')
INSERT INTO @tbl VALUES ( 'Queensland', 'Bungil', 'BJ')
INSERT INTO @tbl VALUES ( 'Queensland', 'Burdekin', 'BD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Burke', 'BK')
INSERT INTO @tbl VALUES ( 'Queensland', 'Burnett', 'BT')
INSERT INTO @tbl VALUES ( 'Queensland', 'Caboolture', 'CB')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cairns', 'CS')
INSERT INTO @tbl VALUES ( 'Queensland', 'Calliope', 'CP')
INSERT INTO @tbl VALUES ( 'Queensland', 'Caloundra', 'CD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cambooya', 'CY')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cardwell', 'CW')
INSERT INTO @tbl VALUES ( 'Queensland', 'Carpentaria', 'CA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Charters Towers', 'CT')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cherbourg', 'CG')
INSERT INTO @tbl VALUES ( 'Queensland', 'Chinchilla', 'CH')
INSERT INTO @tbl VALUES ( 'Queensland', 'Clifton', 'CF')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cloncurry', 'CL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cook', 'CK')
INSERT INTO @tbl VALUES ( 'Queensland', 'Cooloola', 'CO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Crow''s Nest', 'CN')
INSERT INTO @tbl VALUES ( 'Queensland', 'Croydon', 'CR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Dalby', 'DB')
INSERT INTO @tbl VALUES ( 'Queensland', 'Dalrymple', 'DR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Diamantina', 'DI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Doomadgee', 'DM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Douglas', 'DG')
INSERT INTO @tbl VALUES ( 'Queensland', 'Duaringa', 'DU')
INSERT INTO @tbl VALUES ( 'Queensland', 'Eacham', 'EA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Eidsvold', 'EI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Emerald', 'EM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Esk', 'ES')
INSERT INTO @tbl VALUES ( 'Queensland', 'Etheridge', 'ET')
INSERT INTO @tbl VALUES ( 'Queensland', 'Fitzroy', 'FI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Flinders', 'FL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Gatton', 'GT')
INSERT INTO @tbl VALUES ( 'Queensland', 'Gayndah', 'GD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Gladstone', 'GL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Gold Coast', 'GC')
INSERT INTO @tbl VALUES ( 'Queensland', 'Goondiwindi', 'GO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Herberton', 'HE')
INSERT INTO @tbl VALUES ( 'Queensland', 'Hervey Bay', 'HB')
INSERT INTO @tbl VALUES ( 'Queensland', 'Hinchinbrook', 'HI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Hopevale', 'HO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Ilfracombe', 'IL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Inglewood', 'IN')
INSERT INTO @tbl VALUES ( 'Queensland', 'Ipswich', 'IP')
INSERT INTO @tbl VALUES ( 'Queensland', 'Isis', 'IS')
INSERT INTO @tbl VALUES ( 'Queensland', 'Isisford', 'IF')
INSERT INTO @tbl VALUES ( 'Queensland', 'Jericho', 'JE')
INSERT INTO @tbl VALUES ( 'Queensland', 'Johnstone', 'JS')
INSERT INTO @tbl VALUES ( 'Queensland', 'Jondaryan', 'JD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Kilcoy', 'KC')
INSERT INTO @tbl VALUES ( 'Queensland', 'Kilkivan', 'KK')
INSERT INTO @tbl VALUES ( 'Queensland', 'Kingaroy', 'KI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Kolan', 'KL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Kowanyama', 'KW')
INSERT INTO @tbl VALUES ( 'Queensland', 'Laidley', 'LA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Livingstone', 'LI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Logan', 'LG')
INSERT INTO @tbl VALUES ( 'Queensland', 'Longreach', 'LR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mackay', 'MK')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mareeba', 'ME')
INSERT INTO @tbl VALUES ( 'Queensland', 'Maroochy', 'MY')
INSERT INTO @tbl VALUES ( 'Queensland', 'Maryborough', 'MA')
INSERT INTO @tbl VALUES ( 'Queensland', 'McKinlay', 'MC')
INSERT INTO @tbl VALUES ( 'Queensland', 'Millmerran', 'ML')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mirani', 'MR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Miriam Vale', 'MV')
INSERT INTO @tbl VALUES ( 'Queensland', 'Monto', 'MN')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mornington', 'MO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mount Isa', 'MI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mount Morgan', 'MM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Mundubbera', 'MD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Murgon', 'MG')
INSERT INTO @tbl VALUES ( 'Queensland', 'Murilla', 'MU')
INSERT INTO @tbl VALUES ( 'Queensland', 'Murweh', 'MW')
INSERT INTO @tbl VALUES ( 'Queensland', 'Nanango', 'NA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Nebo', 'NE')
INSERT INTO @tbl VALUES ( 'Queensland', 'Noosa', 'NO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Paroo', 'PA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Peak Downs', 'PD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Perry', 'PE')
INSERT INTO @tbl VALUES ( 'Queensland', 'Pine Rivers', 'PR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Pittsworth', 'PI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Pormpuraaw', 'PO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Quilpie', 'QP')
INSERT INTO @tbl VALUES ( 'Queensland', 'Redcliffe', 'RC')
INSERT INTO @tbl VALUES ( 'Queensland', 'Redland', 'RL')
INSERT INTO @tbl VALUES ( 'Queensland', 'Richmond', 'RI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Rockhampton', 'RH')
INSERT INTO @tbl VALUES ( 'Queensland', 'Roma', 'RM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Rosalie', 'RS')
INSERT INTO @tbl VALUES ( 'Queensland', 'Sarina', 'SA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Stanthorpe', 'ST')
INSERT INTO @tbl VALUES ( 'Queensland', 'Tambo', 'TA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Tara', 'TR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Taroom', 'TM')
INSERT INTO @tbl VALUES ( 'Queensland', 'Thuringowa', 'TH')
INSERT INTO @tbl VALUES ( 'Queensland', 'Tiaro', 'TI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Toowoomba', 'TW')
INSERT INTO @tbl VALUES ( 'Queensland', 'Torres', 'TO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Townsville', 'TV')
INSERT INTO @tbl VALUES ( 'Queensland', 'Waggamba', 'WG')
INSERT INTO @tbl VALUES ( 'Queensland', 'Wambo', 'WB')
INSERT INTO @tbl VALUES ( 'Queensland', 'Warroo', 'WR')
INSERT INTO @tbl VALUES ( 'Queensland', 'Warwick', 'WA')
INSERT INTO @tbl VALUES ( 'Queensland', 'Weipa South', 'WS')
INSERT INTO @tbl VALUES ( 'Queensland', 'Whitsunday', 'WH')
INSERT INTO @tbl VALUES ( 'Queensland', 'Winton', 'WI')
INSERT INTO @tbl VALUES ( 'Queensland', 'Wondai', 'WD')
INSERT INTO @tbl VALUES ( 'Queensland', 'Woocoo', 'WC')
INSERT INTO @tbl VALUES ( 'Queensland', 'Woorabinda', 'WO')
INSERT INTO @tbl VALUES ( 'Queensland', 'Wujal Wujal', 'WW')
INSERT INTO @tbl VALUES ( 'Queensland', 'Yarrabah', 'YA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Adelaide', 'AD')
INSERT INTO @tbl VALUES ( 'South Australia', 'Adelaide Hills', 'AH')
INSERT INTO @tbl VALUES ( 'South Australia', 'Alexandrina', 'AL')
INSERT INTO @tbl VALUES ( 'South Australia', 'Barossa', 'BA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Barunga West', 'BW')
INSERT INTO @tbl VALUES ( 'South Australia', 'Berri and Barmera', 'BB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Burnside', 'BU')
INSERT INTO @tbl VALUES ( 'South Australia', 'Campbelltown', 'CA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Ceduna', 'CE')
INSERT INTO @tbl VALUES ( 'South Australia', 'Charles Sturt', 'CS')
INSERT INTO @tbl VALUES ( 'South Australia', 'Clare and Gilbert Valleys', 'CG')
INSERT INTO @tbl VALUES ( 'South Australia', 'Cleve', 'CL')
INSERT INTO @tbl VALUES ( 'South Australia', 'Coober Pedy', 'CP')
INSERT INTO @tbl VALUES ( 'South Australia', 'Coorong', 'CO')
INSERT INTO @tbl VALUES ( 'South Australia', 'Copper Coast', 'CC')
INSERT INTO @tbl VALUES ( 'South Australia', 'Elliston', 'EL')
INSERT INTO @tbl VALUES ( 'South Australia', 'Flinders Ranges', 'FR')
INSERT INTO @tbl VALUES ( 'South Australia', 'Franklin Harbour', 'FH')
INSERT INTO @tbl VALUES ( 'South Australia', 'Gawler', 'GA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Goyder', 'GO')
INSERT INTO @tbl VALUES ( 'South Australia', 'Grant', 'GR')
INSERT INTO @tbl VALUES ( 'South Australia', 'Holdfast Bay', 'HB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Kangaroo Island', 'KI')
INSERT INTO @tbl VALUES ( 'South Australia', 'Karoonda-East Murray', 'KE')
INSERT INTO @tbl VALUES ( 'South Australia', 'Kimba', 'KB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Lacepede', 'LA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Le Hunte', 'LH')
INSERT INTO @tbl VALUES ( 'South Australia', 'Light', 'LI')
INSERT INTO @tbl VALUES ( 'South Australia', 'Lower Eyre Peninsula', 'LE')
INSERT INTO @tbl VALUES ( 'South Australia', 'Loxton Waikerie', 'LW')
INSERT INTO @tbl VALUES ( 'South Australia', 'Mallala', 'ML')
INSERT INTO @tbl VALUES ( 'South Australia', 'Marion', 'MA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Mid Murray', 'MM')
INSERT INTO @tbl VALUES ( 'South Australia', 'Mitcham', 'MI')
INSERT INTO @tbl VALUES ( 'South Australia', 'Mount Barker', 'MB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Mount Gambier', 'MG')
INSERT INTO @tbl VALUES ( 'South Australia', 'Mount Remarkable', 'MR')
INSERT INTO @tbl VALUES ( 'South Australia', 'Murray Bridge', 'MU')
INSERT INTO @tbl VALUES ( 'South Australia', 'Naracoorte Lucindale', 'NL')
INSERT INTO @tbl VALUES ( 'South Australia', 'Northern Areas', 'NA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Norwood Payneham and Saint Peters', 'NP')
INSERT INTO @tbl VALUES ( 'South Australia', 'Onkaparinga', 'ON')
INSERT INTO @tbl VALUES ( 'South Australia', 'Orroroo/Carrieton', 'OC')
INSERT INTO @tbl VALUES ( 'South Australia', 'Outback Areas', 'OA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Peterborough', 'PB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Playford', 'PF')
INSERT INTO @tbl VALUES ( 'South Australia', 'Port Adelaide Enfield', 'PE')
INSERT INTO @tbl VALUES ( 'South Australia', 'Port Augusta', 'PA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Port Lincoln', 'PL')
INSERT INTO @tbl VALUES ( 'South Australia', 'Port Pirie', 'PP')
INSERT INTO @tbl VALUES ( 'South Australia', 'Prospect', 'PR')
INSERT INTO @tbl VALUES ( 'South Australia', 'Renmark Paringa', 'RP')
INSERT INTO @tbl VALUES ( 'South Australia', 'Robe', 'RO')
INSERT INTO @tbl VALUES ( 'South Australia', 'Roxby Downs', 'RD')
INSERT INTO @tbl VALUES ( 'South Australia', 'Salisbury', 'SA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Southern Mallee', 'SM')
INSERT INTO @tbl VALUES ( 'South Australia', 'Streaky Bay', 'SB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Tatiara', 'TA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Tea Tree Gully', 'TT')
INSERT INTO @tbl VALUES ( 'South Australia', 'Tumby Bay', 'TB')
INSERT INTO @tbl VALUES ( 'South Australia', 'Unley', 'UN')
INSERT INTO @tbl VALUES ( 'South Australia', 'Victor Harbor', 'VH')
INSERT INTO @tbl VALUES ( 'South Australia', 'Wakefield', 'WF')
INSERT INTO @tbl VALUES ( 'South Australia', 'Walkerville', 'WV')
INSERT INTO @tbl VALUES ( 'South Australia', 'Wattle Range', 'WR')
INSERT INTO @tbl VALUES ( 'South Australia', 'West Torrens Thebarton', 'WT')
INSERT INTO @tbl VALUES ( 'South Australia', 'Whyalla', 'WH')
INSERT INTO @tbl VALUES ( 'South Australia', 'Yankalilla', 'YA')
INSERT INTO @tbl VALUES ( 'South Australia', 'Yorke Peninsula', 'YP')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Break O''Day', 'BO')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Brighton', 'BR')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Burnie', 'BU')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Central Coast', 'CC')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Central Highlands', 'CH')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Circular Head', 'CI')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Clarence', 'CL')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Derwent Valley', 'DV')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Devonport', 'DE')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Dorset', 'DO')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Flinders', 'FL')
INSERT INTO @tbl VALUES ( 'Tasmania', 'George Town', 'GT')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Glamorgan-Spring Bay', 'GS')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Glenorchy', 'GL')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Hobart', 'HO')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Huon Valley', 'HV')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Kentish', 'KE')
INSERT INTO @tbl VALUES ( 'Tasmania', 'King Island', 'KI')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Kingborough', 'KB')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Latrobe', 'LT')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Launceston', 'LC')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Meander Valley', 'MV')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Northern Midlands', 'NM')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Sorell', 'SO')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Southern Midlands', 'SM')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Tasman', 'TA')
INSERT INTO @tbl VALUES ( 'Tasmania', 'Waratah-Wynyard', 'WW')
INSERT INTO @tbl VALUES ( 'Tasmania', 'West Coast', 'WC')
INSERT INTO @tbl VALUES ( 'Tasmania', 'West Tamar', 'WT')
INSERT INTO @tbl VALUES ( 'Victoria', 'Alpine', 'AL')
INSERT INTO @tbl VALUES ( 'Victoria', 'Ararat', 'AR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Ballarat', 'BA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Banyule', 'BY')
INSERT INTO @tbl VALUES ( 'Victoria', 'Bass Coast', 'BC')
INSERT INTO @tbl VALUES ( 'Victoria', 'Baw Baw', 'BB')
INSERT INTO @tbl VALUES ( 'Victoria', 'Bayside', 'BS')
INSERT INTO @tbl VALUES ( 'Victoria', 'Boroondara', 'BO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Brimbank', 'BR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Buloke', 'BU')
INSERT INTO @tbl VALUES ( 'Victoria', 'Campaspe', 'CP')
INSERT INTO @tbl VALUES ( 'Victoria', 'Cardinia', 'CA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Casey', 'CS')
INSERT INTO @tbl VALUES ( 'Victoria', 'Central Goldfields', 'CG')
INSERT INTO @tbl VALUES ( 'Victoria', 'Colac-Otway', 'CO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Corangamite', 'CR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Darebin', 'DA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Delatite', 'DE')
INSERT INTO @tbl VALUES ( 'Victoria', 'East Gippsland', 'EG')
INSERT INTO @tbl VALUES ( 'Victoria', 'Frankston', 'FR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Gannawarra', 'GA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Glen Eira', 'GE')
INSERT INTO @tbl VALUES ( 'Victoria', 'Glenelg', 'GL')
INSERT INTO @tbl VALUES ( 'Victoria', 'Golden Plains', 'GP')
INSERT INTO @tbl VALUES ( 'Victoria', 'Greater Bendigo', 'GB')
INSERT INTO @tbl VALUES ( 'Victoria', 'Greater Dandenong', 'GD')
INSERT INTO @tbl VALUES ( 'Victoria', 'Greater Geelong', 'GG')
INSERT INTO @tbl VALUES ( 'Victoria', 'Greater Shepparton', 'GS')
INSERT INTO @tbl VALUES ( 'Victoria', 'Hepburn', 'HE')
INSERT INTO @tbl VALUES ( 'Victoria', 'Hindmarsh', 'HI')
INSERT INTO @tbl VALUES ( 'Victoria', 'Hobsons Bay', 'HB')
INSERT INTO @tbl VALUES ( 'Victoria', 'Horsham', 'HO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Hume', 'HU')
INSERT INTO @tbl VALUES ( 'Victoria', 'Indigo', 'IN')
INSERT INTO @tbl VALUES ( 'Victoria', 'Kingston', 'KI')
INSERT INTO @tbl VALUES ( 'Victoria', 'Knox', 'KN')
INSERT INTO @tbl VALUES ( 'Victoria', 'Latrobe', 'LA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Loddon', 'LO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Macedon Ranges', 'MR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Manningham', 'MN')
INSERT INTO @tbl VALUES ( 'Victoria', 'Maribyrnong', 'MB')
INSERT INTO @tbl VALUES ( 'Victoria', 'Maroondah', 'MH')
INSERT INTO @tbl VALUES ( 'Victoria', 'Melbourne', 'ME')
INSERT INTO @tbl VALUES ( 'Victoria', 'Melton', 'MT')
INSERT INTO @tbl VALUES ( 'Victoria', 'Mildura', 'ML')
INSERT INTO @tbl VALUES ( 'Victoria', 'Mitchell', 'MC')
INSERT INTO @tbl VALUES ( 'Victoria', 'Moira', 'MI')
INSERT INTO @tbl VALUES ( 'Victoria', 'Monash', 'MS')
INSERT INTO @tbl VALUES ( 'Victoria', 'Moonee Valley', 'MV')
INSERT INTO @tbl VALUES ( 'Victoria', 'Moorabool', 'MO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Moreland', 'MD')
INSERT INTO @tbl VALUES ( 'Victoria', 'Mornington Peninsula', 'MP')
INSERT INTO @tbl VALUES ( 'Victoria', 'Mount Alexander', 'MA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Moyne', 'MY')
INSERT INTO @tbl VALUES ( 'Victoria', 'Murrindindi', 'MU')
INSERT INTO @tbl VALUES ( 'Victoria', 'Nillumbik', 'NI')
INSERT INTO @tbl VALUES ( 'Victoria', 'Northern Grampians', 'NG')
INSERT INTO @tbl VALUES ( 'Victoria', 'Port Phillip', 'PP')
INSERT INTO @tbl VALUES ( 'Victoria', 'Pyrenees', 'PY')
INSERT INTO @tbl VALUES ( 'Victoria', 'Queenscliffe', 'QC')
INSERT INTO @tbl VALUES ( 'Victoria', 'South Gippsland', 'SL')
INSERT INTO @tbl VALUES ( 'Victoria', 'Southern Grampians', 'SG')
INSERT INTO @tbl VALUES ( 'Victoria', 'Stonnington', 'SN')
INSERT INTO @tbl VALUES ( 'Victoria', 'Strathbogie', 'SB')
INSERT INTO @tbl VALUES ( 'Victoria', 'Surf Coast', 'SC')
INSERT INTO @tbl VALUES ( 'Victoria', 'Swan Hill', 'SH')
INSERT INTO @tbl VALUES ( 'Victoria', 'Towong', 'TO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Wangaratta', 'WG')
INSERT INTO @tbl VALUES ( 'Victoria', 'Warrnambool', 'WR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Wellington', 'WE')
INSERT INTO @tbl VALUES ( 'Victoria', 'West Wimmera', 'WW')
INSERT INTO @tbl VALUES ( 'Victoria', 'Whitehorse', 'WH')
INSERT INTO @tbl VALUES ( 'Victoria', 'Whittlesea', 'WS')
INSERT INTO @tbl VALUES ( 'Victoria', 'Wodonga', 'WO')
INSERT INTO @tbl VALUES ( 'Victoria', 'Wyndham', 'WY')
INSERT INTO @tbl VALUES ( 'Victoria', 'Yarra', 'YA')
INSERT INTO @tbl VALUES ( 'Victoria', 'Yarra Ranges', 'YR')
INSERT INTO @tbl VALUES ( 'Victoria', 'Yarriambiack', 'YB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Albany', 'AL')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Armadale', 'AR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Ashburton', 'AS')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Augusta-Margaret River', 'AM')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Bassendean', 'BA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Bayswater', 'BW')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Belmont', 'BE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Beverley', 'BV')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Boddington', 'BO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Boyup Brook', 'BB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Bridgetown-Greenbushes', 'BG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Brookton', 'BK')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Broome', 'BM')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Broomehill', 'BH')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Bruce Rock', 'BR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Bunbury', 'BU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Busselton', 'BS')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cambridge', 'CG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Canning', 'CN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Capel', 'CP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Carnamah', 'CM')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Carnarvon', 'CA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Chapman Valley', 'CV')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Chittering', 'CH')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Claremont', 'CL')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cockburn', 'CK')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Collie', 'CE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Coolgardie', 'CO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Coorow', 'CW')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Corrigin', 'CI')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cottesloe', 'CT')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cranbrook', 'CR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cuballing', 'CB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cue', 'CU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Cunderdin', 'CD')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Dalwallinu', 'DL')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Dandaragan', 'DN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Dardanup', 'DP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Denmark', 'DE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Derby-West Kimberley', 'DW')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Donnybrook-Balingup', 'DB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Dowerin', 'DO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Dumbleyung', 'DY')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Dundas', 'DU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'East Fremantle', 'EF')
INSERT INTO @tbl VALUES ( 'Western Australia', 'East Pilbara', 'EP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Esperance', 'ES')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Exmouth', 'EX')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Fremantle', 'FR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Geraldton', 'GE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Gingin', 'GI')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Gnowangerup', 'GN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Goomalling', 'GM')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Gosnells', 'GS')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Greenough', 'GR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Halls Creek', 'HC')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Harvey', 'HA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Irwin', 'IR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Jerramungup', 'JE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Joondalup', 'JO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kalamunda', 'KL')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kalgoorlie/Boulder', 'KB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Katanning', 'KT')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kellerberrin', 'KE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kent', 'KN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kojonup', 'KJ')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kondinin', 'KO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Koorda', 'KR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kulin', 'KU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Kwinana', 'KW')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Lake Grace', 'LG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Laverton', 'LA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Leonora', 'LE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mandurah', 'MA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Manjimup', 'MJ')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Meekatharra', 'MT')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Melville', 'MV')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Menzies', 'MZ')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Merredin', 'ME')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mingenew', 'MI')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Moora', 'MR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Morawa', 'MO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mosman Park', 'MP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mount Magnet', 'MG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mount Marshall', 'MM')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mukinbudin', 'MB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mullewa', 'MW')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Mundaring', 'MN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Murchison', 'MU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Murray', 'MY')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Nannup', 'NN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Narembeen', 'NB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Narrogin', 'NS')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Narrogin Town', 'NT')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Nedlands', 'NE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Ngaanyatjarraku', 'NG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Northam Town', 'NH')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Northam', 'NR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Northampton', 'NP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Nungarin', 'NU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Peppermint Grove', 'PG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Perenjori', 'PJ')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Perth', 'PE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Pingelly', 'PI')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Plantagenet', 'PL')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Port Hedland', 'PO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Quairading', 'QR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Ravensthorpe', 'RA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Rockingham', 'RC')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Roebourne', 'RB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Sandstone', 'SA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Serpentine-Jarrahdale', 'SJ')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Shark Bay', 'SB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'South Perth', 'SP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Stirling', 'ST')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Subiaco', 'SU')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Swan', 'SW')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Tambellup', 'TB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Tammin', 'TM')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Three Springs', 'TS')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Toodyay', 'TO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Trayning', 'TR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Upper Gascoyne', 'UG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Victoria Park', 'VK')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Victoria Plains', 'VP')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Vincent', 'VI')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wagin', 'WG')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wandering', 'WD')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wanneroo', 'WR')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Waroona', 'WO')
INSERT INTO @tbl VALUES ( 'Western Australia', 'West Arthur', 'WA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Westonia', 'WT')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wickepin', 'WC')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Williams', 'WS')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wiluna', 'WL')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wongan-Ballidu', 'WB')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Woodanilling', 'WN')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wyalkatchem', 'WY')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Wyndham-East Kimberley', 'WE')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Yalgoo', 'YA')
INSERT INTO @tbl VALUES ( 'Western Australia', 'Yilgarn', 'YI')
INSERT INTO @tbl VALUES ( 'Western Australia', 'York', 'YO')

INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl	t
		JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm	);

-- ======================================================================


UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);

-- ======================================================================


