/* ==================================================================================
    Source File		:	setup_uk_components.sql
	Author(s)		:	Jitendra Loyal
	Started On		:	Fri Sep 12 15:33 2014
	Module ID		:	CDB
	Last updated	:	Sep 12, 2014
	==================================================================================
																		   Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of United Kingdom are set-up
	==================================================================================
																	  Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'United Kingdom';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('United Kingdom not found', 16, 1);
	RETURN;
END

UPDATE	countries
	SET	level_1_address_component	=	'Sub-Country',
		level_2_address_component	=	'Division',			--UnitaryAuthority/District/Borough/County',
		level_3_address_component	=	'Sub-Division'		--County District/Borough/UnitaryAuthority'
WHERE	country_id	=	@country_id;

-- ======================================================================

INSERT INTO	level_1_address_components
	(	country_id, level_1_address_component_nm, level_1_address_component_cd	) VALUES	(	@country_id,	'England',			'E'	)
INSERT INTO	level_1_address_components
	(	country_id, level_1_address_component_nm, level_1_address_component_cd	) VALUES	(	@country_id,	'Northern Ireland',	'N'	)
INSERT INTO	level_1_address_components
	(	country_id, level_1_address_component_nm, level_1_address_component_cd	) VALUES	(	@country_id,	'Scotland',			'S'	)
INSERT INTO	level_1_address_components
	(	country_id, level_1_address_component_nm, level_1_address_component_cd	) VALUES	(	@country_id,	'Wales',			'W'	)

-- ======================================================================

DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl VALUES ( 'England', 'Barnsley', 'BX')
INSERT INTO @tbl VALUES ( 'England', 'Bath and North East Somerset', 'BN')
INSERT INTO @tbl VALUES ( 'England', 'Bedford', 'FO')
INSERT INTO @tbl VALUES ( 'England', 'Birmingham', 'BI')
INSERT INTO @tbl VALUES ( 'England', 'Blackburn with Darwen', 'BW')
INSERT INTO @tbl VALUES ( 'England', 'Blackpool', 'BP')
INSERT INTO @tbl VALUES ( 'England', 'Bolton', 'BT')
INSERT INTO @tbl VALUES ( 'England', 'Bournemouth', 'BM')
INSERT INTO @tbl VALUES ( 'England', 'Bracknell Forest', 'BC')
INSERT INTO @tbl VALUES ( 'England', 'Bradford', 'BV')
INSERT INTO @tbl VALUES ( 'England', 'Brighton and Hove', 'BH')
INSERT INTO @tbl VALUES ( 'England', 'Bristol', 'BS')
INSERT INTO @tbl VALUES ( 'England', 'Buckinghamshire', 'BU')
INSERT INTO @tbl VALUES ( 'England', 'Bury', 'BR')
INSERT INTO @tbl VALUES ( 'England', 'Calderdale', 'CX')
INSERT INTO @tbl VALUES ( 'England', 'Cambridgeshire', 'CM')
INSERT INTO @tbl VALUES ( 'England', 'Central Bedfordshire', 'CB')
INSERT INTO @tbl VALUES ( 'England', 'Cheshire East', 'CQ')
INSERT INTO @tbl VALUES ( 'England', 'Cheshire West and Chester', 'CZ')
INSERT INTO @tbl VALUES ( 'England', 'Cornwall', 'CO')
INSERT INTO @tbl VALUES ( 'England', 'Coventry', 'CT')
INSERT INTO @tbl VALUES ( 'England', 'Cumbria', 'CU')
INSERT INTO @tbl VALUES ( 'England', 'Darlington', 'DA')
INSERT INTO @tbl VALUES ( 'England', 'Derby', 'DE')
INSERT INTO @tbl VALUES ( 'England', 'Derbyshire', 'DB')
INSERT INTO @tbl VALUES ( 'England', 'Devon', 'DO')
INSERT INTO @tbl VALUES ( 'England', 'Doncaster', 'DC')
INSERT INTO @tbl VALUES ( 'England', 'Dorset', 'DS')
INSERT INTO @tbl VALUES ( 'England', 'Dudley', 'DY')
INSERT INTO @tbl VALUES ( 'England', 'Durham', 'DH')
INSERT INTO @tbl VALUES ( 'England', 'East Riding of Yorkshire', 'EY')
INSERT INTO @tbl VALUES ( 'England', 'East Sussex', 'ES')
INSERT INTO @tbl VALUES ( 'England', 'Essex', 'EX')
INSERT INTO @tbl VALUES ( 'England', 'Gateshead', 'GH')
INSERT INTO @tbl VALUES ( 'England', 'Gloucestershire', 'GC')
INSERT INTO @tbl VALUES ( 'England', 'Greater London', 'GL')
INSERT INTO @tbl VALUES ( 'England', 'Halton', 'HL')
INSERT INTO @tbl VALUES ( 'England', 'Hampshire', 'HA')
INSERT INTO @tbl VALUES ( 'England', 'Hartlepool', 'HP')
INSERT INTO @tbl VALUES ( 'England', 'Herefordshire', 'HE')
INSERT INTO @tbl VALUES ( 'England', 'Hertfordshire', 'HT')
INSERT INTO @tbl VALUES ( 'England', 'Isle of Wight', 'IW')
INSERT INTO @tbl VALUES ( 'England', 'Isles of Scilly', 'IS')
INSERT INTO @tbl VALUES ( 'England', 'Kent', 'KE')
INSERT INTO @tbl VALUES ( 'England', 'Kingston upon Hull', 'KH')
INSERT INTO @tbl VALUES ( 'England', 'Kirklees', 'KK')
INSERT INTO @tbl VALUES ( 'England', 'Knowsley', 'KN')
INSERT INTO @tbl VALUES ( 'England', 'Lancashire', 'LA')
INSERT INTO @tbl VALUES ( 'England', 'Leeds', 'LS')
INSERT INTO @tbl VALUES ( 'England', 'Leicester', 'LC')
INSERT INTO @tbl VALUES ( 'England', 'Leicestershire', 'LE')
INSERT INTO @tbl VALUES ( 'England', 'Lincolnshire', 'LI')
INSERT INTO @tbl VALUES ( 'England', 'Liverpool', 'LV')
INSERT INTO @tbl VALUES ( 'England', 'Luton', 'LU')
INSERT INTO @tbl VALUES ( 'England', 'Manchester', 'MN')
INSERT INTO @tbl VALUES ( 'England', 'Medway', 'MW')
INSERT INTO @tbl VALUES ( 'England', 'Middlesbrough', 'MB')
INSERT INTO @tbl VALUES ( 'England', 'Milton Keynes', 'MK')
INSERT INTO @tbl VALUES ( 'England', 'Newcastle upon Tyne', 'NU')
INSERT INTO @tbl VALUES ( 'England', 'Norfolk', 'NF')
INSERT INTO @tbl VALUES ( 'England', 'North East Lincolnshire', 'NE')
INSERT INTO @tbl VALUES ( 'England', 'North Lincolnshire', 'NL')
INSERT INTO @tbl VALUES ( 'England', 'North Somerset', 'NS')
INSERT INTO @tbl VALUES ( 'England', 'North Tyneside', 'NI')
INSERT INTO @tbl VALUES ( 'England', 'North Yorkshire', 'NY')
INSERT INTO @tbl VALUES ( 'England', 'Northamptonshire', 'NA')
INSERT INTO @tbl VALUES ( 'England', 'Northumberland', 'NB')
INSERT INTO @tbl VALUES ( 'England', 'Nottingham', 'NG')
INSERT INTO @tbl VALUES ( 'England', 'Nottinghamshire', 'NT')
INSERT INTO @tbl VALUES ( 'England', 'Oldham', 'OL')
INSERT INTO @tbl VALUES ( 'England', 'Oxfordshire', 'OX')
INSERT INTO @tbl VALUES ( 'England', 'Peterborough', 'PB')
INSERT INTO @tbl VALUES ( 'England', 'Plymouth', 'PM')
INSERT INTO @tbl VALUES ( 'England', 'Poole', 'PL')
INSERT INTO @tbl VALUES ( 'England', 'Portsmouth', 'PS')
INSERT INTO @tbl VALUES ( 'England', 'Reading', 'RG')
INSERT INTO @tbl VALUES ( 'England', 'Redcar and Cleveland', 'RC')
INSERT INTO @tbl VALUES ( 'England', 'Rochdale', 'RD')
INSERT INTO @tbl VALUES ( 'England', 'Rotherham', 'RH')
INSERT INTO @tbl VALUES ( 'England', 'Rutland', 'RL')
INSERT INTO @tbl VALUES ( 'England', 'Saint Helens', 'SZ')
INSERT INTO @tbl VALUES ( 'England', 'Salford', 'ZF')
INSERT INTO @tbl VALUES ( 'England', 'Sandwell', 'ZW')
INSERT INTO @tbl VALUES ( 'England', 'Sefton', 'SE')
INSERT INTO @tbl VALUES ( 'England', 'Sheffield', 'SV')
INSERT INTO @tbl VALUES ( 'England', 'Shropshire', 'SP')
INSERT INTO @tbl VALUES ( 'England', 'Slough', 'ZL')
INSERT INTO @tbl VALUES ( 'England', 'Solihull', 'SI')
INSERT INTO @tbl VALUES ( 'England', 'Somerset', 'SM')
INSERT INTO @tbl VALUES ( 'England', 'South Gloucestershire', 'SJ')
INSERT INTO @tbl VALUES ( 'England', 'South Tyneside', 'SX')
INSERT INTO @tbl VALUES ( 'England', 'Southampton', 'ZH')
INSERT INTO @tbl VALUES ( 'England', 'Southend-on-Sea', 'SS')
INSERT INTO @tbl VALUES ( 'England', 'Staffordshire', 'ST')
INSERT INTO @tbl VALUES ( 'England', 'Stockport', 'SK')
INSERT INTO @tbl VALUES ( 'England', 'Stockton-on-Tees', 'ZT')
INSERT INTO @tbl VALUES ( 'England', 'Stoke-on-Trent', 'SO')
INSERT INTO @tbl VALUES ( 'England', 'Suffolk', 'SF')
INSERT INTO @tbl VALUES ( 'England', 'Sunderland', 'SD')
INSERT INTO @tbl VALUES ( 'England', 'Surrey', 'SR')
INSERT INTO @tbl VALUES ( 'England', 'Swindon', 'SN')
INSERT INTO @tbl VALUES ( 'England', 'Tameside', 'TM')
INSERT INTO @tbl VALUES ( 'England', 'Telford and Wrekin', 'TK')
INSERT INTO @tbl VALUES ( 'England', 'Thurrock', 'TR')
INSERT INTO @tbl VALUES ( 'England', 'Torbay', 'TB')
INSERT INTO @tbl VALUES ( 'England', 'Trafford', 'TD')
INSERT INTO @tbl VALUES ( 'England', 'Wakefield', 'WK')
INSERT INTO @tbl VALUES ( 'England', 'Walsall', 'WZ')
INSERT INTO @tbl VALUES ( 'England', 'Warrington', 'WT')
INSERT INTO @tbl VALUES ( 'England', 'Warwickshire', 'WR')
INSERT INTO @tbl VALUES ( 'England', 'West Berkshire', 'WB')
INSERT INTO @tbl VALUES ( 'England', 'West Sussex', 'WS')
INSERT INTO @tbl VALUES ( 'England', 'Wigan', 'WN')
INSERT INTO @tbl VALUES ( 'England', 'Wiltshire', 'WL')
INSERT INTO @tbl VALUES ( 'England', 'Windsor and Maidenhead', 'WA')
INSERT INTO @tbl VALUES ( 'England', 'Wirral', 'WQ')
INSERT INTO @tbl VALUES ( 'England', 'Wokingham', 'WO')
INSERT INTO @tbl VALUES ( 'England', 'Wolverhampton', 'WV')
INSERT INTO @tbl VALUES ( 'England', 'Worcestershire', 'WC')
INSERT INTO @tbl VALUES ( 'England', 'York', 'YK')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Antrim', 'AN')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Ards', 'AD')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Armagh', 'AM')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Ballymena', 'BL')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Ballymoney', 'BY')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Banbridge', 'BB')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Belfast', 'BF')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Carrickfergus', 'CF')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Castlereagh', 'CS')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Coleraine', 'CL')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Cookstown', 'CK')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Craigavon', 'CR')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Derry', 'LD')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Down', 'DW')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Dungannon', 'DN')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Fermanagh', 'FE')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Larne', 'LR')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Limavady', 'LM')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Lisburn', 'LB')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Magherafelt', 'MF')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Moyle', 'MY')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Newry and Mourne', 'NM')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Newtownabbey', 'NW')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'North Down', 'ND')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Omagh', 'OM')
INSERT INTO @tbl VALUES ( 'Northern Ireland', 'Strabane', 'SB')
INSERT INTO @tbl VALUES ( 'Scotland', 'Aberdeen', 'AR')
INSERT INTO @tbl VALUES ( 'Scotland', 'Aberdeenshire', 'AS')
INSERT INTO @tbl VALUES ( 'Scotland', 'Angus', 'AG')
INSERT INTO @tbl VALUES ( 'Scotland', 'Argyll and Bute', 'AB')
INSERT INTO @tbl VALUES ( 'Scotland', 'Clackmannanshire', 'CC')
INSERT INTO @tbl VALUES ( 'Scotland', 'Dumfries and Galloway', 'DG')
INSERT INTO @tbl VALUES ( 'Scotland', 'Dundee', 'DU')
INSERT INTO @tbl VALUES ( 'Scotland', 'East Ayrshire', 'EA')
INSERT INTO @tbl VALUES ( 'Scotland', 'East Dunbartonshire', 'ED')
INSERT INTO @tbl VALUES ( 'Scotland', 'East Lothian', 'EL')
INSERT INTO @tbl VALUES ( 'Scotland', 'East Renfrewshire', 'ER')
INSERT INTO @tbl VALUES ( 'Scotland', 'Edinburgh', 'EB')
INSERT INTO @tbl VALUES ( 'Scotland', 'Eilean Siar', 'WI')
INSERT INTO @tbl VALUES ( 'Scotland', 'Falkirk', 'FK')
INSERT INTO @tbl VALUES ( 'Scotland', 'Fife', 'FI')
INSERT INTO @tbl VALUES ( 'Scotland', 'Glasgow', 'GG')
INSERT INTO @tbl VALUES ( 'Scotland', 'Highland', 'HI')
INSERT INTO @tbl VALUES ( 'Scotland', 'Inverclyde', 'IC')
INSERT INTO @tbl VALUES ( 'Scotland', 'Midlothian', 'ML')
INSERT INTO @tbl VALUES ( 'Scotland', 'Moray', 'MO')
INSERT INTO @tbl VALUES ( 'Scotland', 'North Ayrshire', 'NR')
INSERT INTO @tbl VALUES ( 'Scotland', 'North Lanarkshire', 'NN')
INSERT INTO @tbl VALUES ( 'Scotland', 'Orkney Islands', 'OR')
INSERT INTO @tbl VALUES ( 'Scotland', 'Perthshire and Kinross', 'PK')
INSERT INTO @tbl VALUES ( 'Scotland', 'Renfrewshire', 'RF')
INSERT INTO @tbl VALUES ( 'Scotland', 'Scottish Borders', 'BO')
INSERT INTO @tbl VALUES ( 'Scotland', 'Shetland Islands', 'SH')
INSERT INTO @tbl VALUES ( 'Scotland', 'South Ayrshire', 'SA')
INSERT INTO @tbl VALUES ( 'Scotland', 'South Lanarkshire', 'SL')
INSERT INTO @tbl VALUES ( 'Scotland', 'Stirling', 'ZG')
INSERT INTO @tbl VALUES ( 'Scotland', 'West Dunbartonshire', 'WD')
INSERT INTO @tbl VALUES ( 'Scotland', 'West Lothian', 'WH')
INSERT INTO @tbl VALUES ( 'Wales', 'Anglesey', 'AY')
INSERT INTO @tbl VALUES ( 'Wales', 'Blaenau Gwent', 'BG')
INSERT INTO @tbl VALUES ( 'Wales', 'Bridgend', 'BJ')
INSERT INTO @tbl VALUES ( 'Wales', 'Caerphilly', 'CP')
INSERT INTO @tbl VALUES ( 'Wales', 'Cardiff', 'CA')
INSERT INTO @tbl VALUES ( 'Wales', 'Carmarthenshire', 'CI')
INSERT INTO @tbl VALUES ( 'Wales', 'Ceredigion', 'CG')
INSERT INTO @tbl VALUES ( 'Wales', 'Conwy', 'CW')
INSERT INTO @tbl VALUES ( 'Wales', 'Denbighshire', 'DI')
INSERT INTO @tbl VALUES ( 'Wales', 'Flintshire', 'FL')
INSERT INTO @tbl VALUES ( 'Wales', 'Gwynedd', 'GD')
INSERT INTO @tbl VALUES ( 'Wales', 'Merthyr Tydfil', 'MT')
INSERT INTO @tbl VALUES ( 'Wales', 'Monmouthshire', 'MM')
INSERT INTO @tbl VALUES ( 'Wales', 'Neath Port Talbot', 'NP')
INSERT INTO @tbl VALUES ( 'Wales', 'Newport', 'NO')
INSERT INTO @tbl VALUES ( 'Wales', 'Pembrokeshire', 'PE')
INSERT INTO @tbl VALUES ( 'Wales', 'Powys', 'PO')
INSERT INTO @tbl VALUES ( 'Wales', 'Rhondda, Cynon, Taff', 'RT')
INSERT INTO @tbl VALUES ( 'Wales', 'Swansea', 'SW')
INSERT INTO @tbl VALUES ( 'Wales', 'Torfaen', 'TF')
INSERT INTO @tbl VALUES ( 'Wales', 'Vale of Glamorgan', 'VG')
INSERT INTO @tbl VALUES ( 'Wales', 'Wrexham', 'WX')

INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl	t
		JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				);

-- ======================================================================

DECLARE	@tbl2	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_3_nm varchar (40), level_3_cd varchar (5),
							PRIMARY KEY (level_1_nm, level_2_nm, level_3_nm), UNIQUE (level_1_nm, level_2_nm, level_3_cd));

INSERT INTO @tbl2 VALUES ( 'England', 'Barnsley', 'Barnsley', 'BX')
INSERT INTO @tbl2 VALUES ( 'England', 'Bath and North East Somerset', 'Bath and North East Somerset', 'BN')
INSERT INTO @tbl2 VALUES ( 'England', 'Bedford', 'Bedford', 'FO')
INSERT INTO @tbl2 VALUES ( 'England', 'Birmingham', 'Birmingham', 'BI')
INSERT INTO @tbl2 VALUES ( 'England', 'Blackburn with Darwen', 'Blackburn with Darwen', 'BW')
INSERT INTO @tbl2 VALUES ( 'England', 'Blackpool', 'Blackpool', 'BP')
INSERT INTO @tbl2 VALUES ( 'England', 'Bolton', 'Bolton', 'BT')
INSERT INTO @tbl2 VALUES ( 'England', 'Bournemouth', 'Bournemouth', 'BM')
INSERT INTO @tbl2 VALUES ( 'England', 'Bracknell Forest', 'Bracknell Forest', 'BC')
INSERT INTO @tbl2 VALUES ( 'England', 'Bradford', 'Bradford', 'BV')
INSERT INTO @tbl2 VALUES ( 'England', 'Brighton and Hove', 'Brighton and Hove', 'BH')
INSERT INTO @tbl2 VALUES ( 'England', 'Bristol', 'Bristol', 'BS')
INSERT INTO @tbl2 VALUES ( 'England', 'Buckinghamshire', 'Aylesbury Vale', 'AV')
INSERT INTO @tbl2 VALUES ( 'England', 'Buckinghamshire', 'Chiltern', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Buckinghamshire', 'South Bucks', 'SB')
INSERT INTO @tbl2 VALUES ( 'England', 'Buckinghamshire', 'Wycombe', 'WY')
INSERT INTO @tbl2 VALUES ( 'England', 'Bury', 'Bury', 'BR')
INSERT INTO @tbl2 VALUES ( 'England', 'Calderdale', 'Calderdale', 'CX')
INSERT INTO @tbl2 VALUES ( 'England', 'Cambridgeshire', 'Cambridge', 'CA')
INSERT INTO @tbl2 VALUES ( 'England', 'Cambridgeshire', 'East Cambridgeshire', 'EC')
INSERT INTO @tbl2 VALUES ( 'England', 'Cambridgeshire', 'Fenland', 'FE')
INSERT INTO @tbl2 VALUES ( 'England', 'Cambridgeshire', 'Huntingdonshire', 'HU')
INSERT INTO @tbl2 VALUES ( 'England', 'Cambridgeshire', 'South Cambridgeshire', 'SC')
INSERT INTO @tbl2 VALUES ( 'England', 'Central Bedfordshire', 'Central Bedfordshire', 'CB')
INSERT INTO @tbl2 VALUES ( 'England', 'Cheshire East', 'Cheshire East', 'CQ')
INSERT INTO @tbl2 VALUES ( 'England', 'Cheshire West and Chester', 'Cheshire West and Chester', 'CZ')
INSERT INTO @tbl2 VALUES ( 'England', 'Cornwall', 'Cornwall', 'CO')
INSERT INTO @tbl2 VALUES ( 'England', 'Coventry', 'Coventry', 'CT')
INSERT INTO @tbl2 VALUES ( 'England', 'Cumbria', 'Allerdale', 'AL')
INSERT INTO @tbl2 VALUES ( 'England', 'Cumbria', 'Barrow-in-Furness', 'BF')
INSERT INTO @tbl2 VALUES ( 'England', 'Cumbria', 'Carlisle', 'CA')
INSERT INTO @tbl2 VALUES ( 'England', 'Cumbria', 'Copeland', 'CO')
INSERT INTO @tbl2 VALUES ( 'England', 'Cumbria', 'Eden', 'ED')
INSERT INTO @tbl2 VALUES ( 'England', 'Cumbria', 'South Lakeland', 'SL')
INSERT INTO @tbl2 VALUES ( 'England', 'Darlington', 'Darlington', 'DA')
INSERT INTO @tbl2 VALUES ( 'England', 'Derby', 'Derby', 'DE')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'Amber Valley', 'AV')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'Bolsover', 'BO')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'Chesterfield', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'Derbyshire Dales', 'DD')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'Erewash', 'ER')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'High Peak', 'HP')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'North East Derbyshire', 'ND')
INSERT INTO @tbl2 VALUES ( 'England', 'Derbyshire', 'South Derbyshire', 'SD')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'East Devon', 'ED')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'Exeter', 'EX')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'Mid Devon', 'MD')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'North Devon', 'ND')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'South Hams', 'SH')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'Teignbridge', 'TE')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'Torridge', 'TO')
INSERT INTO @tbl2 VALUES ( 'England', 'Devon', 'West Devon', 'WD')
INSERT INTO @tbl2 VALUES ( 'England', 'Doncaster', 'Doncaster', 'DC')
INSERT INTO @tbl2 VALUES ( 'England', 'Dorset', 'Christchurch', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Dorset', 'East Dorset', 'ED')
INSERT INTO @tbl2 VALUES ( 'England', 'Dorset', 'North Dorset', 'ND')
INSERT INTO @tbl2 VALUES ( 'England', 'Dorset', 'Purbeck', 'PU')
INSERT INTO @tbl2 VALUES ( 'England', 'Dorset', 'West Dorset', 'WD')
INSERT INTO @tbl2 VALUES ( 'England', 'Dorset', 'Weymouth and Portland', 'WP')
INSERT INTO @tbl2 VALUES ( 'England', 'Dudley', 'Dudley', 'DY')
INSERT INTO @tbl2 VALUES ( 'England', 'Durham', 'Durham', 'DH')
INSERT INTO @tbl2 VALUES ( 'England', 'East Riding of Yorkshire', 'East Riding of Yorkshire', 'EY')
INSERT INTO @tbl2 VALUES ( 'England', 'East Sussex', 'Eastbourne', 'EA')
INSERT INTO @tbl2 VALUES ( 'England', 'East Sussex', 'Hastings', 'HA')
INSERT INTO @tbl2 VALUES ( 'England', 'East Sussex', 'Lewes', 'LE')
INSERT INTO @tbl2 VALUES ( 'England', 'East Sussex', 'Rother', 'RO')
INSERT INTO @tbl2 VALUES ( 'England', 'East Sussex', 'Wealden', 'WE')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Basildon', 'BA')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Braintree', 'BT')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Brentwood', 'BW')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Castle Point', 'CP')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Chelmsford', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Colchester', 'CO')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Epping Forest', 'EF')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Harlow', 'HA')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Maldon', 'MA')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Rochford', 'RO')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Tendring', 'TE')
INSERT INTO @tbl2 VALUES ( 'England', 'Essex', 'Uttlesford', 'UT')
INSERT INTO @tbl2 VALUES ( 'England', 'Gateshead', 'Gateshead', 'GH')
INSERT INTO @tbl2 VALUES ( 'England', 'Gloucestershire', 'Cheltenham', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Gloucestershire', 'Cotswold', 'CO')
INSERT INTO @tbl2 VALUES ( 'England', 'Gloucestershire', 'Forest of Dean', 'FD')
INSERT INTO @tbl2 VALUES ( 'England', 'Gloucestershire', 'Gloucester', 'GL')
INSERT INTO @tbl2 VALUES ( 'England', 'Gloucestershire', 'Stroud', 'ST')
INSERT INTO @tbl2 VALUES ( 'England', 'Gloucestershire', 'Tewkesbury', 'TE')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Barking and Dagenham', 'BA')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Barnet', 'BQ')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Bexley', 'XB')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Brent', 'BE')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Bromley', 'BZ')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Camden', 'CN')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Croydon', 'CY')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Ealing', 'EG')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Enfield', 'EF')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Greenwich', 'GR')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Hackney', 'HK')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Hammersmith and Fulham', 'HF')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Haringey', 'HY')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Harrow', 'HR')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Havering', 'HV')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Hillingdon', 'HD')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Hounslow', 'HU')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Islington', 'IT')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Kensington and Chelsea', 'KC')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Kingston upon Thames', 'KT')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Lambeth', 'LT')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Lewisham', 'LW')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'London', 'LN')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Merton', 'ME')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Newham', 'NH')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Redbridge', 'RB')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Richmond upon Thames', 'RU')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Southwark', 'SQ')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Sutton', 'SU')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Tower Hamlets', 'TH')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Waltham Forest', 'WF')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Wandsworth', 'WW')
INSERT INTO @tbl2 VALUES ( 'England', 'Greater London', 'Westminster', 'WE')
INSERT INTO @tbl2 VALUES ( 'England', 'Halton', 'Halton', 'HL')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Basingstoke and Deane', 'BD')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'East Hampshire', 'EH')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Eastleigh', 'EA')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Fareham', 'FA')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Gosport', 'GO')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Hart', 'HR')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Havant', 'HV')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'New Forest', 'NF')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Rushmoor', 'RU')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Test Valley', 'TV')
INSERT INTO @tbl2 VALUES ( 'England', 'Hampshire', 'Winchester', 'WI')
INSERT INTO @tbl2 VALUES ( 'England', 'Hartlepool', 'Hartlepool', 'HP')
INSERT INTO @tbl2 VALUES ( 'England', 'Herefordshire', 'Herefordshire', 'HE')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Broxbourne', 'BR')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Dacorum', 'DA')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'East Hertfordshire', 'EH')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Hertsmere', 'HE')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'North Hertfordshire', 'NH')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Saint Albans', 'SA')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Stevenage', 'ST')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Three Rivers', 'TR')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Watford', 'WA')
INSERT INTO @tbl2 VALUES ( 'England', 'Hertfordshire', 'Welwyn Hatfield', 'WH')
INSERT INTO @tbl2 VALUES ( 'England', 'Isle of Wight', 'Isle of Wight', 'IW')
INSERT INTO @tbl2 VALUES ( 'England', 'Isles of Scilly', 'Isles of Scilly', 'IS')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Ashford', 'AS')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Canterbury', 'CA')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Dartford', 'DA')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Dover', 'DO')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Gravesham', 'GR')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Maidstone', 'MA')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Sevenoaks', 'SE')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Shepway', 'SH')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Swale', 'SW')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Thanet', 'TH')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Tonbridge and Malling', 'TM')
INSERT INTO @tbl2 VALUES ( 'England', 'Kent', 'Tunbridge Wells', 'TW')
INSERT INTO @tbl2 VALUES ( 'England', 'Kingston upon Hull', 'Kingston upon Hull', 'KH')
INSERT INTO @tbl2 VALUES ( 'England', 'Kirklees', 'Kirklees', 'KK')
INSERT INTO @tbl2 VALUES ( 'England', 'Knowsley', 'Knowsley', 'KN')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Burnley', 'BU')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Chorley', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Fylde', 'FY')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Hyndburn', 'HY')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Lancaster', 'LN')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Pendle', 'PE')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Preston', 'PR')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Ribble Valley', 'RV')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Rossendale', 'RO')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'South Ribble', 'SR')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'West Lancashire', 'WL')
INSERT INTO @tbl2 VALUES ( 'England', 'Lancashire', 'Wyre', 'WY')
INSERT INTO @tbl2 VALUES ( 'England', 'Leeds', 'Leeds', 'LS')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicester', 'Leicester', 'LC')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'Blaby', 'BL')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'Charnwood', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'Harborough', 'HA')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'Hinckley and Bosworth', 'HB')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'Melton', 'ME')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'North West Leicestershire', 'NL')
INSERT INTO @tbl2 VALUES ( 'England', 'Leicestershire', 'Oadby and Wigston', 'OW')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'Boston', 'BO')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'East Lindsey', 'EL')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'Lincoln', 'LC')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'North Kesteven', 'NK')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'South Holland', 'SH')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'South Kesteven', 'SK')
INSERT INTO @tbl2 VALUES ( 'England', 'Lincolnshire', 'West Lindsey', 'WL')
INSERT INTO @tbl2 VALUES ( 'England', 'Liverpool', 'Liverpool', 'LV')
INSERT INTO @tbl2 VALUES ( 'England', 'Luton', 'Luton', 'LU')
INSERT INTO @tbl2 VALUES ( 'England', 'Manchester', 'Manchester', 'MN')
INSERT INTO @tbl2 VALUES ( 'England', 'Medway', 'Medway', 'MW')
INSERT INTO @tbl2 VALUES ( 'England', 'Middlesbrough', 'Middlesbrough', 'MB')
INSERT INTO @tbl2 VALUES ( 'England', 'Milton Keynes', 'Milton Keynes', 'MK')
INSERT INTO @tbl2 VALUES ( 'England', 'Newcastle upon Tyne', 'Newcastle upon Tyne', 'NU')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'Breckland', 'BE')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'Broadland', 'BO')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'Great Yarmouth', 'GY')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'King''s Lynn and West Norfolk', 'KL')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'North Norfolk', 'NN')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'Norwich', 'NO')
INSERT INTO @tbl2 VALUES ( 'England', 'Norfolk', 'South Norfolk', 'SN')
INSERT INTO @tbl2 VALUES ( 'England', 'North East Lincolnshire', 'North East Lincolnshire', 'NE')
INSERT INTO @tbl2 VALUES ( 'England', 'North Lincolnshire', 'North Lincolnshire', 'NL')
INSERT INTO @tbl2 VALUES ( 'England', 'North Somerset', 'North Somerset', 'NS')
INSERT INTO @tbl2 VALUES ( 'England', 'North Tyneside', 'North Tyneside', 'NI')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Craven', 'CR')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Hambleton', 'HM')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Harrogate', 'HR')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Richmondshire', 'RI')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Ryedale', 'RY')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Scarborough', 'SC')
INSERT INTO @tbl2 VALUES ( 'England', 'North Yorkshire', 'Selby', 'SE')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'Corby', 'CO')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'Daventry', 'DA')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'East Northamptonshire', 'EN')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'Kettering', 'KE')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'Northampton', 'NO')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'South Northamptonshire', 'SN')
INSERT INTO @tbl2 VALUES ( 'England', 'Northamptonshire', 'Wellingborough', 'WE')
INSERT INTO @tbl2 VALUES ( 'England', 'Northumberland', 'Northumberland', 'NB')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottingham', 'Nottingham', 'NG')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Ashfield', 'AS')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Bassetlaw', 'BA')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Broxtowe', 'BR')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Gedling', 'GE')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Mansfield', 'MA')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Newark and Sherwood', 'NS')
INSERT INTO @tbl2 VALUES ( 'England', 'Nottinghamshire', 'Rushcliffe', 'RU')
INSERT INTO @tbl2 VALUES ( 'England', 'Oldham', 'Oldham', 'OL')
INSERT INTO @tbl2 VALUES ( 'England', 'Oxfordshire', 'Cherwell', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'Oxfordshire', 'Oxford', 'OF')
INSERT INTO @tbl2 VALUES ( 'England', 'Oxfordshire', 'South Oxfordshire', 'SO')
INSERT INTO @tbl2 VALUES ( 'England', 'Oxfordshire', 'Vale of White Horse', 'WH')
INSERT INTO @tbl2 VALUES ( 'England', 'Oxfordshire', 'West Oxfordshire', 'WO')
INSERT INTO @tbl2 VALUES ( 'England', 'Peterborough', 'Peterborough', 'PB')
INSERT INTO @tbl2 VALUES ( 'England', 'Plymouth', 'Plymouth', 'PM')
INSERT INTO @tbl2 VALUES ( 'England', 'Poole', 'Poole', 'PL')
INSERT INTO @tbl2 VALUES ( 'England', 'Portsmouth', 'Portsmouth', 'PS')
INSERT INTO @tbl2 VALUES ( 'England', 'Reading', 'Reading', 'RG')
INSERT INTO @tbl2 VALUES ( 'England', 'Redcar and Cleveland', 'Redcar and Cleveland', 'RC')
INSERT INTO @tbl2 VALUES ( 'England', 'Rochdale', 'Rochdale', 'RD')
INSERT INTO @tbl2 VALUES ( 'England', 'Rotherham', 'Rotherham', 'RH')
INSERT INTO @tbl2 VALUES ( 'England', 'Rutland', 'Rutland', 'RL')
INSERT INTO @tbl2 VALUES ( 'England', 'Saint Helens', 'Saint Helens', 'SZ')
INSERT INTO @tbl2 VALUES ( 'England', 'Salford', 'Salford', 'ZF')
INSERT INTO @tbl2 VALUES ( 'England', 'Sandwell', 'Sandwell', 'ZW')
INSERT INTO @tbl2 VALUES ( 'England', 'Sefton', 'Sefton', 'SE')
INSERT INTO @tbl2 VALUES ( 'England', 'Sheffield', 'Sheffield', 'SV')
INSERT INTO @tbl2 VALUES ( 'England', 'Shropshire', 'Shropshire', 'SP')
INSERT INTO @tbl2 VALUES ( 'England', 'Slough', 'Slough', 'ZL')
INSERT INTO @tbl2 VALUES ( 'England', 'Solihull', 'Solihull', 'SI')
INSERT INTO @tbl2 VALUES ( 'England', 'Somerset', 'Mendip', 'ME')
INSERT INTO @tbl2 VALUES ( 'England', 'Somerset', 'Sedgemoor', 'SE')
INSERT INTO @tbl2 VALUES ( 'England', 'Somerset', 'South Somerset', 'SS')
INSERT INTO @tbl2 VALUES ( 'England', 'Somerset', 'Taunton Deane', 'TD')
INSERT INTO @tbl2 VALUES ( 'England', 'Somerset', 'West Somerset', 'WS')
INSERT INTO @tbl2 VALUES ( 'England', 'South Gloucestershire', 'South Gloucestershire', 'SJ')
INSERT INTO @tbl2 VALUES ( 'England', 'South Tyneside', 'South Tyneside', 'SX')
INSERT INTO @tbl2 VALUES ( 'England', 'Southampton', 'Southampton', 'ZH')
INSERT INTO @tbl2 VALUES ( 'England', 'Southend-on-Sea', 'Southend-on-Sea', 'SS')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'Cannock Chase', 'CC')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'East Staffordshire', 'ES')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'Lichfield', 'LI')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'Newcastle-under-Lyme', 'NL')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'South Staffordshire', 'SS')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'Stafford', 'SF')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'Staffordshire Moorlands', 'SM')
INSERT INTO @tbl2 VALUES ( 'England', 'Staffordshire', 'Tamworth', 'TA')
INSERT INTO @tbl2 VALUES ( 'England', 'Stockport', 'Stockport', 'SK')
INSERT INTO @tbl2 VALUES ( 'England', 'Stockton-on-Tees', 'Stockton-on-Tees', 'ZT')
INSERT INTO @tbl2 VALUES ( 'England', 'Stoke-on-Trent', 'Stoke-on-Trent', 'SO')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Babergh', 'BA')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Forest Heath', 'FH')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Ipswich', 'IP')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Mid Suffolk', 'MS')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Saint Edmundsbury', 'SE')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Suffolk Coastal', 'SC')
INSERT INTO @tbl2 VALUES ( 'England', 'Suffolk', 'Waveney', 'WA')
INSERT INTO @tbl2 VALUES ( 'England', 'Sunderland', 'Sunderland', 'SD')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Elmbridge', 'EL')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Epsom and Ewell', 'EE')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Guildford', 'GU')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Mole Valley', 'MV')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Reigate and Banstead', 'RB')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Runnymede', 'RU')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Spelthorne', 'SP')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Surrey Heath', 'SH')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Tandridge', 'TA')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Waverley', 'WA')
INSERT INTO @tbl2 VALUES ( 'England', 'Surrey', 'Woking', 'WO')
INSERT INTO @tbl2 VALUES ( 'England', 'Swindon', 'Swindon', 'SN')
INSERT INTO @tbl2 VALUES ( 'England', 'Tameside', 'Tameside', 'TM')
INSERT INTO @tbl2 VALUES ( 'England', 'Telford and Wrekin', 'Telford and Wrekin', 'TK')
INSERT INTO @tbl2 VALUES ( 'England', 'Thurrock', 'Thurrock', 'TR')
INSERT INTO @tbl2 VALUES ( 'England', 'Torbay', 'Torbay', 'TB')
INSERT INTO @tbl2 VALUES ( 'England', 'Trafford', 'Trafford', 'TD')
INSERT INTO @tbl2 VALUES ( 'England', 'Wakefield', 'Wakefield', 'WK')
INSERT INTO @tbl2 VALUES ( 'England', 'Walsall', 'Walsall', 'WZ')
INSERT INTO @tbl2 VALUES ( 'England', 'Warrington', 'Warrington', 'WT')
INSERT INTO @tbl2 VALUES ( 'England', 'Warwickshire', 'North Warwickshire', 'NW')
INSERT INTO @tbl2 VALUES ( 'England', 'Warwickshire', 'Nuneaton and Bedworth', 'NB')
INSERT INTO @tbl2 VALUES ( 'England', 'Warwickshire', 'Rugby', 'RU')
INSERT INTO @tbl2 VALUES ( 'England', 'Warwickshire', 'Stratford-on-Avon', 'SA')
INSERT INTO @tbl2 VALUES ( 'England', 'Warwickshire', 'Warwick', 'WA')
INSERT INTO @tbl2 VALUES ( 'England', 'West Berkshire', 'West Berkshire', 'WB')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Adur', 'AD')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Arun', 'AR')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Chichester', 'CH')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Crawley', 'CR')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Horsham', 'HO')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Mid Sussex', 'MS')
INSERT INTO @tbl2 VALUES ( 'England', 'West Sussex', 'Worthing', 'WO')
INSERT INTO @tbl2 VALUES ( 'England', 'Wigan', 'Wigan', 'WN')
INSERT INTO @tbl2 VALUES ( 'England', 'Wiltshire', 'Wiltshire', 'WL')
INSERT INTO @tbl2 VALUES ( 'England', 'Windsor and Maidenhead', 'Windsor and Maidenhead', 'WA')
INSERT INTO @tbl2 VALUES ( 'England', 'Wirral', 'Wirral', 'WQ')
INSERT INTO @tbl2 VALUES ( 'England', 'Wokingham', 'Wokingham', 'WO')
INSERT INTO @tbl2 VALUES ( 'England', 'Wolverhampton', 'Wolverhampton', 'WV')
INSERT INTO @tbl2 VALUES ( 'England', 'Worcestershire', 'Bromsgrove', 'BR')
INSERT INTO @tbl2 VALUES ( 'England', 'Worcestershire', 'Malvern Hills', 'MH')
INSERT INTO @tbl2 VALUES ( 'England', 'Worcestershire', 'Redditch', 'RE')
INSERT INTO @tbl2 VALUES ( 'England', 'Worcestershire', 'Worcester', 'WO')
INSERT INTO @tbl2 VALUES ( 'England', 'Worcestershire', 'Wychavon', 'WY')
INSERT INTO @tbl2 VALUES ( 'England', 'Worcestershire', 'Wyre Forest', 'WF')
INSERT INTO @tbl2 VALUES ( 'England', 'York', 'York', 'YK')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Antrim', 'Antrim', 'AN')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Ards', 'Ards', 'AD')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Armagh', 'Armagh', 'AM')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Ballymena', 'Ballymena', 'BL')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Ballymoney', 'Ballymoney', 'BY')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Banbridge', 'Banbridge', 'BB')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Belfast', 'Belfast', 'BF')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Carrickfergus', 'Carrickfergus', 'CF')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Castlereagh', 'Castlereagh', 'CS')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Coleraine', 'Coleraine', 'CL')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Cookstown', 'Cookstown', 'CK')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Craigavon', 'Craigavon', 'CR')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Derry', 'Derry', 'LD')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Down', 'Down', 'DW')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Dungannon', 'Dungannon', 'DN')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Fermanagh', 'Fermanagh', 'FE')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Larne', 'Larne', 'LR')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Limavady', 'Limavady', 'LM')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Lisburn', 'Lisburn', 'LB')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Magherafelt', 'Magherafelt', 'MF')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Moyle', 'Moyle', 'MY')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Newry and Mourne', 'Newry and Mourne', 'NM')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Newtownabbey', 'Newtownabbey', 'NW')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'North Down', 'North Down', 'ND')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Omagh', 'Omagh', 'OM')
INSERT INTO @tbl2 VALUES ( 'Northern Ireland', 'Strabane', 'Strabane', 'SB')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Aberdeen', 'Aberdeen', 'AR')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Aberdeenshire', 'Aberdeenshire', 'AS')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Angus', 'Angus', 'AG')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Argyll and Bute', 'Argyll and Bute', 'AB')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Clackmannanshire', 'Clackmannanshire', 'CC')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Dumfries and Galloway', 'Dumfries and Galloway', 'DG')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Dundee', 'Dundee', 'DU')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'East Ayrshire', 'East Ayrshire', 'EA')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'East Dunbartonshire', 'East Dunbartonshire', 'ED')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'East Lothian', 'East Lothian', 'EL')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'East Renfrewshire', 'East Renfrewshire', 'ER')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Edinburgh', 'Edinburgh', 'EB')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Eilean Siar', 'Eilean Siar', 'WI')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Falkirk', 'Falkirk', 'FK')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Fife', 'Fife', 'FI')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Glasgow', 'Glasgow', 'GG')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Highland', 'Highland', 'HI')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Inverclyde', 'Inverclyde', 'IC')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Midlothian', 'Midlothian', 'ML')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Moray', 'Moray', 'MO')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'North Ayrshire', 'North Ayrshire', 'NR')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'North Lanarkshire', 'North Lanarkshire', 'NN')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Orkney Islands', 'Orkney Islands', 'OR')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Perthshire and Kinross', 'Perthshire and Kinross', 'PK')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Renfrewshire', 'Renfrewshire', 'RF')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Scottish Borders', 'Scottish Borders', 'BO')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Shetland Islands', 'Shetland Islands', 'SH')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'South Ayrshire', 'South Ayrshire', 'SA')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'South Lanarkshire', 'South Lanarkshire', 'SL')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'Stirling', 'Stirling', 'ZG')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'West Dunbartonshire', 'West Dunbartonshire', 'WD')
INSERT INTO @tbl2 VALUES ( 'Scotland', 'West Lothian', 'West Lothian', 'WH')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Anglesey', 'Anglesey', 'AY')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Blaenau Gwent', 'Blaenau Gwent', 'BG')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Bridgend', 'Bridgend', 'BJ')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Caerphilly', 'Caerphilly', 'CP')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Cardiff', 'Cardiff', 'CA')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Carmarthenshire', 'Carmarthenshire', 'CI')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Ceredigion', 'Ceredigion', 'CG')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Conwy', 'Conwy', 'CW')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Denbighshire', 'Denbighshire', 'DI')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Flintshire', 'Flintshire', 'FL')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Gwynedd', 'Gwynedd', 'GD')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Merthyr Tydfil', 'Merthyr Tydfil', 'MT')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Monmouthshire', 'Monmouthshire', 'MM')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Neath Port Talbot', 'Neath Port Talbot', 'NP')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Newport', 'Newport', 'NO')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Pembrokeshire', 'Pembrokeshire', 'PE')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Powys', 'Powys', 'PO')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Rhondda, Cynon, Taff', 'Rhondda, Cynon, Taff', 'RT')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Swansea', 'Swansea', 'SW')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Torfaen', 'Torfaen', 'TF')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Vale of Glamorgan', 'Vale of Glamorgan', 'VG')
INSERT INTO @tbl2 VALUES ( 'Wales', 'Wrexham', 'Wrexham', 'WX')

INSERT INTO level_3_address_components ( level_3_address_component_nm, level_3_address_component_cd, level_2_address_component_id )
	SELECT	level_3_nm, level_3_cd, level_2_address_component_id
	FROM	@tbl2	t
		JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				)
		JOIN	level_2_address_components	l2
			ON	(	l2.level_2_address_component_nm	=	t.level_2_nm	
				AND	l2.level_1_address_component_id	=	l1.level_1_address_component_id
				)

-- ======================================================================


UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);

UPDATE	l3
	SET	is_authentic	=	1
FROM	level_3_address_components	l3
	JOIN	level_2_address_components	l2
		ON	(	l2.level_2_address_component_id	=	l3.level_2_address_component_id	)
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);

-- ======================================================================


