/* THE BELOW SCRIPT WAS AUTO GENERATED BY THIS SCRIPT
use sysadmin
go
select 
'if exists (select top 1 1 from sysobjects where type = ''v'' and name='''+name+''')
BEGIN
	DROP VIEW '+name+'
END
[GO]
CREATE VIEW '+name+' AS SELECT * FROM dsql2k.CDB.dbo.' + name + '
[GO]'
from sysobjects where type = 'u' or type = 'v'
*/
use CDB
go
if exists (select top 1 1 from sysobjects where type = 'v' and name='Languages')
BEGIN
	DROP VIEW Languages
END
GO
CREATE VIEW Languages AS SELECT * FROM dsql2k.CDB.dbo.Languages
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='states')
BEGIN
	DROP VIEW states
END
GO
CREATE VIEW states AS SELECT * FROM dsql2k.CDB.dbo.states
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='relations')
BEGIN
	DROP VIEW relations
END
GO
CREATE VIEW relations AS SELECT * FROM dsql2k.CDB.dbo.relations
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='representatives')
BEGIN
	DROP VIEW representatives
END
GO
CREATE VIEW representatives AS SELECT * FROM dsql2k.CDB.dbo.representatives
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='districts_or_cities')
BEGIN
	DROP VIEW districts_or_cities
END
GO
CREATE VIEW districts_or_cities AS SELECT * FROM dsql2k.CDB.dbo.districts_or_cities
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='satsang_centre_types')
BEGIN
	DROP VIEW satsang_centre_types
END
GO
CREATE VIEW satsang_centre_types AS SELECT * FROM dsql2k.CDB.dbo.satsang_centre_types
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='post_offices')
BEGIN
	DROP VIEW post_offices
END
GO
CREATE VIEW post_offices AS SELECT * FROM dsql2k.CDB.dbo.post_offices
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='department_groups')
BEGIN
	DROP VIEW department_groups
END
GO
CREATE VIEW department_groups AS SELECT * FROM dsql2k.CDB.dbo.department_groups
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='hospital_units')
BEGIN
	DROP VIEW hospital_units
END
GO
CREATE VIEW hospital_units AS SELECT * FROM dsql2k.CDB.dbo.hospital_units
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='p_and_t_lines')
BEGIN
	DROP VIEW p_and_t_lines
END
GO
CREATE VIEW p_and_t_lines AS SELECT * FROM dsql2k.CDB.dbo.p_and_t_lines
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='measuring_units')
BEGIN
	DROP VIEW measuring_units
END
GO
CREATE VIEW measuring_units AS SELECT * FROM dsql2k.CDB.dbo.measuring_units
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='epabx_lines')
BEGIN
	DROP VIEW epabx_lines
END
GO
CREATE VIEW epabx_lines AS SELECT * FROM dsql2k.CDB.dbo.epabx_lines
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='departments')
BEGIN
	DROP VIEW departments
END
GO
CREATE VIEW departments AS SELECT * FROM dsql2k.CDB.dbo.departments
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='roles')
BEGIN
	DROP VIEW roles
END
GO
CREATE VIEW roles AS SELECT * FROM dsql2k.CDB.dbo.roles
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='roles_application_controls')
BEGIN
	DROP VIEW roles_application_controls
END
GO
CREATE VIEW roles_application_controls AS SELECT * FROM dsql2k.CDB.dbo.roles_application_controls
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='department_p_and_t_lines')
BEGIN
	DROP VIEW department_p_and_t_lines
END
GO
CREATE VIEW department_p_and_t_lines AS SELECT * FROM dsql2k.CDB.dbo.department_p_and_t_lines
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='parties')
BEGIN
	DROP VIEW parties
END
GO
CREATE VIEW parties AS SELECT * FROM dsql2k.CDB.dbo.parties
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='department_epabx_extensions')
BEGIN
	DROP VIEW department_epabx_extensions
END
GO
CREATE VIEW department_epabx_extensions AS SELECT * FROM dsql2k.CDB.dbo.department_epabx_extensions
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='person_titles')
BEGIN
	DROP VIEW person_titles
END
GO
CREATE VIEW person_titles AS SELECT * FROM dsql2k.CDB.dbo.person_titles
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='persons')
BEGIN
	DROP VIEW persons
END
GO
CREATE VIEW persons AS SELECT * FROM dsql2k.CDB.dbo.persons
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='designations')
BEGIN
	DROP VIEW designations
END
GO
CREATE VIEW designations AS SELECT * FROM dsql2k.CDB.dbo.designations
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='societies')
BEGIN
	DROP VIEW societies
END
GO
CREATE VIEW societies AS SELECT * FROM dsql2k.CDB.dbo.societies
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='Sewadar_Status')
BEGIN
	DROP VIEW Sewadar_Status
END
GO
CREATE VIEW Sewadar_Status AS SELECT * FROM dsql2k.CDB.dbo.Sewadar_Status
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='Sewadar_types')
BEGIN
	DROP VIEW Sewadar_types
END
GO
CREATE VIEW Sewadar_types AS SELECT * FROM dsql2k.CDB.dbo.Sewadar_types
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='initiation_places')
BEGIN
	DROP VIEW initiation_places
END
GO
CREATE VIEW initiation_places AS SELECT * FROM dsql2k.CDB.dbo.initiation_places
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='department_persons')
BEGIN
	DROP VIEW department_persons
END
GO
CREATE VIEW department_persons AS SELECT * FROM dsql2k.CDB.dbo.department_persons
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='address_types')
BEGIN
	DROP VIEW address_types
END
GO
CREATE VIEW address_types AS SELECT * FROM dsql2k.CDB.dbo.address_types
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='patrons')
BEGIN
	DROP VIEW patrons
END
GO
CREATE VIEW patrons AS SELECT * FROM dsql2k.CDB.dbo.patrons
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='party_addresses')
BEGIN
	DROP VIEW party_addresses
END
GO
CREATE VIEW party_addresses AS SELECT * FROM dsql2k.CDB.dbo.party_addresses
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='skills')
BEGIN
	DROP VIEW skills
END
GO
CREATE VIEW skills AS SELECT * FROM dsql2k.CDB.dbo.skills
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='satsang_centres')
BEGIN
	DROP VIEW satsang_centres
END
GO
CREATE VIEW satsang_centres AS SELECT * FROM dsql2k.CDB.dbo.satsang_centres
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='occupations')
BEGIN
	DROP VIEW occupations
END
GO
CREATE VIEW occupations AS SELECT * FROM dsql2k.CDB.dbo.occupations
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='party_roles')
BEGIN
	DROP VIEW party_roles
END
GO
CREATE VIEW party_roles AS SELECT * FROM dsql2k.CDB.dbo.party_roles
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='qualifications')
BEGIN
	DROP VIEW qualifications
END
GO
CREATE VIEW qualifications AS SELECT * FROM dsql2k.CDB.dbo.qualifications
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='syssegments')
BEGIN
	DROP VIEW syssegments
END
GO
CREATE VIEW syssegments AS SELECT * FROM dsql2k.CDB.dbo.syssegments
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='sysconstraints')
BEGIN
	DROP VIEW sysconstraints
END
GO
CREATE VIEW sysconstraints AS SELECT * FROM dsql2k.CDB.dbo.sysconstraints
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='party_role_applications')
BEGIN
	DROP VIEW party_role_applications
END
GO
CREATE VIEW party_role_applications AS SELECT * FROM dsql2k.CDB.dbo.party_role_applications
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='cameras')
BEGIN
	DROP VIEW cameras
END
GO
CREATE VIEW cameras AS SELECT * FROM dsql2k.CDB.dbo.cameras
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='marital_status')
BEGIN
	DROP VIEW marital_status
END
GO
CREATE VIEW marital_status AS SELECT * FROM dsql2k.CDB.dbo.marital_status
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='dtproperties')
BEGIN
	DROP VIEW dtproperties
END
GO
CREATE VIEW dtproperties AS SELECT * FROM dsql2k.CDB.dbo.dtproperties
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='countries')
BEGIN
	DROP VIEW countries
END
GO
CREATE VIEW countries AS SELECT * FROM dsql2k.CDB.dbo.countries
GO
