/* THE BELOW SCRIPT WAS AUTO GENERATED BY THIS SCRIPT
use sysadmin
go
select 
'if exists (select top 1 1 from sysobjects where type = ''v'' and name='''+name+''')
BEGIN
	DROP VIEW '+name+'
END
[GO]
CREATE VIEW '+name+' AS SELECT * FROM dsql2k.SysAdmin.dbo.' + name + '
[GO]'
from sysobjects where type = 'u' or type = 'v'
*/

use SysAdmin
Go
if exists (select top 1 1 from sysobjects where type = 'v' and name='package_screen_actions')
BEGIN
	DROP VIEW package_screen_actions
END
GO
CREATE VIEW package_screen_actions AS SELECT * FROM dsql2k.SysAdmin.dbo.package_screen_actions
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='package_user_roles')
BEGIN
	DROP VIEW package_user_roles
END
GO
CREATE VIEW package_user_roles AS SELECT * FROM dsql2k.SysAdmin.dbo.package_user_roles
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='user_role_privileges')
BEGIN
	DROP VIEW user_role_privileges
END
GO
CREATE VIEW user_role_privileges AS SELECT * FROM dsql2k.SysAdmin.dbo.user_role_privileges
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='user_role_granted_actions')
BEGIN
	DROP VIEW user_role_granted_actions
END
GO
CREATE VIEW user_role_granted_actions AS SELECT * FROM dsql2k.SysAdmin.dbo.user_role_granted_actions
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='applications')
BEGIN
	DROP VIEW applications
END
GO
CREATE VIEW applications AS SELECT * FROM dsql2k.SysAdmin.dbo.applications
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='dtproperties')
BEGIN
	DROP VIEW dtproperties
END
GO
CREATE VIEW dtproperties AS SELECT * FROM dsql2k.SysAdmin.dbo.dtproperties
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='application_screen_audits')
BEGIN
	DROP VIEW application_screen_audits
END
GO
CREATE VIEW application_screen_audits AS SELECT * FROM dsql2k.SysAdmin.dbo.application_screen_audits
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='all_users')
BEGIN
	DROP VIEW all_users
END
GO
CREATE VIEW all_users AS SELECT * FROM dsql2k.SysAdmin.dbo.all_users
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='application_users')
BEGIN
	DROP VIEW application_users
END
GO
CREATE VIEW application_users AS SELECT * FROM dsql2k.SysAdmin.dbo.application_users
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='user_privileges')
BEGIN
	DROP VIEW user_privileges
END
GO
CREATE VIEW user_privileges AS SELECT * FROM dsql2k.SysAdmin.dbo.user_privileges
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='standard_messages')
BEGIN
	DROP VIEW standard_messages
END
GO
CREATE VIEW standard_messages AS SELECT * FROM dsql2k.SysAdmin.dbo.standard_messages
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='system_information')
BEGIN
	DROP VIEW system_information
END
GO
CREATE VIEW system_information AS SELECT * FROM dsql2k.SysAdmin.dbo.system_information
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='v_application_user_roles')
BEGIN
	DROP VIEW v_application_user_roles
END
GO
CREATE VIEW v_application_user_roles AS SELECT * FROM dsql2k.SysAdmin.dbo.v_application_user_roles
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='audit_logs')
BEGIN
	DROP VIEW audit_logs
END
GO
CREATE VIEW audit_logs AS SELECT * FROM dsql2k.SysAdmin.dbo.audit_logs
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='adt_packages')
BEGIN
	DROP VIEW adt_packages
END
GO
CREATE VIEW adt_packages AS SELECT * FROM dsql2k.SysAdmin.dbo.adt_packages
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='adt_package_databases')
BEGIN
	DROP VIEW adt_package_databases
END
GO
CREATE VIEW adt_package_databases AS SELECT * FROM dsql2k.SysAdmin.dbo.adt_package_databases
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='adt_package_user_roles')
BEGIN
	DROP VIEW adt_package_user_roles
END
GO
CREATE VIEW adt_package_user_roles AS SELECT * FROM dsql2k.SysAdmin.dbo.adt_package_user_roles
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='adt_application_screen_audits')
BEGIN
	DROP VIEW adt_application_screen_audits
END
GO
CREATE VIEW adt_application_screen_audits AS SELECT * FROM dsql2k.SysAdmin.dbo.adt_application_screen_audits
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='adt_application_users')
BEGIN
	DROP VIEW adt_application_users
END
GO
CREATE VIEW adt_application_users AS SELECT * FROM dsql2k.SysAdmin.dbo.adt_application_users
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='adt_user_privileges')
BEGIN
	DROP VIEW adt_user_privileges
END
GO
CREATE VIEW adt_user_privileges AS SELECT * FROM dsql2k.SysAdmin.dbo.adt_user_privileges
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='package_menu_groups')
BEGIN
	DROP VIEW package_menu_groups
END
GO
CREATE VIEW package_menu_groups AS SELECT * FROM dsql2k.SysAdmin.dbo.package_menu_groups
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='package_menus')
BEGIN
	DROP VIEW package_menus
END
GO
CREATE VIEW package_menus AS SELECT * FROM dsql2k.SysAdmin.dbo.package_menus
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='syssegments')
BEGIN
	DROP VIEW syssegments
END
GO
CREATE VIEW syssegments AS SELECT * FROM dsql2k.SysAdmin.dbo.syssegments
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='sysconstraints')
BEGIN
	DROP VIEW sysconstraints
END
GO
CREATE VIEW sysconstraints AS SELECT * FROM dsql2k.SysAdmin.dbo.sysconstraints
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='packages')
BEGIN
	DROP VIEW packages
END
GO
CREATE VIEW packages AS SELECT * FROM dsql2k.SysAdmin.dbo.packages
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='package_databases')
BEGIN
	DROP VIEW package_databases
END
GO
CREATE VIEW package_databases AS SELECT * FROM dsql2k.SysAdmin.dbo.package_databases
GO
if exists (select top 1 1 from sysobjects where type = 'v' and name='package_screens')
BEGIN
	DROP VIEW package_screens
END
GO
CREATE VIEW package_screens AS SELECT * FROM dsql2k.SysAdmin.dbo.package_screens
GO
