
/* ==================================================================================
    	Source File		:	setup_colombia_components.sql
	Author(s)		:	Jitendra Loyal
	Started On		:	10-10-2014
	Module ID		:	CDB
	Last updated		:	10-10-2014
	==================================================================================
		Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of Colombia are set-up
	==================================================================================
		Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'Colombia';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('Country Colombia not found', 16, 1);
	RETURN;
END

UPDATE	countries
	SET	level_1_address_component	=	'Department',
		level_2_address_component	=	'Municipality',
		level_3_address_component	=	NULL
WHERE	country_id	=	@country_id;

-- ======================================================================

SET NOCOUNT ON
DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_1_cd varchar (5), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_cd, level_2_cd), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Abejorral',	'AN',	'AB');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Abrego',	'NS',	'AB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Abriaqui',	'AN',	'AQ');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Acacias',	'ME',	'AC');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Acandi',	'CH',	'AC');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Acevedo',	'HU',	'AC');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Achi',	'BL',	'AC');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Agrado',	'HU',	'AG');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Aguachica',	'CE',	'AG');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Aguada',	'ST',	'AG');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Aguadas',	'CL',	'AG');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Agua de Dios',	'CU',	'AD');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Aguazul',	'CS',	'AG');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Agustin Codazzi',	'CE',	'AC');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Aipe',	'HU',	'AI');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Alban',	'CU',	'AL');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Alban',	'NA',	'AB');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Albania',	'CQ',	'AL');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Albania',	'ST',	'AL');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Alcala',	'VC',	'AL');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Aldana',	'NA',	'AD');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Alejandria',	'AN',	'AJ');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Algarrobo',	'MA',	'AL');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Algeciras',	'HU',	'AL');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Almaguer',	'CA',	'AL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Almeida',	'BY',	'AL');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Alpujarra',	'TO',	'AJ');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Altamira',	'HU',	'AM');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Alto Baudo',	'CH',	'AL');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Altos del Rosario',	'BL',	'AL');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Alvarado',	'TO',	'AV');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Amaga',	'AN',	'AM');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Amalfi',	'AN',	'AF');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Ambalema',	'TO',	'AM');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Anapoima',	'CU',	'AP');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Ancuya',	'NA',	'AN');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Andalucia',	'VC',	'AD');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Andes',	'AN',	'AD');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Angelopolis',	'AN',	'AL');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Angostura',	'AN',	'AS');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Anolaima',	'CU',	'AN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Anori',	'AN',	'AN');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Anserma',	'CL',	'AN');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Ansermanuevo',	'VC',	'AN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Antioquia [, Santa Fe de]',	'AN',	'AT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Anza',	'AN',	'AZ');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Anzoategui',	'TO',	'AN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Apartado',	'AN',	'AP');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Apia',	'RI',	'AP');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Aquitania',	'BY',	'AQ');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Aracataca',	'MA',	'AC');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Aranzazu',	'CL',	'AR');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Aratoca',	'ST',	'AR');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Arauca',	'AR',	'AC');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Arauquita',	'AR',	'AQ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Arbelaez',	'CU',	'AR');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Arboleda',	'NA',	'AR');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Arboledas',	'NS',	'AR');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Arboletes',	'AN',	'AR');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Arcabuco',	'BY',	'AR');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Arenal',	'BL',	'AN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Argelia',	'AN',	'AG');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Argelia',	'CA',	'AR');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Argelia',	'VC',	'AR');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Ariguani',	'MA',	'AG');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Arjona',	'BL',	'AR');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Armenia',	'QD',	'AR');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Armenia [Mantequilla]',	'AN',	'AA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Armero',	'TO',	'AR');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Arroyohondo',	'BL',	'AH');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Astrea',	'CE',	'AS');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Ataco',	'TO',	'AT');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Atrato',	'CH',	'AT');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Ayapel',	'CO',	'AY');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Bagado',	'CH',	'BA');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Bahia Solano',	'CH',	'BS');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Bajo Baudo',	'CH',	'BB');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Balboa',	'CA',	'BB');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Balboa',	'RI',	'BA');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Baranoa',	'AT',	'BO');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Baraya',	'HU',	'BA');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Barbacoas',	'NA',	'BA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Barbosa',	'AN',	'BB');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Barbosa',	'ST',	'BS');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Barichara',	'ST',	'BH');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Barrancabermeja',	'ST',	'BB');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Barranca de Upia',	'ME',	'BA');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Barrancas',	'LG',	'BA');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Barranco de Loba',	'BL',	'BA');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Barranquilla',	'AT',	'BQ');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Becerril',	'CE',	'BE');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Belalcazar',	'CL',	'BE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Belen',	'BY',	'BL');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Belen',	'NA',	'BE');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Belen de los Andaquies',	'CQ',	'BE');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Belen de Umbria',	'RI',	'BE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Bello',	'AN',	'BL');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Belmira',	'AN',	'BM');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Beltran',	'CU',	'BE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Berbeo',	'BY',	'BB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Betania',	'AN',	'BN');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Beteitiva',	'BY',	'BT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Betulia',	'AN',	'BT');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Betulia',	'ST',	'BE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Bituima',	'CU',	'BI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Boavita',	'BY',	'BO');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Bochalema',	'NS',	'BO');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Bojaca',	'CU',	'BO');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Bojaya',	'CH',	'BO');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Bolivar',	'CA',	'BO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Bolivar',	'ST',	'BO');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Bolivar',	'VC',	'BO');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Bosconia',	'CE',	'BO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Boyaca',	'BY',	'BY');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Briceno',	'AN',	'BR');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Briceno',	'BY',	'BR');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Bucaramanga',	'ST',	'BU');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Bucarasica',	'NS',	'BU');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Buenaventura',	'VC',	'BV');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Buenavista',	'BY',	'BU');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Buenavista',	'CO',	'BU');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Buenavista',	'QD',	'BU');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Buenavista',	'SU',	'BU');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Buenos Aires',	'CA',	'BA');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Buesaco',	'NA',	'BU');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Buga [,Guadalajara de]',	'VC',	'BU');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Bugalagrande',	'VC',	'BG');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Buritica',	'AN',	'BU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Busbanza',	'BY',	'BZ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Cabrera',	'CU',	'CB');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Cabrera',	'ST',	'CB');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Cabuyaro',	'ME',	'CA');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'Cacahual',	'GN',	'CA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Caceres',	'AN',	'CE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Cachipay',	'CU',	'CA');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Cachira',	'NS',	'CR');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Cacota',	'NS',	'CA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Caicedo',	'AN',	'CD');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Caicedonia',	'VC',	'CC');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Caimito',	'SU',	'CA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Cajamarca',	'TO',	'CJ');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Cajibio',	'CA',	'CJ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Cajica',	'CU',	'CJ');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Calamar',	'BL',	'CM');
INSERT INTO @tbl VALUES ('Guaviare'            ,	     'Calamar',	'GV',	'CA');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Calarca',	'QD',	'CA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Caldas',	'AN',	'CL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Caldas',	'BY',	'CD');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Caldono',	'CA',	'CD');
INSERT INTO @tbl VALUES ('Santander'            ,	     'California',	'ST',	'CA');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Calima',	'VC',	'CM');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Cali [, Santiago de]',	'VC',	'CL');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Caloto',	'CA',	'CT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Campamento',	'AN',	'CM');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Campoalegre',	'HU',	'CA');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Campo de la Cruz',	'AT',	'CC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Campohermoso',	'BY',	'CM');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Canalete',	'CO',	'CA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Canasgordas',	'AN',	'CG');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Candelaria',	'AT',	'CA');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Candelaria',	'VC',	'CN');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Cantagallo',	'BL',	'CN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Caparrapi',	'CU',	'CP');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Capitanejo',	'ST',	'CJ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Caqueza',	'CU',	'CQ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Caracoli',	'AN',	'CA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Caramanta',	'AN',	'CT');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Carcasi',	'ST',	'CS');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Carepa',	'AN',	'CP');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Carmen de Apicala',	'TO',	'CA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Carmen de Carupa',	'CU',	'CC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Carolina [del Principe]',	'AN',	'CR');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Cartagena [de Indias]',	'BL',	'CG');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Cartagena del Chaira',	'CQ',	'CA');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Cartago',	'VC',	'CR');
INSERT INTO @tbl VALUES ('Vaupes'            ,	     'Caruru',	'VP',	'CA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Casabianca',	'TO',	'CB');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Castilla la Nueva',	'ME',	'CN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Caucasia',	'AN',	'CU');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Cepita',	'ST',	'CE');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Cerete',	'CO',	'CE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Cerinza',	'BY',	'CE');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Cerrito',	'ST',	'CR');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Cerro de San Antonio',	'MA',	'CE');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Chachagui',	'NA',	'CH');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Chaguani',	'CU',	'CN');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Chalan',	'SU',	'CH');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Chameza',	'CS',	'CH');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Chaparral',	'TO',	'CH');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Charala',	'ST',	'CL');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Charta',	'ST',	'CH');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Chia',	'CU',	'CI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Chigorodo',	'AN',	'CH');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Chima',	'CO',	'CM');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Chima',	'ST',	'CM');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Chimichagua',	'CE',	'CC');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Chinacota',	'NS',	'CH');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chinavita',	'BY',	'CN');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Chinchina',	'CL',	'CH');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Chinu',	'CO',	'CN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Chipaque',	'CU',	'CE');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Chipata',	'ST',	'CP');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chiquinquira',	'BY',	'CQ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chiquiza',	'BY',	'CZ');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Chiriguana',	'CE',	'CG');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chiscas',	'BY',	'CS');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chita',	'BY',	'CA');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Chitaga',	'NS',	'CT');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chitaraque',	'BY',	'CR');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chivata',	'BY',	'CV');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Chivolo',	'MA',	'CH');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Chivor',	'BY',	'CH');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Choachi',	'CU',	'CH');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Choconta',	'CU',	'CO');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Cicuco',	'BL',	'CC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Cienaga',	'BY',	'CG');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Cienaga',	'MA',	'CI');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Cienaga de Oro',	'CO',	'CO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Cimitarra',	'ST',	'CI');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Circasia',	'QD',	'CI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Cisneros',	'AN',	'CI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     '[Ciudad] Bolivar',	'AN',	'BO');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Clemencia',	'BL',	'CL');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Cocorna',	'AN',	'CO');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Coello',	'TO',	'CL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Cogua',	'CU',	'CG');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Colombia',	'HU',	'CO');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Colon',	'NA',	'CL');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Colon',	'PU',	'CO');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Coloso',	'SU',	'CS');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Combita',	'BY',	'CB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Concepcion',	'AN',	'CC');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Concepcion',	'ST',	'CC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Concordia',	'AN',	'CN');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Concordia',	'MA',	'CO');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Condoto',	'CH',	'CO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Confines',	'ST',	'CF');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Consaca',	'NA',	'CS');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Contadero',	'NA',	'CN');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Contratacion',	'ST',	'CN');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Convencion',	'NS',	'CV');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Copacabana',	'AN',	'CB');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Coper',	'BY',	'CP');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Cordoba',	'BL',	'CO');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Cordoba',	'NA',	'CO');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Cordoba',	'QD',	'CO');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Corinto',	'CA',	'CO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Coromoro',	'ST',	'CO');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Corozal',	'SU',	'CZ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Corrales',	'BY',	'CL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Cota',	'CU',	'CT');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Cotorra',	'CO',	'CT');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Covarachia',	'BY',	'CO');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Coyaima',	'TO',	'CY');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Cravo Norte',	'AR',	'CN');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Cuaspud',	'NA',	'CD');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Cubara',	'BY',	'CU');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Cubarral [, San Luis de]',	'ME',	'CB');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Cucaita',	'BY',	'CC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Cucunuba',	'CU',	'CU');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Cucuta [, San Jose de]',	'NS',	'CC');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Cucutilla',	'NS',	'CL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Cuitiva',	'BY',	'CT');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Cumaral',	'ME',	'CM');
INSERT INTO @tbl VALUES ('Vichada'            ,	     'Cumaribo',	'VD',	'CU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Cumbal',	'NA',	'CU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Cumbitara',	'NA',	'CT');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Cunday',	'TO',	'CU');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Curillo',	'CQ',	'CU');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Curiti',	'ST',	'CU');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Curumani',	'CE',	'CU');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Dabeiba',	'AN',	'DA');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Dagua',	'VC',	'DA');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Dibulla',	'LG',	'DB');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Distraccion',	'LG',	'DS');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Dolores',	'TO',	'DO');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Don Matias',	'AN',	'DM');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Dosquebradas',	'RI',	'DO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Duitama',	'BY',	'DU');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Durania',	'NS',	'DU');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Ebejico',	'AN',	'EJ');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'El Aguila',	'VC',	'EA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'El Bagre',	'AN',	'EB');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'El Banco',	'MA',	'EB');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'El Cairo',	'VC',	'EC');
INSERT INTO @tbl VALUES ('Meta'            ,	     'El Calvario',	'ME',	'EV');
INSERT INTO @tbl VALUES ('Choco'            ,	     'El Canton del San Pablo',	'CH',	'SP');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'El Carmen',	'NS',	'EC');
INSERT INTO @tbl VALUES ('Choco'            ,	     'El Carmen [de Atrato]',	'CH',	'EC');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'El Carmen de Bolivar',	'BL',	'EC');
INSERT INTO @tbl VALUES ('Santander'            ,	     'El Carmen [de Chucuri]',	'ST',	'EC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'El Carmen de Viboral',	'AN',	'CV');
INSERT INTO @tbl VALUES ('Meta'            ,	     'El Castillo',	'ME',	'EC');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'El Cerrito',	'VC',	'ET');
INSERT INTO @tbl VALUES ('Narino'            ,	     'El Charco',	'NA',	'EC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'El Cocuy',	'BY',	'EC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'El Colegio',	'CU',	'EC');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'El Copey',	'CE',	'EC');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'El Doncello',	'CQ',	'ED');
INSERT INTO @tbl VALUES ('Meta'            ,	     'El Dorado',	'ME',	'ED');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'El Dovio',	'VC',	'ED');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'El Encanto',	'AM',	'EE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'El Espino',	'BY',	'EE');
INSERT INTO @tbl VALUES ('Santander'            ,	     'El Guacamayo',	'ST',	'EG');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'El Guamo',	'BL',	'EG');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Elias',	'HU',	'EL');
INSERT INTO @tbl VALUES ('Choco'            ,	     'El Litoral del San Juan',	'CH',	'LI');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'El Molino',	'LG',	'EM');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'El Paso',	'CE',	'EP');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'El Paujil',	'CQ',	'EP');
INSERT INTO @tbl VALUES ('Narino'            ,	     'El Penol',	'NA',	'EP');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'El Penon',	'BL',	'EP');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'El Penon',	'CU',	'EP');
INSERT INTO @tbl VALUES ('Santander'            ,	     'El Penon',	'ST',	'EP');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'El Pinon',	'MA',	'EP');
INSERT INTO @tbl VALUES ('Santander'            ,	     'El Playon',	'ST',	'EY');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'El Reten',	'MA',	'ER');
INSERT INTO @tbl VALUES ('Guaviare'            ,	     'El Retorno',	'GV',	'ER');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'El Rosal',	'CU',	'ER');
INSERT INTO @tbl VALUES ('Narino'            ,	     'El Rosario',	'NA',	'ER');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'El Santuario',	'AN',	'SI');
INSERT INTO @tbl VALUES ('Narino'            ,	     'El Tablon [de Gomez]',	'NA',	'EL');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'El Tambo',	'CA',	'ET');
INSERT INTO @tbl VALUES ('Narino'            ,	     'El Tambo',	'NA',	'ET');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'El Tarra',	'NS',	'ET');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'El Zulia',	'NS',	'EZ');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Encino',	'ST',	'EN');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Enciso',	'ST',	'ES');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Entrerrios',	'AN',	'ER');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Envigado',	'AN',	'EN');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Espinal',	'TO',	'ES');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Facatativa',	'CU',	'FA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Falan',	'TO',	'FA');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Filadelfia',	'CL',	'FI');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Filandia',	'QD',	'FI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Firavitoba',	'BY',	'FI');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Flandes',	'TO',	'FL');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Florencia',	'CA',	'FL');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Florencia',	'CQ',	'FL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Floresta',	'BY',	'FL');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Florian',	'ST',	'EF');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Florida',	'VC',	'FL');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Floridablanca',	'ST',	'FL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Fomeque',	'CU',	'FM');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Fonseca',	'LG',	'FO');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Fortul',	'AR',	'FO');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Fosca',	'CU',	'FO');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Francisco Pizarro',	'NA',	'FP');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Fredonia',	'AN',	'FD');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Fresno',	'TO',	'FR');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Frontino',	'AN',	'FN');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Fuente de Oro',	'ME',	'FO');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Fundacion',	'MA',	'FU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Funes',	'NA',	'FU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Funza',	'CU',	'FZ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Fuquene',	'CU',	'FQ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Fusagasuga',	'CU',	'FS');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Gachala',	'CU',	'GL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Gachancipa',	'CU',	'GP');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Gachantiva',	'BY',	'GC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Gacheta',	'CU',	'GT');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Galan',	'ST',	'GL');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Galapa',	'AT',	'GA');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Galeras',	'SU',	'GA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Gama',	'CU',	'GM');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Gamarra',	'CE',	'GA');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Gambita',	'ST',	'GA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Gameza',	'BY',	'GZ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Garagoa',	'BY',	'GG');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Garzon',	'HU',	'GA');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Genova',	'QD',	'GE');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Gigante',	'HU',	'GI');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Ginebra',	'VC',	'GI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Giraldo',	'AN',	'GL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Girardot',	'CU',	'GI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Girardota',	'AN',	'GT');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Giron',	'ST',	'GI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Gomez Plata',	'AN',	'GP');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Gonzalez',	'CE',	'GO');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Gramalote',	'NS',	'GR');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Granada',	'AN',	'GR');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Granada',	'CU',	'GR');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Granada',	'ME',	'GR');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Guaca',	'ST',	'GC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Guacamayas',	'BY',	'GM');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Guacari',	'VC',	'GU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guacheta',	'CU',	'GC');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Guachucal',	'NA',	'GC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Guadalupe',	'AN',	'GD');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Guadalupe',	'HU',	'GU');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Guadalupe',	'ST',	'GD');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guaduas',	'CU',	'GD');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Guaitarilla',	'NA',	'GT');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Gualmatan',	'NA',	'GM');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Guamal',	'MA',	'GU');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Guamal',	'ME',	'GU');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Guamo',	'TO',	'GU');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Guapi',	'CA',	'GU');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Guapota',	'ST',	'GP');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Guaranda',	'SU',	'GU');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Guarne',	'AN',	'GU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guasca',	'CU',	'GU');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Guatape',	'AN',	'GA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guataqui',	'CU',	'GQ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guatavita',	'CU',	'GV');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Guateque',	'BY',	'GT');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Guatica',	'RI',	'GU');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Guavata',	'ST',	'GV');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'Guaviare',	'GN',	'GU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guayabal de Siquima',	'CU',	'GS');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Guayabetal',	'CU',	'GB');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Guayata',	'BY',	'GY');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Guican',	'BY',	'GU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Gutierrez',	'CU',	'GZ');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Guepsa',	'ST',	'GU');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Hacari',	'NS',	'HA');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Hatillo de Loba',	'BL',	'HL');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Hato',	'ST',	'HA');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Hato Corozal',	'CS',	'HA');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Hatonuevo',	'LG',	'HN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Heliconia',	'AN',	'HE');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Herran',	'NS',	'HE');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Herveo',	'TO',	'HE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Hispania',	'AN',	'HI');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Hobo',	'HU',	'HO');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Honda',	'TO',	'HO');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Ibague',	'TO',	'IB');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Icononzo',	'TO',	'IC');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Iles',	'NA',	'IL');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Imues',	'NA',	'IM');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Inza',	'CA',	'IN');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Ipiales',	'NA',	'IP');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Iquira',	'HU',	'IQ');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Isnos',	'HU',	'IS');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Istmina',	'CH',	'IS');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Itagui',	'AN',	'II');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Ituango',	'AN',	'IN');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Iza',	'BY',	'IZ');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Jambalo',	'CA',	'JA');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Jamundi',	'VC',	'JA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Jardin',	'AN',	'JA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Jenesano',	'BY',	'JN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Jerico',	'AN',	'JE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Jerico',	'BY',	'JR');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Jerusalen',	'CU',	'JE');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Jesus Maria',	'ST',	'JM');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Jordan',	'ST',	'JO');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Juan de Acosta',	'AT',	'JU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Junin',	'CU',	'JU');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Jurado',	'CH',	'JU');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'La Apartada',	'CO',	'LA');
INSERT INTO @tbl VALUES ('Huila'            ,	     'La Argentina',	'HU',	'LA');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Labateca',	'NS',	'LB');
INSERT INTO @tbl VALUES ('Santander'            ,	     'La Belleza',	'ST',	'LB');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Labranzagrande',	'BY',	'LB');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'La Calera',	'CU',	'LC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'La Capilla',	'BY',	'LC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'La Ceja',	'AN',	'LC');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'La Celia',	'RI',	'LC');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'La Chorrera',	'AM',	'LC');
INSERT INTO @tbl VALUES ('Narino'            ,	     'La Cruz',	'NA',	'LC');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'La Cumbre',	'VC',	'LC');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'La Dorada',	'CL',	'LD');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'La Esperanza',	'NS',	'LE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'La Estrella',	'AN',	'LE');
INSERT INTO @tbl VALUES ('Narino'            ,	     'La Florida',	'NA',	'LF');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'La Gloria',	'CE',	'LG');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'La Guadalupe',	'GN',	'LG');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'La Jagua de Ibirico',	'CE',	'LJ');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'La Jagua del Pilar',	'LG',	'LJ');
INSERT INTO @tbl VALUES ('Narino'            ,	     'La Llanada',	'NA',	'LL');
INSERT INTO @tbl VALUES ('Meta'            ,	     'La Macarena',	'ME',	'LM');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'La Merced',	'CL',	'LM');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'La Mesa',	'CU',	'LM');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'La Montanita',	'CQ',	'LM');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Landazuri',	'ST',	'LN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'La Palma',	'CU',	'LA');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'La Paz',	'CE',	'RO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'La Paz',	'ST',	'LP');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'La Pedrera',	'AM',	'LP');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'La Pena',	'CU',	'LP');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'La Pintada',	'AN',	'LP');
INSERT INTO @tbl VALUES ('Huila'            ,	     'La Plata',	'HU',	'LP');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'La Playa [de Belen]',	'NS',	'LP');
INSERT INTO @tbl VALUES ('Vichada'            ,	     'La Primavera',	'VD',	'LP');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'La Salina',	'CS',	'LS');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'La Sierra',	'CA',	'LS');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'La Tebaida',	'QD',	'LT');
INSERT INTO @tbl VALUES ('Narino'            ,	     'La Tola',	'NA',	'LT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'La Union',	'AN',	'LU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'La Union',	'NA',	'LU');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'La Union',	'VC',	'LU');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'La Union [de Sucre]',	'SU',	'LU');
INSERT INTO @tbl VALUES ('Meta'            ,	     'La Uribe',	'ME',	'LU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'La Uvita',	'BY',	'LU');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'La Vega',	'CA',	'LV');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'La Vega',	'CU',	'LV');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'La Victoria',	'AM',	'LV');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'La Victoria',	'BY',	'LV');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'La Victoria',	'VC',	'LV');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'La Virginia',	'RI',	'LV');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Lebrija',	'ST',	'LE');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Leiva',	'NA',	'LE');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Lejanias',	'ME',	'LE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Lenguazaque',	'CU',	'LE');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Lerida',	'TO',	'LE');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Leticia',	'AM',	'LE');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Libano',	'TO',	'LI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Liborina',	'AN',	'LI');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Linares',	'NA',	'LI');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Lloro',	'CH',	'LL');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Lopez [de Micay]',	'CA',	'LO');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Lorica [, Santa Cruz de]',	'CO',	'LO');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Los Andes',	'NA',	'LO');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Los Cordobas',	'CO',	'LC');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Los Palmitos',	'SU',	'LP');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Los Patios',	'NS',	'LS');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Los Santos',	'ST',	'LS');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Lourdes',	'NS',	'LO');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Luruaco',	'AT',	'LU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Macanal',	'BY',	'MC');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Macaravita',	'ST',	'MC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Maceo',	'AN',	'MC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Macheta',	'CU',	'MC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Madrid',	'CU',	'MD');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Magangue',	'BL',	'MG');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Magui',	'NA',	'MG');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Mahates',	'BL',	'MH');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Maicao',	'LG',	'MC');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Majagual',	'SU',	'MA');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Malaga',	'ST',	'MA');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Malambo',	'AT',	'ML');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Mallama',	'NA',	'ML');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Manati',	'AT',	'MN');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Manaure',	'LG',	'MN');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Manaure [Balcon del Cesar]',	'CE',	'MA');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Mani',	'CS',	'MA');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Manizales',	'CL',	'ML');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Manta',	'CU',	'MN');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Manzanares',	'CL',	'MZ');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Mapiripan',	'ME',	'MA');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Margarita',	'BL',	'MA');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Maria la Baja',	'BL',	'MB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Marinilla',	'AN',	'MA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Maripi',	'BY',	'MP');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Mariquita [, San Sebastian de]',	'TO',	'MA');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Marmato',	'CL',	'MM');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Marquetalia',	'CL',	'MQ');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Marsella',	'RI',	'MA');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Marulanda',	'CL',	'MD');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Matanza',	'ST',	'MZ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Medellin',	'AN',	'ME');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Medina',	'CU',	'ME');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Medio Atrato',	'CH',	'MA');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Medio Baudo',	'CH',	'MB');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Melgar',	'TO',	'ME');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Mercaderes',	'CA',	'ME');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Mesetas',	'ME',	'ME');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Milan',	'CQ',	'MI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Miraflores',	'BY',	'MF');
INSERT INTO @tbl VALUES ('Guaviare'            ,	     'Miraflores',	'GV',	'MI');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Miranda',	'CA',	'MI');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Miriti-Parana',	'AM',	'MI');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Mistrato',	'RI',	'MI');
INSERT INTO @tbl VALUES ('Vaupes'            ,	     'Mitu',	'VP',	'MI');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Mocoa [, San Miguel de]',	'PU',	'MO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Mogotes',	'ST',	'MG');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Molagavita',	'ST',	'MO');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Momil',	'CO',	'MM');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Mompos',	'BL',	'MP');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Mongua',	'BY',	'MA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Mongui',	'BY',	'MI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Moniquira',	'BY',	'MQ');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Monitos',	'CO',	'MT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Montebello',	'AN',	'MO');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Montecristo',	'BL',	'MC');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Montelibano',	'CO',	'ML');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Montenegro',	'QD',	'MO');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Monteria',	'CO',	'MR');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Monterrey',	'CS',	'MO');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Morales',	'BL',	'MS');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Morales',	'CA',	'MO');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Morelia',	'CQ',	'MO');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'Morichal Nuevo',	'GN',	'MO');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Morroa',	'SU',	'MO');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Mosquera',	'CU',	'MO');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Mosquera',	'NA',	'MO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Motavita',	'BY',	'MV');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Murillo',	'TO',	'MU');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Murindo',	'AN',	'MR');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Mutata',	'AN',	'MT');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Mutiscua',	'NS',	'MU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Muzo',	'BY',	'MZ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Narino',	'AN',	'NA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Narino',	'CU',	'NA');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Nataga',	'HU',	'NA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Natagaima',	'TO',	'NA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Nechi',	'AN',	'NH');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Necocli',	'AN',	'NC');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Neira',	'CL',	'NE');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Neiva',	'HU',	'NE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Nemocon',	'CU',	'NE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Nilo',	'CU',	'NI');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Nimaima',	'CU',	'NM');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Nobsa',	'BY',	'NO');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Nocaima',	'CU',	'NO');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Norcasia',	'CL',	'NO');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Novita',	'CH',	'NO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Nuevo Colon',	'BY',	'NC');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Nunchia',	'CS',	'NU');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Nuqui',	'CH',	'NU');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Obando',	'VC',	'OB');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Ocamonte',	'ST',	'OC');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Ocana',	'NS',	'OC');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Oiba',	'ST',	'OI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Oicata',	'BY',	'OI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Olaya',	'AN',	'OL');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Olaya Herrera',	'NA',	'OH');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Onzaga',	'ST',	'ON');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Oporapa',	'HU',	'OP');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Orito',	'PU',	'OR');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Orocue',	'CS',	'OR');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Ortega',	'TO',	'OR');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Ospina',	'NA',	'OS');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Otanche',	'BY',	'OT');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Ovejas',	'SU',	'OV');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Pachavita',	'BY',	'PC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Pacho',	'CU',	'PC');
INSERT INTO @tbl VALUES ('Vaupes'            ,	     'Pacoa',	'VP',	'PC');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Pacora',	'CL',	'PC');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Padilla',	'CA',	'PD');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Paez',	'BY',	'PZ');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Paez',	'CA',	'PZ');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Paicol',	'HU',	'PC');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Pailitas',	'CE',	'PA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Paime',	'CU',	'PM');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Paipa',	'BY',	'PP');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Pajarito',	'BY',	'PJ');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Palermo',	'HU',	'PM');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Palestina',	'CL',	'PL');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Palestina',	'HU',	'PS');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Palmar',	'ST',	'PL');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Palmar de Varela',	'AT',	'PV');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Palmas del Socorro',	'ST',	'PS');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Palmira',	'VC',	'PA');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Palmito [, San Antonio de]',	'SU',	'PA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Palocabildo',	'TO',	'PA');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Pamplona',	'NS',	'PA');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Pamplonita',	'NS',	'PT');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'Pana Pana',	'GN',	'PA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Pandi',	'CU',	'PD');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Panqueba',	'BY',	'PQ');
INSERT INTO @tbl VALUES ('Vaupes'            ,	     'Papunahua',	'VP',	'PP');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Paramo',	'ST',	'PR');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Paratebueno',	'CU',	'PB');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Pasca',	'CU',	'PA');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Pasto [, San Juan de]',	'NA',	'PA');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Patia',	'CA',	'PA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Pauna',	'BY',	'PA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Paya',	'BY',	'PY');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Paz de Ariporo',	'CS',	'PA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Paz de Rio',	'BY',	'PR');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Pedraza',	'MA',	'PE');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Pelaya',	'CE',	'PE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Penol',	'AN',	'PL');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Pensilvania',	'CL',	'PE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Peque',	'AN',	'PQ');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Pereira',	'RI',	'PE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Pesca',	'BY',	'PE');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Piamonte',	'CA',	'PM');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Piedecuesta',	'ST',	'PD');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Piedras',	'TO',	'PI');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Piendamo',	'CA',	'PI');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Pijao',	'QD',	'PI');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Pijino del Carmen',	'MA',	'PC');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Pinchote',	'ST',	'PI');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Pinillos',	'BL',	'PI');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Piojo',	'AT',	'PI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Pisba',	'BY',	'PV');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Pital',	'HU',	'PI');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Pitalito',	'HU',	'PT');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Pivijay',	'MA',	'PI');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Planadas',	'TO',	'PL');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Planeta Rica',	'CO',	'PR');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Plato',	'MA',	'PL');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Policarpa',	'NA',	'PC');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Polonuevo',	'AT',	'PL');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Ponedera',	'AT',	'PD');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Popayan',	'CA',	'PO');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Pore',	'CS',	'PO');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Potosi',	'NA',	'PT');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Pradera',	'VC',	'PR');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Prado',	'TO',	'PR');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Providencia',	'NA',	'PR');
INSERT INTO @tbl VALUES ('San Andres y Providencia'            ,	     'Providencia [y Santa Catalina]',	'SA',	'PR');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Pueblo Bello',	'CE',	'PB');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Pueblo Nuevo',	'CO',	'PN');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Pueblo Rico',	'RI',	'PR');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Pueblorrico',	'AN',	'PU');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Pueblo Viejo',	'MA',	'PV');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Puente Nacional',	'ST',	'PN');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Puerres',	'NA',	'PU');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Puerto Alegria',	'AM',	'AL');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Puerto Arica',	'AM',	'AR');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Puerto Asis',	'PU',	'PA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Puerto Berrio',	'AN',	'PB');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Puerto Boyaca',	'BY',	'PB');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Puerto Caicedo',	'PU',	'PC');
INSERT INTO @tbl VALUES ('Vichada'            ,	     'Puerto Carreno',	'VD',	'PC');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Puerto Colombia',	'AT',	'PC');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'Puerto Colombia',	'GN',	'PC');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Puerto Concordia',	'ME',	'PC');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Puerto Escondido',	'CO',	'PE');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Puerto Gaitan',	'ME',	'PG');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Puerto Guzman',	'PU',	'PG');
INSERT INTO @tbl VALUES ('Guainia'            ,	     '[Puerto] Inirida',	'GN',	'IN');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Puerto Leguizamo',	'PU',	'PL');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Puerto Libertador',	'CO',	'PL');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Puerto Lleras',	'ME',	'PL');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Puerto Lopez',	'ME',	'PZ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Puerto Nare',	'AN',	'PN');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Puerto Narino',	'AM',	'PN');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Puerto Parra',	'ST',	'PP');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Puerto Rico',	'CQ',	'PR');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Puerto Rico',	'ME',	'PR');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Puerto Rondon',	'AR',	'PR');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Puerto Salgar',	'CU',	'PS');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Puerto Santander',	'AM',	'PS');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Puerto Santander',	'NS',	'PS');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Puerto Tejada',	'CA',	'PT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Puerto Triunfo',	'AN',	'PT');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Puerto Wilches',	'ST',	'PW');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Puli',	'CU',	'PU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Pupiales',	'NA',	'PP');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Purace',	'CA',	'PU');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Purificacion',	'TO',	'PU');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Purisima',	'CO',	'PU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Quebradanegra',	'CU',	'QN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Quetame',	'CU',	'QT');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Quibdo',	'CH',	'QU');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Quimbaya',	'QD',	'QU');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Quinchia',	'RI',	'QU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Quipama',	'BY',	'QU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Quipile',	'CU',	'QP');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Rafael Reyes',	'CU',	'RR');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Ragonvalia',	'NS',	'RA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Ramiriqui',	'BY',	'RM');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Raquira',	'BY',	'RA');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Recetor',	'CS',	'RE');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Regidor',	'BL',	'RE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Remedios',	'AN',	'RM');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Remolino',	'MA',	'RE');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Repelon',	'AT',	'RE');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Restrepo',	'ME',	'RE');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Restrepo',	'VC',	'RE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Retiro',	'AN',	'RT');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Ricaurte',	'CU',	'RI');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Ricaurte',	'NA',	'RI');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Rioblanco',	'TO',	'RI');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Rio de Oro',	'CE',	'RI');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Riofrio',	'VC',	'RI');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Riohacha',	'LG',	'RI');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Rionegro',	'AN',	'RI');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Rionegro',	'ST',	'RI');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Rio Quito',	'CH',	'RQ');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Riosucio',	'CH',	'RI');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Riosucio',	'CL',	'RS');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Rio Viejo',	'BL',	'RV');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Risaralda',	'CL',	'RR');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Rivera',	'HU',	'RI');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Roberto Payan',	'NA',	'RO');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Roldanillo',	'VC',	'RO');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Roncesvalles',	'TO',	'RC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Rondon',	'BY',	'RO');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Rosas',	'CA',	'RO');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Rovira',	'TO',	'RR');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Sabana de Torres',	'ST',	'ST');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Sabanagrande',	'AT',	'SG');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Sabanalarga',	'AN',	'SY');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Sabanalarga',	'AT',	'SA');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Sabanalarga',	'CS',	'SB');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Sabanas de San Angel',	'MA',	'SB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Sabaneta',	'AN',	'ST');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Saboya',	'BY',	'SB');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Sacama',	'CS',	'SC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sachica',	'BY',	'SH');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Sahagun [, San Bernardino de]',	'CO',	'SH');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Saladoblanco',	'HU',	'SB');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Salamina',	'CL',	'SL');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Salamina',	'MA',	'SL');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Salazar [de Las Palmas]',	'NS',	'SZ');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Saldana',	'TO',	'SD');
INSERT INTO @tbl VALUES ('Quindio'            ,	     'Salento',	'QD',	'SA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Salgar',	'AN',	'SG');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Samaca',	'BY',	'SA');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Samana',	'CL',	'SA');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Samaniego',	'NA',	'SM');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Sampues',	'SU',	'SA');
INSERT INTO @tbl VALUES ('Huila'            ,	     'San Agustin',	'HU',	'SA');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'San Alberto',	'CE',	'SA');
INSERT INTO @tbl VALUES ('San Andres y Providencia'            ,	     'San Andres',	'SA',	'SA');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Andres',	'ST',	'SA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Andres [de Cuerquia]',	'AN',	'SA');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'San Andres de Sotavento',	'CO',	'SS');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'San Antero',	'CO',	'SA');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'San Antonio',	'TO',	'SA');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'San Antonio del Tequendama',	'CU',	'ST');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Benito',	'ST',	'SN');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'San Benito Abad',	'SU',	'SB');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'San Bernardo',	'CU',	'SB');
INSERT INTO @tbl VALUES ('Narino'            ,	     'San Bernardo',	'NA',	'SN');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'San Bernardo del Viento',	'CO',	'SB');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'San Calixto',	'NS',	'SX');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Carlos',	'AN',	'SC');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'San Carlos',	'CO',	'SC');
INSERT INTO @tbl VALUES ('Meta'            ,	     'San Carlos de Guaroa',	'ME',	'SC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'San Cayetano',	'CU',	'SY');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'San Cayetano',	'NS',	'SC');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Cristobal',	'BL',	'SB');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'San Diego',	'CE',	'SD');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Sandona',	'NA',	'SD');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'San Eduardo',	'BY',	'SD');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Estanislao [de Kostka]',	'BL',	'SE');
INSERT INTO @tbl VALUES ('Guainia'            ,	     'San Felipe',	'GN',	'SF');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Fernando',	'BL',	'SF');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Francisco',	'AN',	'SF');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'San Francisco',	'CU',	'SF');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'San Francisco',	'PU',	'SF');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Gil',	'ST',	'SG');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Jacinto',	'BL',	'SJ');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Jacinto del Cauca',	'BL',	'ST');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Jeronimo',	'AN',	'SM');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Joaquin',	'ST',	'SQ');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'San Jose [de Caldas]',	'CL',	'SJ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Jose de la Montana',	'AN',	'SJ');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'San Jose del Fragua',	'CQ',	'SJ');
INSERT INTO @tbl VALUES ('Guaviare'            ,	     'San Jose del Guaviare',	'GV',	'SJ');
INSERT INTO @tbl VALUES ('Choco'            ,	     'San Jose del Palmar',	'CH',	'SJ');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Jose de Miranda',	'ST',	'SJ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'San Jose de Pare',	'BY',	'JP');
INSERT INTO @tbl VALUES ('Meta'            ,	     'San Juan de Arama',	'ME',	'SA');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'San Juan de Betulia',	'SU',	'SJ');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'San Juan del Cesar',	'LG',	'SJ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'San Juan de Rio Seco',	'CU',	'SJ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Juan de Uraba',	'AN',	'SX');
INSERT INTO @tbl VALUES ('Meta'            ,	     'San Juanito',	'ME',	'SJ');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Juan Nepomuceno',	'BL',	'SN');
INSERT INTO @tbl VALUES ('Narino'            ,	     'San Lorenzo',	'NA',	'SL');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Luis',	'AN',	'SL');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'San Luis',	'TO',	'SL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'San Luis de Gaceno',	'BY',	'LG');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'San Luis de Palenque',	'CS',	'SL');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'San Marcos',	'SU',	'SM');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'San Martin',	'CE',	'SM');
INSERT INTO @tbl VALUES ('Meta'            ,	     'San Martin',	'ME',	'SM');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Martin de Loba',	'BL',	'SM');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'San Mateo',	'BY',	'SM');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'San Miguel',	'PU',	'SM');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Miguel',	'ST',	'SM');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'San Miguel de Sema',	'BY',	'MS');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'San Onofre',	'SU',	'SO');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'San Pablo',	'BL',	'SP');
INSERT INTO @tbl VALUES ('Narino'            ,	     'San Pablo',	'NA',	'SP');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'San Pablo de Borbur',	'BY',	'SP');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'San Pedro',	'SU',	'SP');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'San Pedro',	'VC',	'SP');
INSERT INTO @tbl VALUES ('Narino'            ,	     'San Pedro de Cartago',	'NA',	'SC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Pedro [de Los Milagros]',	'AN',	'SP');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Pedro de Uraba',	'AN',	'SU');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'San Pelayo',	'CO',	'SP');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Rafael',	'AN',	'SN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Roque',	'AN',	'SQ');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'San Sebastian',	'CA',	'SS');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'San Sebastian de Buenavista',	'MA',	'SS');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Santa Ana',	'MA',	'SA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Santa Barbara',	'AN',	'SB');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Santa Barbara',	'NA',	'SB');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Santa Barbara',	'ST',	'SB');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Santa Catalina',	'BL',	'SC');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Santa Cruz',	'NA',	'SZ');
INSERT INTO @tbl VALUES ('Distrito Capital'            ,	     'Santafe de Bogota',	'DC',	'SF');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Santa Helena [del Opon]',	'ST',	'SH');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Santa Isabel',	'TO',	'SI');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Santa Lucia',	'AT',	'SL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Santa Maria',	'BY',	'SX');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Santa Maria',	'HU',	'SM');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Santa Marta',	'MA',	'SM');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Santana',	'BY',	'SN');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Santander de Quilichao',	'CA',	'SN');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Santa Rosa',	'BL',	'SR');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Santa Rosa',	'CA',	'SR');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Santa Rosa de Cabal',	'RI',	'SR');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Santa Rosa del Sur',	'BL',	'SS');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Santa Rosa de Osos',	'AN',	'SR');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Santa Rosa de Viterbo',	'BY',	'RV');
INSERT INTO @tbl VALUES ('Vichada'            ,	     'Santa Rosalia',	'VD',	'SR');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Santa Sofia',	'BY',	'SF');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Santiago',	'NS',	'SG');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Santiago',	'PU',	'SA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Santo Domingo',	'AN',	'SD');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Santo Tomas',	'AT',	'ST');
INSERT INTO @tbl VALUES ('Risaralda'            ,	     'Santuario',	'RI',	'SA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'San Vicente',	'AN',	'SV');
INSERT INTO @tbl VALUES ('Santander'            ,	     'San Vicente de Chucuri',	'ST',	'SV');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'San Vicente del Caguan',	'CQ',	'SV');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'San Zenon',	'MA',	'SZ');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Sapuyes',	'NA',	'SY');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Saravena',	'AR',	'SA');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Sardinata',	'NS',	'SR');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Sasaima',	'CU',	'SA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sativanorte',	'BY',	'SE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sativasur',	'BY',	'SV');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Segovia',	'AN',	'SE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Sesquile',	'CU',	'SE');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Sevilla',	'VC',	'SE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Siachoque',	'BY',	'SI');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Sibate',	'CU',	'SI');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Sibundoy',	'PU',	'SI');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Silos [, Santo Domingo de]',	'NS',	'SI');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Silvania',	'CU',	'SV');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Silvia',	'CA',	'SI');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Simacota',	'ST',	'SI');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Simijaca',	'CU',	'SM');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Simiti',	'BL',	'SI');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Since',	'SU',	'SI');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Sincelejo',	'SU',	'SL');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Sipi',	'CH',	'SI');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Sitionuevo',	'MA',	'SI');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Soacha',	'CU',	'SH');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Soata',	'BY',	'SO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Socha',	'BY',	'SC');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Socorro',	'ST',	'SO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Socota',	'BY',	'ST');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sogamoso',	'BY',	'SG');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Solano',	'CQ',	'SO');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Soledad',	'AT',	'SO');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Solita',	'CQ',	'ST');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Somondoco',	'BY',	'SK');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Sonson',	'AN',	'SS');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Sopetran',	'AN',	'SO');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Soplaviento',	'BL',	'SO');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Sopo',	'CU',	'SO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sora',	'BY',	'SR');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Soraca',	'BY',	'SL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sotaquira',	'BY',	'SQ');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Sotara',	'CA',	'SO');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Suaita',	'ST',	'SU');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Suan',	'AT',	'SU');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Suarez',	'CA',	'SU');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Suarez',	'TO',	'SU');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Suaza',	'HU',	'SU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Subachoque',	'CU',	'SQ');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Sucre',	'ST',	'SC');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Sucre',	'SU',	'SU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Suesca',	'CU',	'SC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Supata',	'CU',	'SP');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Supia',	'CL',	'SU');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Surata',	'ST',	'SR');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Susa',	'CU',	'SS');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Susacon',	'BY',	'SS');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sutamarchan',	'BY',	'SU');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Sutatausa',	'CU',	'SU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Sutatenza',	'BY',	'SZ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tabio',	'CU',	'TB');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Tado',	'CH',	'TA');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Talaigua Nuevo',	'BL',	'TA');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Tamalameque',	'CE',	'TA');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Tamara',	'CS',	'TM');
INSERT INTO @tbl VALUES ('Arauca'            ,	     'Tame',	'AR',	'TA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Tamesis',	'AN',	'TM');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Taminango',	'NA',	'TN');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Tangua',	'NA',	'TG');
INSERT INTO @tbl VALUES ('Vaupes'            ,	     'Taraira',	'VP',	'TA');
INSERT INTO @tbl VALUES ('Amazonas'            ,	     'Tarapaca',	'AM',	'TA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Taraza',	'AN',	'TZ');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Tarqui',	'HU',	'TA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Tarso',	'AN',	'TA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tasco',	'BY',	'TA');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Tauramena',	'CS',	'TN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tausa',	'CU',	'TS');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Tello',	'HU',	'TL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tena',	'CU',	'TE');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Tenerife',	'MA',	'TE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tenjo',	'CU',	'TJ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tenza',	'BY',	'TZ');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Teorama',	'NS',	'TE');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Teruel',	'HU',	'TR');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Tesalia',	'HU',	'TS');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tibacuy',	'CU',	'TY');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tibana',	'BY',	'TN');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tibasosa',	'BY',	'TB');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tibirita',	'CU',	'TI');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Tibu',	'NS',	'TI');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Tierralta',	'CO',	'TI');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Timana',	'HU',	'TI');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Timbio',	'CA',	'TM');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Timbiqui',	'CA',	'TQ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tinjaca',	'BY',	'TI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tipacoque',	'BY',	'TQ');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Tiquisio',	'BL',	'TQ');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Titiribi',	'AN',	'TI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Toca',	'BY',	'TC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tocaima',	'CU',	'TM');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Tocancipa',	'CU',	'TC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Togui',	'BY',	'TG');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Toledo',	'AN',	'TO');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Toledo',	'NS',	'TO');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Tolu',	'SU',	'TO');
INSERT INTO @tbl VALUES ('Sucre'            ,	     'Toluviejo',	'SU',	'TV');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Tona',	'ST',	'TO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Topaga',	'BY',	'TP');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Topaipi',	'CU',	'TP');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Toribio',	'CA',	'TR');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Toro',	'VC',	'TO');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tota',	'BY',	'TO');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Totoro',	'CA',	'TT');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Trinidad',	'CS',	'TR');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Trujillo',	'VC',	'TR');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Tubara',	'AT',	'TU');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Tulua',	'VC',	'TU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Tumaco',	'NA',	'TC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tunja',	'BY',	'TJ');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tunungua',	'BY',	'TU');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Tuquerres',	'NA',	'TQ');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Turbaco',	'BL',	'TC');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Turbana',	'BL',	'TN');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Turbo',	'AN',	'TU');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Turmeque',	'BY',	'TE');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tuta',	'BY',	'TT');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Tutaza',	'BY',	'TS');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Ubala',	'CU',	'UL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Ubaque',	'CU',	'UQ');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Ubate [, Villa de San Diego de]',	'CU',	'UB');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Ulloa',	'VC',	'UL');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Umbita',	'BY',	'UM');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Une',	'CU',	'UN');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Unguia',	'CH',	'UN');
INSERT INTO @tbl VALUES ('Choco'            ,	     'Union Panamericana',	'CH',	'UP');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Uramita',	'AN',	'UM');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Uribia',	'LG',	'UB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Urrao',	'AN',	'UO');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Urumita',	'LG',	'UM');
INSERT INTO @tbl VALUES ('Atlantico'            ,	     'Usiacuri',	'AT',	'US');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Utica',	'CU',	'UT');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Valdivia',	'AN',	'VD');
INSERT INTO @tbl VALUES ('Cordoba'            ,	     'Valencia',	'CO',	'VA');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Valle del Guamuez',	'PU',	'VA');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Valle de San Jose',	'ST',	'VS');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Valle de San Juan',	'TO',	'VS');
INSERT INTO @tbl VALUES ('Cesar'            ,	     'Valledupar',	'CE',	'VA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Valparaiso',	'AN',	'VP');
INSERT INTO @tbl VALUES ('Caqueta'            ,	     'Valparaiso',	'CQ',	'VA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Vegachi',	'AN',	'VG');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Velez',	'ST',	'VZ');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Venadillo',	'TO',	'VE');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Venecia',	'AN',	'VN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Venecia',	'CU',	'OS');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Ventaquemada',	'BY',	'VE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Vergara',	'CU',	'VE');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Versalles',	'VC',	'VE');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Vetas',	'ST',	'VT');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Viani',	'CU',	'VN');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Victoria',	'CL',	'VC');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Vigia del Fuerte',	'AN',	'VF');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Vijes',	'VC',	'VI');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Villa Caro',	'NS',	'VC');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Villa de Leyva',	'BY',	'LE');
INSERT INTO @tbl VALUES ('Norte de Santander'            ,	     'Villa del Rosario',	'NS',	'VR');
INSERT INTO @tbl VALUES ('Putumayo'            ,	     'Villagarzon',	'PU',	'VG');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Villagomez',	'CU',	'VG');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Villahermosa',	'TO',	'VH');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Villamaria',	'CL',	'VM');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Villanueva',	'BL',	'VN');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Villanueva',	'CS',	'VN');
INSERT INTO @tbl VALUES ('La Guajira'            ,	     'Villanueva',	'LG',	'VN');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Villanueva',	'ST',	'VN');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Villapinzon',	'CU',	'VP');
INSERT INTO @tbl VALUES ('Cauca'            ,	     'Villa Rica',	'CA',	'VR');
INSERT INTO @tbl VALUES ('Tolima'            ,	     'Villarrica',	'TO',	'VR');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Villavicencio',	'ME',	'VV');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Villavieja',	'HU',	'VV');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Villeta',	'CU',	'VL');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Viota',	'CU',	'VI');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Viracacha',	'BY',	'VI');
INSERT INTO @tbl VALUES ('Meta'            ,	     'Vista Hermosa',	'ME',	'VH');
INSERT INTO @tbl VALUES ('Caldas'            ,	     'Viterbo',	'CL',	'VB');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Yacopi',	'CU',	'YA');
INSERT INTO @tbl VALUES ('Narino'            ,	     'Yacuanquer',	'NA',	'YA');
INSERT INTO @tbl VALUES ('Huila'            ,	     'Yaguara',	'HU',	'YA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Yali',	'AN',	'YL');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Yarumal',	'AN',	'YR');
INSERT INTO @tbl VALUES ('Vaupes'            ,	     'Yavarate',	'VP',	'YA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Yolombo',	'AN',	'YB');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Yondo',	'AN',	'YD');
INSERT INTO @tbl VALUES ('Casanare'            ,	     'Yopal',	'CS',	'YO');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Yotoco',	'VC',	'YO');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Yumbo',	'VC',	'YU');
INSERT INTO @tbl VALUES ('Bolivar'            ,	     'Zambrano',	'BL',	'ZA');
INSERT INTO @tbl VALUES ('Santander'            ,	     'Zapatoca',	'ST',	'ZA');
INSERT INTO @tbl VALUES ('Antioquia'            ,	     'Zaragoza',	'AN',	'ZA');
INSERT INTO @tbl VALUES ('Valle del Cauca'            ,	     'Zarzal',	'VC',	'ZA');
INSERT INTO @tbl VALUES ('Boyaca'            ,	     'Zetaquira',	'BY',	'ZE');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Zipacon',	'CU',	'ZC');
INSERT INTO @tbl VALUES ('Cundinamarca'            ,	     'Zipaquira',	'CU',	'ZQ');
INSERT INTO @tbl VALUES ('Magdalena'            ,	     'Zona Bananera',	'MA',	'ZB');

SET NOCOUNT OFF

INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) 
	SELECT	DISTINCT @country_id, level_1_nm, level_1_cd
	FROM	@tbl;

-- ======================================================================


INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl	t
		LEFT JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				)

-- ======================================================================

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);


UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

-- ======================================================================

