
/* ==================================================================================
    	Source File		:	setup_nigeria_components.sql
	Author(s)		:	Jitendra Loyal
	Started On		:	11-10-2014
	Module ID		:	CDB
	Last updated		:	11-10-2014
	==================================================================================
		Usage Notes
	----------------------------------------------------------------------------------
		Level 1 Address Components of Nigeria are set-up
	==================================================================================
		Revision History
	----------------------------------------------------------------------------------

	==================================================================================*/

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

-- ======================================================================

DECLARE
	@country_id		INT;

-- ======================================================================
SELECT	@country_id	=	country_id
FROM	countries
WHERE	country_nm	=	'Nigeria';

IF (@@ROWCOUNT = 0)
BEGIN
	RAISERROR ('Country Nigeria not found', 16, 1);
	RETURN;
END

UPDATE	countries
	SET	level_1_address_component	=	'State',
		level_2_address_component	=	'Local.govt.areas',
		level_3_address_component	=	NULL
WHERE	country_id	=	@country_id;

-- ======================================================================

SET NOCOUNT ON
DECLARE	@tbl	TABLE	(	level_1_nm	VARCHAR (50), level_2_nm varchar (50), level_1_cd varchar (5), level_2_cd varchar (5), PRIMARY KEY (level_1_nm, level_2_nm), UNIQUE (level_1_cd, level_2_cd), UNIQUE (level_1_nm, level_2_cd));

INSERT INTO @tbl VALUES ('Borno'            ,	     'Abadam',	'BO',	'AB');
INSERT INTO @tbl VALUES ('Federal Capital Territory'            ,	     'Abaji',	'FC',	'AB');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Abak',	'AK',	'AB');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Abakaliki',	'EB',	'AB');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Aba North',	'AB',	'AN');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Aba South',	'AB',	'AS');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Abeokuta North',	'OG',	'AN');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Abeokuta South',	'OG',	'AS');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Abi',	'CR',	'AB');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Aboh-Mbaise',	'IM',	'AB');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Abua/Odual',	'RI',	'AO');
INSERT INTO @tbl VALUES ('Federal Capital Territory'            ,	     'Abuja Municipal Area Council (AMAC)',	'FC',	'AC');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Adavi',	'KO',	'AD');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Ado',	'BE',	'AO');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ado Ekiti',	'EK',	'AE');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ado-Odo/Ota',	'OG',	'AO');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Afijio',	'OY',	'AF');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Afikpo North',	'EB',	'AN');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Afikpo South',	'EB',	'AS');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Agaie',	'NI',	'AA');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Agatu',	'BE',	'AG');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Agege',	'LA',	'AG');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Aguata',	'AN',	'AG');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Agwara',	'NI',	'AW');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ahiazu-Mbaise',	'IM',	'AZ');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Ahoada East',	'RI',	'AE');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Ahoada West',	'RI',	'AW');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Aiyedade',	'OS',	'AD');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Aiyedire',	'OS',	'AI');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Aiyekire',	'EK',	'AI');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Ajaokuta',	'KO',	'AJ');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Ajeromi-Ifelodun',	'LA',	'AI');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Ajingi',	'KN',	'AJ');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Akamkpa',	'CR',	'AM');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Akinyele',	'OY',	'AK');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Akko',	'GO',	'AK');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Akoko-Edo',	'ED',	'AE');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Akoko North East',	'ON',	'AN');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Akoko North West',	'ON',	'AW');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Akoko South East',	'ON',	'AE');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Akoko South West',	'ON',	'AS');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Akpabuyo',	'CR',	'AY');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Akuku Toru',	'RI',	'AU');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Akure North',	'ON',	'AK');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Akure South',	'ON',	'AR');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Akwanga',	'NA',	'AK');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Albasu',	'KN',	'AL');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Aleiro',	'KE',	'AL');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Alimosho',	'LA',	'AL');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Alkaleri',	'BA',	'AL');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Amuwo-Odofin',	'LA',	'AO');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Anambra East',	'AN',	'AE');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Anambra West',	'AN',	'AW');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Anaocha',	'AN',	'AC');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Andoni',	'RI',	'AN');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Aninri',	'EN',	'AN');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Aniocha North',	'DE',	'AN');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Aniocha South',	'DE',	'AS');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Anka',	'ZA',	'AN');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Ankpa',	'KO',	'AN');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Apa',	'BE',	'AA');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Apapa',	'LA',	'AP');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Ardo-Kola',	'TA',	'AK');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Arewa-Dandi',	'KE',	'AD');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Argungu',	'KE',	'AR');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Arochukwu',	'AB',	'AR');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Asa',	'KW',	'AS');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Asari-Toru',	'RI',	'AT');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Askira/Uba',	'BO',	'AU');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Atakunmosa East',	'OS',	'AE');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Atakunmosa West',	'OS',	'AW');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Atiba',	'OY',	'AT');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Atisbo',	'OY',	'AS');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Augie',	'KE',	'AU');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Auyo',	'JI',	'AU');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Awe',	'NA',	'AW');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Awgu',	'EN',	'AW');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Awka North',	'AN',	'AN');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Awka South',	'AN',	'AS');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Ayamelum',	'AN',	'AY');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Babura',	'JI',	'BA');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Badagry',	'LA',	'BA');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Bagudo',	'KE',	'BA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Bagwai',	'KN',	'BA');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Bakassi',	'CR',	'BA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Bakori',	'KT',	'BK');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Bakura',	'ZA',	'BA');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Balanga',	'GO',	'BA');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Bali',	'TA',	'BA');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Bama',	'BO',	'BM');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Barde',	'YO',	'BA');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Barkin Ladi',	'PL',	'BL');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Baruten',	'KW',	'BA');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Bassa',	'PL',	'BA');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Bassa',	'KO',	'BA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Batagarawa',	'KT',	'BG');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Batsari',	'KT',	'BS');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Bauchi',	'BA',	'BA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Baure',	'KT',	'BU');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Bayo',	'BO',	'BY');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Bebeji',	'KN',	'BE');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Bekwarra',	'CR',	'BE');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Bende',	'AB',	'BE');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Biase',	'CR',	'BI');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Bichi',	'KN',	'BI');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Bida',	'NI',	'BI');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Billiri',	'GO',	'BI');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Bindawa',	'KT',	'BI');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Binji',	'SO',	'BI');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Biriniwa',	'JI',	'BI');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Birnin-Gwari',	'KD',	'BG');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Birnin Kebbi',	'KE',	'BK');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Birnin Kudu',	'JI',	'BK');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Birnin Magaji/Kiyaw',	'ZA',	'BM');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Biu',	'BO',	'BI');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Bodinga',	'SO',	'BO');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Bogoro',	'BA',	'BO');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Boki',	'CR',	'BO');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Bokkos',	'PL',	'BO');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Boluwaduro',	'OS',	'BL');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Bomadi',	'DE',	'BO');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Bonny',	'RI',	'BO');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Borgu',	'NI',	'BR');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Boripe',	'OS',	'BP');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Bosso',	'NI',	'BS');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Brass',	'BY',	'BR');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Buji',	'JI',	'BU');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Bukkuyum',	'ZA',	'BY');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Bungudu',	'ZA',	'BD');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Bunkure',	'KN',	'BU');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Bunza',	'KE',	'BU');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Bursari',	'YO',	'BO');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Buruku',	'BE',	'BU');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Burutu',	'DE',	'BU');
INSERT INTO @tbl VALUES ('Federal Capital Territory'            ,	     'Bwari',	'FC',	'BW');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Calabar-Municipal',	'CR',	'CM');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Calabar South',	'CR',	'CS');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Chanchaga',	'NI',	'CH');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Charanchi',	'KT',	'CH');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Chibok',	'BO',	'CH');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Chikun',	'KD',	'CH');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Dala',	'KN',	'DL');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Damaturu',	'YO',	'DA');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Damban',	'BA',	'DB');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Dambatta',	'KN',	'DM');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Damboa',	'BO',	'DA');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Dandi',	'KE',	'DA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Dandume',	'KT',	'DD');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Dange-Shuni',	'SO',	'DS');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Danja',	'KT',	'DJ');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Dan Musa',	'KT',	'DM');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Darazo',	'BA',	'DZ');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Dass',	'BA',	'DS');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Daura',	'KT',	'DR');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Dawakin Kudu',	'KN',	'DK');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Dawakin Tofa',	'KN',	'DT');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Degema',	'RI',	'DE');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Dekina',	'KO',	'DE');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Demsa',	'AD',	'DE');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Dikwa',	'BO',	'DI');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Disputed Areas',	'TA',	'DA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Doguwa',	'KN',	'DO');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Doma',	'NA',	'DO');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Donga',	'TA',	'DO');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Dukku',	'GO',	'DU');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Dunukofia',	'AN',	'DU');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Dutse',	'JI',	'DU');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Dutsi',	'KT',	'DU');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Dutsin-Ma',	'KT',	'DT');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Eastern Obolo',	'AK',	'EO');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ebonyi',	'EB',	'EB');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Edati',	'NI',	'ED');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ede North',	'OS',	'EN');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ede South',	'OS',	'ES');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Edu',	'KW',	'ED');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Efon',	'EK',	'EF');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Egbado North',	'OG',	'EN');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Egbado South',	'OG',	'ES');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Egbeda',	'OY',	'EG');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Egbedore',	'OS',	'EG');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Egor',	'ED',	'EG');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ehime-Mbano',	'IM',	'EM');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ejigbo',	'OS',	'EJ');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Ekeremor',	'BY',	'EK');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Eket',	'AK',	'EK');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Ekiti',	'KW',	'EK');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ekiti East',	'EK',	'EE');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ekiti South West',	'EK',	'ES');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ekiti West',	'EK',	'EW');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Ekwusigo',	'AN',	'EK');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Eleme',	'RI',	'EL');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Emuoha',	'RI',	'EM');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Emure',	'EK',	'EM');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Enugu East',	'EN',	'EE');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Enugu North',	'EN',	'EN');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Enugu South',	'EN',	'ES');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Epe',	'LA',	'EP');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Esan Central',	'ED',	'EC');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Esan North East',	'ED',	'EN');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Esan South East',	'ED',	'ES');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Esan West',	'ED',	'EW');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ese-Odo',	'ON',	'EO');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Esit Eket',	'AK',	'ES');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Essien Udim',	'AK',	'EU');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Etche',	'RI',	'ET');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ethiope East',	'DE',	'EE');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ethiope West',	'DE',	'EW');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Etim Ekpo',	'AK',	'EP');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Etinan',	'AK',	'ET');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Eti-Osa',	'LA',	'EO');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Etsako Central',	'ED',	'ET');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Etsako East',	'ED',	'EK');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Etsako West',	'ED',	'EO');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Etung',	'CR',	'ET');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ewekoro',	'OG',	'EW');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Ezeagu',	'EN',	'EZ');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ezinihitte',	'IM',	'EZ');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ezza North',	'EB',	'EN');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ezza South',	'EB',	'ES');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Fagge',	'KN',	'FA');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Fakai',	'KE',	'FA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Faskari',	'KT',	'FA');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Fika',	'YO',	'FI');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Fufore',	'AD',	'FU');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Funakaye',	'GO',	'FU');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Fune',	'YO',	'FU');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Funtua',	'KT',	'FU');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Gabasawa',	'KN',	'GB');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Gada',	'SO',	'GA');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Gagarawa',	'JI',	'GG');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Gamawa',	'BA',	'GM');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Ganjuwa',	'BA',	'GN');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Ganye',	'AD',	'GA');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Garki',	'JI',	'GK');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Garko',	'KN',	'GK');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Garum Mallam',	'KN',	'GM');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Gashaka',	'TA',	'GK');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Gassol',	'TA',	'GS');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Gaya',	'KN',	'GY');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Gbako',	'NI',	'GB');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Gboko',	'BE',	'GB');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Geidam',	'YO',	'GE');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Gezawa',	'KN',	'GE');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Giade',	'BA',	'GI');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Girie',	'AD',	'GI');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Giwa',	'KD',	'GI');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Gokana',	'RI',	'GO');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Gombe',	'GO',	'GO');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Gombi',	'AD',	'GO');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Goronyo',	'SO',	'GO');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Gubio',	'BO',	'GB');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Gudu',	'SO',	'GU');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Gujba',	'YO',	'GJ');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Gulani',	'YO',	'GL');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Guma',	'BE',	'GU');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Gumel',	'JI',	'GL');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Gummi',	'ZA',	'GM');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Gurara',	'NI',	'GU');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Guri',	'JI',	'GU');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Gusau',	'ZA',	'GS');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Guyuk',	'AD',	'GU');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Guzamala',	'BO',	'GM');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Gwadabawa',	'SO',	'GW');
INSERT INTO @tbl VALUES ('Federal Capital Territory'            ,	     'Gwagwalada',	'FC',	'GW');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Gwale',	'KN',	'GL');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Gwandu',	'KE',	'GW');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Gwaram',	'JI',	'GM');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Gwarzo',	'KN',	'GW');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Gwer East',	'BE',	'GE');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Gwer West',	'BE',	'GW');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Gwiwa',	'JI',	'GW');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Gwoza',	'BO',	'GW');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Hadejia',	'JI',	'HA');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Hawul',	'BO',	'HA');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Hong',	'AD',	'HO');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibadan North',	'OY',	'IB');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibadan North East',	'OY',	'IN');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibadan North West',	'OY',	'IW');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibadan South East',	'OY',	'IE');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibadan South West',	'OY',	'IS');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Ibaji',	'KO',	'IB');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibarapa Central',	'OY',	'IC');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibarapa East',	'OY',	'IA');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ibarapa North',	'OY',	'IP');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Ibeju/Lekki',	'LA',	'IL');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ibeno',	'AK',	'IB');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ibesikpo Asutan',	'AK',	'IP');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Ibi',	'TA',	'IB');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ibiono Ibom',	'AK',	'II');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Idah',	'KO',	'ID');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Idanre',	'ON',	'ID');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ideato North',	'IM',	'IN');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ideato South',	'IM',	'ID');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Idemili North',	'AN',	'IN');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Idemili south',	'AN',	'IS');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ido',	'OY',	'ID');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Idosi-Osi',	'EK',	'ID');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Ifako-Ijaye',	'LA',	'II');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ife Central',	'OS',	'IC');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ifedayo',	'OS',	'IF');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ifedore',	'ON',	'IF');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ife East',	'OS',	'IE');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Ifelodun',	'KW',	'IF');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ifelodun',	'OS',	'ID');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ife North',	'OS',	'IN');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ife South',	'OS',	'IS');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ifo',	'OG',	'IF');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Igabi',	'KD',	'IG');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Igalamela-Odolu',	'KO',	'IO');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Igbo-Etiti',	'EN',	'IE');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Igbo-Eze North',	'EN',	'IN');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Igbo-Eze South',	'EN',	'IS');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Igueben',	'ED',	'IG');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Ihiala',	'AN',	'IH');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ihitte/Uboma',	'IM',	'IU');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ijebu East',	'OG',	'IE');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ijebu North',	'OG',	'IJ');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ijebu North East',	'OG',	'IN');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ijebu Ode',	'OG',	'IO');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ijero',	'EK',	'IJ');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Ijumu',	'KO',	'IJ');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ika',	'AK',	'IK');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ika North East',	'DE',	'IE');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Ikara',	'KD',	'IK');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ika South',	'DE',	'IK');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ikeduru',	'IM',	'IK');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Ikeja',	'LA',	'IJ');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ikenne',	'OG',	'IK');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ikere',	'EK',	'IR');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ikole',	'EK',	'IK');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Ikom',	'CR',	'IK');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ikono',	'AK',	'IO');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Ikorodu',	'LA',	'ID');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ikot Abasi',	'AK',	'IA');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ikot Ekpene',	'AK',	'IE');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Ikpoba-Okha',	'ED',	'IO');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Ikwerre',	'RI',	'IK');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ikwo',	'EB',	'IK');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Ikwuano',	'AB',	'IK');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ila',	'OS',	'IL');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ilaje',	'ON',	'IL');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ilejemeje',	'EK',	'IL');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ile-Oluji-Okeigbo',	'ON',	'IO');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ilesha East',	'OS',	'IH');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ilesha West',	'OS',	'IW');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Illela',	'SO',	'IL');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Ilorin East',	'KW',	'IE');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Ilorin South',	'KW',	'IS');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Ilorin West',	'KW',	'IW');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Imeko-Afon',	'OG',	'IA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Ingawa',	'KT',	'IN');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ini',	'AK',	'IN');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ipokia',	'OG',	'IP');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Irele',	'ON',	'IR');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Irepo',	'OY',	'IR');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Irepodun',	'OS',	'IP');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Irepodun',	'KW',	'IR');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Irepodun/Ifelodun',	'EK',	'II');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Irewole',	'OS',	'IR');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Isa',	'SO',	'IS');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Ise/Orun',	'EK',	'IO');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Iseyin',	'OY',	'IY');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ishielu',	'EB',	'IS');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Isiala Mbano',	'IM',	'IM');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Isiala-Ngwa North',	'AB',	'IN');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Isiala-Ngwa South',	'AB',	'IS');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Isin',	'KW',	'IN');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Isi-Uzo',	'EN',	'IU');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Isokan',	'OS',	'IK');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Isoko North',	'DE',	'IN');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Isoko South',	'DE',	'IS');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Isu',	'IM',	'IS');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Isuikwato',	'AB',	'IT');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Itas/Gadau',	'BA',	'IG');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Itesiwaju',	'OY',	'IT');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Itu',	'AK',	'IT');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ivo',	'EB',	'IV');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Iwajowa',	'OY',	'IJ');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Iwo',	'OS',	'IO');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Izzi',	'EB',	'IZ');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Jaba',	'KD',	'JA');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Jada',	'AD',	'JA');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Jahun',	'JI',	'JA');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Jakusko',	'YO',	'JA');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Jalingo',	'TA',	'JA');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Jama''are',	'BA',	'JA');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Jega',	'KE',	'JE');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Jema''a',	'KD',	'JE');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Jere',	'BO',	'JE');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Jibia',	'KT',	'JI');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Jos East',	'PL',	'JE');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Jos North',	'PL',	'JN');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Jos South',	'PL',	'JS');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Kabba/Bunu',	'KO',	'KB');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kabo',	'KN',	'KB');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kachia',	'KD',	'KC');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kaduna North',	'KD',	'KN');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kaduna South',	'KD',	'KS');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Kafin Hausa',	'JI',	'KH');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Kafur',	'KT',	'KF');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Kaga',	'BO',	'KA');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kagarko',	'KD',	'KG');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Kaiama',	'KW',	'KA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Kaita',	'KT',	'KT');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Kajola',	'OY',	'KA');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kajuru',	'KD',	'KJ');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Kala/Balge',	'BO',	'KB');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Kalgo',	'KE',	'KA');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Kaltungo',	'GO',	'KA');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Kanam',	'PL',	'KM');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Kankara',	'KT',	'KN');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Kanke',	'PL',	'KK');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Kankia',	'KT',	'KK');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kano Municipal',	'KN',	'KM');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Karasuwa',	'YO',	'KA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Karaye',	'KN',	'KY');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Karim-Lamido',	'TA',	'KL');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Karu',	'NA',	'KA');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Katagum',	'BA',	'KA');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Katcha',	'NI',	'KA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Katsina',	'KT',	'KA');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Katsina-Ala',	'BE',	'KA');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Kaugama',	'JI',	'KG');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kaura',	'KD',	'KA');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Kauran Namoda',	'ZA',	'KN');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kauru',	'KD',	'KR');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Kazaure',	'JI',	'KZ');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Keana',	'NA',	'KN');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Kebbe',	'SO',	'KE');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Keffi',	'NA',	'KF');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Khana',	'RI',	'KH');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kibiya',	'KN',	'KI');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Kirfi',	'BA',	'KI');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Kiri Kasama',	'JI',	'KK');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kiru',	'KN',	'KR');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Kiyawa',	'JI',	'KI');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Kogi',	'KO',	'KO');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Koko/Besse',	'KE',	'KB');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Kokona',	'NA',	'KO');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Kolokuma/Opokuma',	'BY',	'KO');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Konduga',	'BO',	'KO');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Konshisha',	'BE',	'KO');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Kontagora',	'NI',	'KO');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Kosofe',	'LA',	'KO');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kubau',	'KD',	'KB');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Kudan',	'KD',	'KU');
INSERT INTO @tbl VALUES ('Federal Capital Territory'            ,	     'Kuje',	'FC',	'KU');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Kukawa',	'BO',	'KU');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kumbotso',	'KN',	'KT');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kunchi',	'KN',	'KN');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Kura',	'KN',	'KU');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Kurfi',	'KT',	'KR');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Kurmi',	'TA',	'KU');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Kusada',	'KT',	'KD');
INSERT INTO @tbl VALUES ('Federal Capital Territory'            ,	     'Kwali',	'FC',	'KW');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Kwami',	'GO',	'KW');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Kwande',	'BE',	'KW');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Kware',	'SO',	'KW');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Kwaya Kusar',	'BO',	'KK');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Lafia',	'NA',	'LA');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Lagelu',	'OY',	'LA');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Lagos Island',	'LA',	'LI');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Lagos Mainland',	'LA',	'LM');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Lamurde',	'AD',	'LA');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Langtang North',	'PL',	'LN');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Langtang South',	'PL',	'LS');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Lapai',	'NI',	'LP');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Lau',	'TA',	'LA');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Lavun',	'NI',	'LV');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Lere',	'KD',	'LE');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Logo',	'BE',	'LO');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Lokoja',	'KO',	'LO');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Machina',	'YO',	'MA');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Madagali',	'AD',	'MD');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Madobi',	'KN',	'MD');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Mafa',	'BO',	'MF');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Magama',	'NI',	'MM');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Magumeri',	'BO',	'MM');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Mai''adua',	'KT',	'MD');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Maiduguri',	'BO',	'MD');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Maigatari',	'JI',	'MA');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Maiha',	'AD',	'MH');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Maiyama',	'KE',	'MA');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Makarfi',	'KD',	'MA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Makoda',	'KN',	'MK');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Makurdi',	'BE',	'MA');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Malam Madori',	'JI',	'MM');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Malumfashi',	'KT',	'MF');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Mangu',	'PL',	'MA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Mani',	'KT',	'MN');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Maradun',	'ZA',	'MD');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Mariga',	'NI',	'MR');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Marte',	'BO',	'MT');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Maru',	'ZA',	'MU');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Mashegu',	'NI',	'MS');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Mashi',	'KT',	'MS');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Matazu',	'KT',	'MZ');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Mayo-Belwa',	'AD',	'MB');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Mbaitoli',	'IM',	'MB');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Mbo',	'AK',	'MB');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Michika',	'AD',	'MI');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Miga',	'JI',	'MI');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Mikang',	'PL',	'MI');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Minjibir',	'KN',	'MI');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Misau',	'BA',	'MI');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Mkpat Enin',	'AK',	'ME');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Moba',	'EK',	'MO');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Mobbar',	'BO',	'MB');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Mokwa',	'NI',	'MO');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Monguno',	'BO',	'MN');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Mopa-Muro',	'KO',	'MM');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Moro',	'KW',	'MO');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Mubi North',	'AD',	'MN');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Mubi South',	'AD',	'MS');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Musawa',	'KT',	'MU');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Mushin',	'LA',	'MU');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Muya',	'NI',	'MU');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Nafada',	'GO',	'NA');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Nangere',	'YO',	'NA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Nassarawa',	'KN',	'NA');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Nassarawa',	'NA',	'NA');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Nassarawa Egon',	'NA',	'NE');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ndokwa East',	'DE',	'NE');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ndokwa West',	'DE',	'NW');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Nembe',	'BY',	'NE');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Ngala',	'BO',	'NL');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Nganzai',	'BO',	'NZ');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Ngaski',	'KE',	'NG');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ngor-Okpala',	'IM',	'NO');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Nguru',	'YO',	'NG');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Ningi',	'BA',	'NI');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Njaba',	'IM',	'NJ');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Njikoka',	'AN',	'NJ');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Nkanu East',	'EN',	'NE');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Nkanu West',	'EN',	'NW');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Nkwerre',	'IM',	'NK');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Nnewi North',	'AN',	'NN');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Nnewi South',	'AN',	'NS');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Nsit Atai',	'AK',	'NA');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Nsit Ibom',	'AK',	'NI');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Nsit Ubium',	'AK',	'NU');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Nsukka',	'EN',	'NS');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Numan',	'AD',	'NU');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Nwangele',	'IM',	'NW');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Obafemi-Owode',	'OG',	'OO');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Obanliku',	'CR',	'OL');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Obi',	'NA',	'OB');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Obi',	'BE',	'OB');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Obi Ngwa',	'AB',	'OB');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Obio/Akpor',	'RI',	'OA');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Obokun',	'OS',	'OB');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Obot Akara',	'AK',	'OB');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Obowo',	'IM',	'OB');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Obubra',	'CR',	'OB');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Obudu',	'CR',	'OU');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Odeda',	'OG',	'OD');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Odigbo',	'ON',	'OD');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Odogbolu',	'OG',	'OB');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Odo-Otin',	'OS',	'OO');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Odukpani',	'CR',	'OP');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Offa',	'KW',	'OF');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Ofu',	'KO',	'OF');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Ogbadibo',	'BE',	'OG');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Ogba/Egbema/Ndoni',	'RI',	'OE');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Ogbaru',	'AN',	'OG');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Ogbia',	'BY',	'OG');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ogbmosho South',	'OY',	'OS');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ogbomosho North',	'OY',	'ON');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Ogoja',	'CR',	'OG');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ogo Oluwa',	'OY',	'OO');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Ogori/Magongo',	'KO',	'OM');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Ogu/Bolo',	'RI',	'OB');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Ogun Waterside',	'OG',	'OW');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Oguta',	'IM',	'OG');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Ohafia',	'AB',	'OH');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Ohaji/Egbema',	'IM',	'OJ');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ohaozara',	'EB',	'OZ');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Ohaukwu',	'EB',	'OK');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Ohimini',	'BE',	'OH');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Oji-River',	'EN',	'OR');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Ojo',	'LA',	'OJ');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Oju',	'BE',	'OJ');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Oke-Ero',	'KW',	'OO');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Okehi',	'KO',	'OH');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Okene',	'KO',	'ON');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Okigwe',	'IM',	'OK');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Okitipupa',	'ON',	'OK');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Okobo',	'AK',	'OK');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Okpe',	'DE',	'OK');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Okpokwu',	'BE',	'OK');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Okrika',	'RI',	'OK');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Olamabolo',	'KO',	'OB');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Ola-Oluwa',	'OS',	'OL');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Olorunda',	'OS',	'ON');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Olorunsogo',	'OY',	'OL');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Oluyole',	'OY',	'OY');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Omala',	'KO',	'OL');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Omumma',	'RI',	'OM');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ona-Ara',	'OY',	'OA');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ondo East',	'ON',	'OE');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ondo West',	'ON',	'OW');
INSERT INTO @tbl VALUES ('Ebonyi'            ,	     'Onicha',	'EB',	'ON');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Onitsha North',	'AN',	'ON');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Onitsha South',	'AN',	'OS');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Onna',	'AK',	'ON');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Opobo/Nkoro',	'RI',	'ON');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Oredo',	'ED',	'OR');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Orelope',	'OY',	'OR');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Orhionmwon',	'ED',	'OH');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Oriade',	'OS',	'OD');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Ori Ire',	'OY',	'OI');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Orlu',	'IM',	'OL');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Orolu',	'OS',	'OR');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Oron',	'AK',	'OR');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Orsu',	'IM',	'OR');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Oru East',	'IM',	'OE');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Oruk Anam',	'AK',	'OA');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Orumba North',	'AN',	'OR');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Orumba South',	'AN',	'OB');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Oru West',	'IM',	'OU');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Ose',	'ON',	'OS');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Oshimili North',	'DE',	'ON');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Oshimili South',	'DE',	'OS');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Oshodi-Isolo',	'LA',	'OI');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Osisioma Ngwa',	'AB',	'OS');
INSERT INTO @tbl VALUES ('Osun'            ,	     'Osogbo',	'OS',	'OS');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Oturkpo',	'BE',	'OT');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Ovia North East',	'ED',	'ON');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Ovia South West',	'ED',	'OS');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Owan East',	'ED',	'OE');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Owan West',	'ED',	'OW');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Owerri-Municipal',	'IM',	'OM');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Owerri North',	'IM',	'ON');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Owerri West',	'IM',	'OW');
INSERT INTO @tbl VALUES ('Ondo'            ,	     'Owo',	'ON',	'OO');
INSERT INTO @tbl VALUES ('Ekiti'            ,	     'Oye',	'EK',	'OY');
INSERT INTO @tbl VALUES ('Anambra'            ,	     'Oyi',	'AN',	'OY');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Oyigbo',	'RI',	'OY');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Oyo East',	'OY',	'OE');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Oyo West',	'OY',	'OW');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Oyun',	'KW',	'OY');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Paikoro',	'NI',	'PA');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Pankshin',	'PL',	'PA');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Patani',	'DE',	'PA');
INSERT INTO @tbl VALUES ('Kwara'            ,	     'Pategi',	'KW',	'PA');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Port-Harcourt',	'RI',	'PH');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Potiskum',	'YO',	'PO');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Qua''an Pan',	'PL',	'QP');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Rabah',	'SO',	'RA');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Rafi',	'NI',	'RA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Rano',	'KN',	'RA');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Remo North',	'OG',	'RN');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Rijau',	'NI',	'RI');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Rimi',	'KT',	'RI');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Rimin Gado',	'KN',	'RG');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Ringim',	'JI',	'RI');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Riyom',	'PL',	'RI');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Rogo',	'KN',	'RO');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Roni',	'JI',	'RO');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Sabon Birni',	'SO',	'SB');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Sabon-Gari',	'KD',	'SG');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Sabuwa',	'KT',	'SB');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Safana',	'KT',	'SF');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Sagbama',	'BY',	'SA');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Sakaba',	'KE',	'SA');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Saki East',	'OY',	'SE');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Saki West',	'OY',	'SW');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Sandamu',	'KT',	'SN');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Sanga',	'KD',	'SA');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Sapele',	'DE',	'SA');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Sardauna',	'TA',	'SA');
INSERT INTO @tbl VALUES ('Ogun'            ,	     'Shagamu',	'OG',	'SH');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Shagari',	'SO',	'SH');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Shanga',	'KE',	'SH');
INSERT INTO @tbl VALUES ('Borno'            ,	     'Shani',	'BO',	'SH');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Shanono',	'KN',	'SH');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Shelleng',	'AD',	'SH');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Shendam',	'PL',	'SH');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Shinkafi',	'ZA',	'SH');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Shira',	'BA',	'SH');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Shiroro',	'NI',	'SH');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Shomgom',	'GO',	'SH');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Shomolu',	'LA',	'SH');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Silame',	'SO',	'SI');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Soba',	'KD',	'SO');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Sokoto North',	'SO',	'SN');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Sokoto South',	'SO',	'SS');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Song',	'AD',	'SO');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Southern Ijaw',	'BY',	'SI');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Suleja',	'NI',	'SU');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Sule Tankarkar',	'JI',	'ST');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Sumaila',	'KN',	'SU');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Suru',	'KE',	'SU');
INSERT INTO @tbl VALUES ('Lagos'            ,	     'Surulere',	'LA',	'SU');
INSERT INTO @tbl VALUES ('Oyo'            ,	     'Surulere',	'OY',	'SU');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Tafa',	'NI',	'TA');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Tafawa-Balewa',	'BA',	'TB');
INSERT INTO @tbl VALUES ('Rivers'            ,	     'Tai',	'RI',	'TA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Takai',	'KN',	'TK');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Takum',	'TA',	'TA');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Talata Mafara',	'ZA',	'TM');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Tambuwal',	'SO',	'TW');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Tangaza',	'SO',	'TZ');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Tarauni',	'KN',	'TR');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Tarka',	'BE',	'TA');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Tarmua',	'YO',	'TA');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Taura',	'JI',	'TA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Tofa',	'KN',	'TO');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Toro',	'BA',	'TO');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Toto',	'NA',	'TO');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Toungo',	'AD',	'TE');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Tsafe',	'ZA',	'TS');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Tsanyawa',	'KN',	'TS');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Tudun Wada',	'KN',	'TW');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Tureta',	'SO',	'TT');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Udenu',	'EN',	'UN');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Udi',	'EN',	'UD');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Udu',	'DE',	'UD');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Udung Uko',	'AK',	'UU');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ughelli North',	'DE',	'UN');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ughelli South',	'DE',	'US');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Ugwunagbo',	'AB',	'UG');
INSERT INTO @tbl VALUES ('Edo'            ,	     'Uhunmwonde',	'ED',	'UH');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Ukanafun',	'AK',	'UK');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Ukum',	'BE',	'UK');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Ukwa East',	'AB',	'UE');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Ukwa West',	'AB',	'UW');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Ukwuani',	'DE',	'UK');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Umuahia North',	'AB',	'UN');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Umuahia South',	'AB',	'US');
INSERT INTO @tbl VALUES ('Abia'            ,	     'Umu-Nneochi',	'AB',	'UM');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Ungogo',	'KN',	'UN');
INSERT INTO @tbl VALUES ('Imo'            ,	     'Unuimo',	'IM',	'UN');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Uruan',	'AK',	'UR');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Urue-Offong/Oruko',	'AK',	'UO');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Ushongo',	'BE',	'US');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Ussa',	'TA',	'US');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Uvwie',	'DE',	'UV');
INSERT INTO @tbl VALUES ('Akwa Ibom'            ,	     'Uyo',	'AK',	'UY');
INSERT INTO @tbl VALUES ('Enugu'            ,	     'Uzo-Uwani',	'EN',	'UU');
INSERT INTO @tbl VALUES ('Benue'            ,	     'Vandeikya',	'BE',	'VA');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Wamako',	'SO',	'WA');
INSERT INTO @tbl VALUES ('Nasarawa'            ,	     'Wamba',	'NA',	'WA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Warawa',	'KN',	'WA');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Warji',	'BA',	'WA');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Warri North',	'DE',	'WN');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Warri South',	'DE',	'WS');
INSERT INTO @tbl VALUES ('Delta'            ,	     'Warri South West',	'DE',	'WW');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Wasagu/Danko',	'KE',	'WD');
INSERT INTO @tbl VALUES ('Plateau'            ,	     'Wase',	'PL',	'WA');
INSERT INTO @tbl VALUES ('Kano'            ,	     'Wudil',	'KN',	'WU');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Wukari',	'TA',	'WU');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Wurno',	'SO',	'WU');
INSERT INTO @tbl VALUES ('Niger'            ,	     'Wushishi',	'NI',	'WU');
INSERT INTO @tbl VALUES ('Sokoto'            ,	     'Yabo',	'SO',	'YA');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Yagba East',	'KO',	'YE');
INSERT INTO @tbl VALUES ('Kogi'            ,	     'Yagba West',	'KO',	'YW');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Yakurr',	'CR',	'YK');
INSERT INTO @tbl VALUES ('Cross River'            ,	     'Yala',	'CR',	'YL');
INSERT INTO @tbl VALUES ('Gombe'            ,	     'Yamaltu/Deba',	'GO',	'YD');
INSERT INTO @tbl VALUES ('Jigawa'            ,	     'Yankwashi',	'JI',	'YA');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Yauri',	'KE',	'YA');
INSERT INTO @tbl VALUES ('Bayelsa'            ,	     'Yenegoa',	'BY',	'YE');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Yola North',	'AD',	'YN');
INSERT INTO @tbl VALUES ('Adamawa'            ,	     'Yola South',	'AD',	'YS');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Yorro',	'TA',	'YO');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Yunusari',	'YO',	'YN');
INSERT INTO @tbl VALUES ('Yobe'            ,	     'Yusufari',	'YO',	'YF');
INSERT INTO @tbl VALUES ('Bauchi'            ,	     'Zaki',	'BA',	'ZA');
INSERT INTO @tbl VALUES ('Katsina'            ,	     'Zango',	'KT',	'ZA');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Zangon-Kataf',	'KD',	'ZK');
INSERT INTO @tbl VALUES ('Kaduna'            ,	     'Zarki',	'KD',	'ZA');
INSERT INTO @tbl VALUES ('Taraba'            ,	     'Zing',	'TA',	'ZI');
INSERT INTO @tbl VALUES ('Zamfara'            ,	     'Zurmi',	'ZA',	'ZU');
INSERT INTO @tbl VALUES ('Kebbi'            ,	     'Zuru',	'KE',	'ZU');

SET NOCOUNT OFF

INSERT INTO level_1_address_components ( country_id, level_1_address_component_nm, level_1_address_component_cd ) 
	SELECT	DISTINCT @country_id, level_1_nm, level_1_cd
	FROM	@tbl;

-- ======================================================================


INSERT INTO level_2_address_components ( level_2_address_component_nm, level_2_address_component_cd, level_1_address_component_id )
	SELECT	level_2_nm, level_2_cd, level_1_address_component_id
	FROM	@tbl	t
		LEFT JOIN	level_1_address_components	l1
			ON	(	l1.level_1_address_component_nm	=	t.level_1_nm
				AND	l1.country_id					=	@country_id
				)

-- ======================================================================

UPDATE	l2
	SET	is_authentic	=	1
FROM	level_2_address_components	l2
	JOIN	level_1_address_components	l1
		ON	(	l1.level_1_address_component_id	=	l2.level_1_address_component_id
			AND	l1.country_id	=	@country_id
			);


UPDATE	level_1_address_components
	SET	is_authentic	=	1
WHERE	country_id	=	@country_id;

-- ======================================================================

